In [28]:
######In this notebook, we cross product features to get combined featurs -> 4-rank tensor->2-rank matrix

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data_dir = "../Datasets/consumption.csv"
csp = pd.read_csv(data_dir).head(100)
csp = csp[csp["indicator"]=="Share of product/service in total expenditure (%)"]
csp

,country_code,area,product,value,exchange_rate,consumption_segment,indicator,ppp_conversion_factor,unit
0,THA,National,Fresh or Chilled Vegetables Other than Potatoes,0.03390,31.686000,Lowest,Share of product/service in total expenditure (%),18.073000,%
1,PHL,National,Fresh or Chilled Vegetables Other than Potatoes,0.02300,45.109664,Lowest,Share of product/service in total expenditure (%),27.525623,%
2,MNG,National,Fresh or Chilled Vegetables Other than Potatoes,0.01520,1357.064000,Lowest,Share of product/service in total expenditure (%),785.100000,%
3,KHM,National,Fresh or Chilled Vegetables Other than Potatoes,0.04650,4184.917000,Lowest,Share of product/service in total expenditure (%),2134.943000,%
4,LAO,National,Fresh or Chilled Vegetables Other than Potatoes,0.06130,8258.770000,Lowest,Share of product/service in total expenditure (%),4268.571000,%
5,IDN,National,Fresh or Chilled Vegetables Other than Potatoes,0.05070,9090.433000,Lowest,Share of product/service in total expenditure (%),5467.129000,%
6,VNM,National,Fresh or Chilled Vegetables Other than Potatoes,0.02470,18612.917000,Lowest,Share of product/service in total expenditure (%),8847.418000,%
37,LVA,National,Fresh or Chilled Vegetables Other than Potatoes,0.03570,0.530000,Lowest,Share of product/service in total expenditure (%),0.418000,%
38,MNE,National,Fresh or Chilled Vegetables Other than Potatoes,0.07240,0.755000,Lowest,Share of product/service in total expenditure (%),0.484000,%
39,AZE,National,Fresh or Chilled Vegetables Other than Potatoes,0.06970,0.803000,Lowest,Share of product/service in total expenditure (%),0.517000,%
40,BGR,National,Fresh or Chilled Vegetables Other than Potatoes,0.05340,1.477000,Lowest,Share of product/service in total expenditure (%),0.811000,%
41,BIH,National,Fresh or Chilled Vegetables Other than Potatoes,0.01870,1.477000,Lowest,Share of product/service in total expenditure (%),0.901000,%
42,TUR,National,Fresh or Chilled Vegetables Other than Potatoes,0.06270,1.503000,Lowest,Share of product/service in total expenditure (%),1.162000,%
43,LTU,National,Fresh or Chilled Vegetables Other than Potatoes,0.03530,2.606000,Lowest,Share of product/service in total expenditure (%),1.834000,%
44,ROU,National,Fresh or Chilled Vegetables Other than Potatoes,0.06780,3.178000,Lowest,Share of product/service in total expenditure (%),2.021000,%
45,TJK,National,Fresh or Chilled Vegetables Other than Potatoes,0.06080,4.379000,Lowest,Share of product/service in total expenditure (%),1.410000,%
46,UKR,National,Fresh or Chilled Vegetables Other than Potatoes,0.06240,7.936000,Lowest,Share of product/service in total expenditure (%),2.990000,%
47,MDA,National,Fresh or Chilled Vegetables Other than Potatoes,0.03400,12.369000,Lowest,Share of product/service in total expenditure (%),6.632000,%
48,RUS,National,Fresh or Chilled Vegetables Other than Potatoes,0.05920,30.368000,Lowest,Share of product/service in total expenditure (%),17.411000,%
49,KGZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.05530,45.964000,Lowest,Share of product/service in total expenditure (%),19.458000,%
50,MKD,National,Fresh or Chilled Vegetables Other than Potatoes,0.07740,46.485000,Lowest,Share of product/service in total expenditure (%),22.320000,%
51,SRB,National,Fresh or Chilled Vegetables Other than Potatoes,0.06990,77.728933,Lowest,Share of product/service in total expenditure (%),44.773690,%
52,ALB,National,Fresh or Chilled Vegetables Other than Potatoes,0.08430,103.936000,Lowest,Share of product/service in total expenditure (%),57.851000,%
53,KAZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.03620,147.355000,Lowest,Share of product/service in total expenditure (%),94.239000,%
54,ARM,National,Fresh or Chilled Vegetables Other than Potatoes,0.07480,373.660000,Lowest,Share of product/service in total expenditure (%),230.056000,%
55,BLR,National,Fresh or Chilled Vegetables Other than Potatoes,0.00842,2978.510000,Lowest,Share of product/service in total expenditure (%),1103.222000,%
78,LVA,National,Fresh or Chilled Vegetables Other than Potatoes,0.01140,0.530000,Higher,Share of product/service in total expenditure (%),0.418000,%
79,MNE,National,Fresh or Chilled Vegetables Other than Potatoes,0.01620,0.755000,Higher,Share of product/service in total expenditure (%),0.484000,%
80,AZE,National,Fresh or Chilled Vegetables Other than Potatoes,0.01900,0.803000,Higher,Share of product/service in total expenditure (%),0.517000,%
81,BGR,National,Fresh or Chilled Vegetables Other than Potatoes,0.01290,1.477000,Higher,Share of product/service in total expenditure (%),0.811000,%
82,BIH,National,Fresh or Chilled Vegetables Other than Potatoes,0.01910,1.477000,Higher,Share of product/service in total expenditure (%),0.901000,%
83,TUR,National,Fresh or Chilled Vegetables Other than Potatoes,0.01620,1.503000,Higher,Share of product/service in total expenditure (%),1.162000,%
84,LTU,National,Fresh or Chilled Vegetables Other than Potatoes,0.01150,2.606000,Higher,Share of product/service in total expenditure (%),1.834000,%
85,ROU,National,Fresh or Chilled Vegetables Other than Potatoes,0.01880,3.178000,Higher,Share of product/service in total expenditure (%),2.021000,%
86,TJK,National,Fresh or Chilled Vegetables Other than Potatoes,0.03540,4.379000,Higher,Share of product/service in total expenditure (%),1.410000,%
87,UKR,National,Fresh or Chilled Vegetables Other than Potatoes,0.03390,7.936000,Higher,Share of product/service in total expenditure (%),2.990000,%
88,MDA,National,Fresh or Chilled Vegetables Other than Potatoes,0.01390,12.369000,Higher,Share of product/service in total expenditure (%),6.632000,%
89,RUS,National,Fresh or Chilled Vegetables Other than Potatoes,0.01540,30.368000,Higher,Share of product/service in total expenditure (%),17.411000,%
90,KGZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.02850,45.964000,Higher,Share of product/service in total expenditure (%),19.458000,%
91,MKD,National,Fresh or Chilled Vegetables Other than Potatoes,0.03160,46.485000,Higher,Share of product/service in total expenditure (%),22.320000,%
92,SRB,National,Fresh or Chilled Vegetables Other than Potatoes,0.03020,77.728933,Higher,Share of product/service in total expenditure (%),44.773690,%
93,ALB,National,Fresh or Chilled Vegetables Other than Potatoes,0.04710,103.936000,Higher,Share of product/service in total expenditure (%),57.851000,%
94,KAZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.02580,147.355000,Higher,Share of product/service in total expenditure (%),94.239000,%
95,ARM,National,Fresh or Chilled Vegetables Other than Potatoes,0.00476,373.660000,Higher,Share of product/service in total expenditure (%),230.056000,%
96,BLR,National,Fresh or Chilled Vegetables Other than Potatoes,0.01450,2978.510000,Higher,Share of product/service in total expenditure (%),1103.222000,%

In [2]:
csp["product"].unique()

array(['Fresh or Chilled Vegetables Other than Potatoes', 'Fresh Milk',
       'Education', 'Pork', 'Lamb, Mutton and Goat',
       'Paramedical Services', 'Pasta Products', 'Water Utility ',
       'Frozen, Preserved or Processed Fruit and Fruit-based Product',
       'Frozen, Preserved or Processed Vegetables and Vegetable-based Product',
       'Cheese', 'Shoes and Other Footwear',
       'Fresh, Chilled or Frozen Fish and Seafood',
       'Preserved or Processed Fish and Seafood',
       'Fresh or Chilled Fruit', 'Insurance', 'Rice',
       'Fresh or Chilled Potatoes', 'Other Medical Products', 'Poultry',
       'Hospital Services', 'Preserved Milk and Other Milk Products',
       'Coffee, Tea and Cocoa', 'Medical Services', 'Spirits', 'Wine',
       'Beef and Veal',
       'Clothing Material, Other Articles of Clothing and Clothing Accessories',
       'Eggs and Egg-Based Products', 'Beer', 'Tobacco',
       'Butter and Margarine', 'Other Edible Oil and Fats',
       'Therapeutic Appliances and Equipment', 'Narcotics',
       'Jams, Marmalades and Honey', 'Garments', 'Sugar',
       'Dental Services', 'Bread', 'Pharmaceuticals Products'],
      dtype=object)

In [15]:
df = pd.DataFrame()
ccs = []

for index, row in csp.iterrows():
    area = row["area"]
    consumption_segment = row["consumption_segment"]
    product = row["product"]
    country_code = row["country_code"]
    value = row["value"]
    i_index = str(area)+","+str(consumption_segment)+","+str(product)
    if not country_code in df.keys():
        df[country_code] = 0
    df[country_code, i_index] =0

df

Empty DataFrame
Columns: [THA, (THA, National,Lowest,Fresh or Chilled Vegetables Other than Potatoes), PHL, (PHL, National,Lowest,Fresh or Chilled Vegetables Other than Potatoes), MNG, (MNG, National,Lowest,Fresh or Chilled Vegetables Other than Potatoes), KHM, (KHM, National,Lowest,Fresh or Chilled Vegetables Other than Potatoes), LAO, (LAO, National,Lowest,Fresh or Chilled Vegetables Other than Potatoes)]
Index: []

In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data_dir = "../Datasets/consumption.csv"
csp = pd.read_csv(data_dir)#.head(100)
csp = csp[csp["indicator"]=="Share of product/service in total expenditure (%)"]
csp

,country_code,area,product,value,exchange_rate,consumption_segment,indicator,ppp_conversion_factor,unit
0,THA,National,Fresh or Chilled Vegetables Other than Potatoes,0.033900,31.686000,Lowest,Share of product/service in total expenditure (%),18.073000,%
1,PHL,National,Fresh or Chilled Vegetables Other than Potatoes,0.023000,45.109664,Lowest,Share of product/service in total expenditure (%),27.525623,%
2,MNG,National,Fresh or Chilled Vegetables Other than Potatoes,0.015200,1357.064000,Lowest,Share of product/service in total expenditure (%),785.100000,%
3,KHM,National,Fresh or Chilled Vegetables Other than Potatoes,0.046500,4184.917000,Lowest,Share of product/service in total expenditure (%),2134.943000,%
4,LAO,National,Fresh or Chilled Vegetables Other than Potatoes,0.061300,8258.770000,Lowest,Share of product/service in total expenditure (%),4268.571000,%
5,IDN,National,Fresh or Chilled Vegetables Other than Potatoes,0.050700,9090.433000,Lowest,Share of product/service in total expenditure (%),5467.129000,%
6,VNM,National,Fresh or Chilled Vegetables Other than Potatoes,0.024700,18612.917000,Lowest,Share of product/service in total expenditure (%),8847.418000,%
37,LVA,National,Fresh or Chilled Vegetables Other than Potatoes,0.035700,0.530000,Lowest,Share of product/service in total expenditure (%),0.418000,%
38,MNE,National,Fresh or Chilled Vegetables Other than Potatoes,0.072400,0.755000,Lowest,Share of product/service in total expenditure (%),0.484000,%
39,AZE,National,Fresh or Chilled Vegetables Other than Potatoes,0.069700,0.803000,Lowest,Share of product/service in total expenditure (%),0.517000,%
40,BGR,National,Fresh or Chilled Vegetables Other than Potatoes,0.053400,1.477000,Lowest,Share of product/service in total expenditure (%),0.811000,%
41,BIH,National,Fresh or Chilled Vegetables Other than Potatoes,0.018700,1.477000,Lowest,Share of product/service in total expenditure (%),0.901000,%
42,TUR,National,Fresh or Chilled Vegetables Other than Potatoes,0.062700,1.503000,Lowest,Share of product/service in total expenditure (%),1.162000,%
43,LTU,National,Fresh or Chilled Vegetables Other than Potatoes,0.035300,2.606000,Lowest,Share of product/service in total expenditure (%),1.834000,%
44,ROU,National,Fresh or Chilled Vegetables Other than Potatoes,0.067800,3.178000,Lowest,Share of product/service in total expenditure (%),2.021000,%
45,TJK,National,Fresh or Chilled Vegetables Other than Potatoes,0.060800,4.379000,Lowest,Share of product/service in total expenditure (%),1.410000,%
46,UKR,National,Fresh or Chilled Vegetables Other than Potatoes,0.062400,7.936000,Lowest,Share of product/service in total expenditure (%),2.990000,%
47,MDA,National,Fresh or Chilled Vegetables Other than Potatoes,0.034000,12.369000,Lowest,Share of product/service in total expenditure (%),6.632000,%
48,RUS,National,Fresh or Chilled Vegetables Other than Potatoes,0.059200,30.368000,Lowest,Share of product/service in total expenditure (%),17.411000,%
49,KGZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.055300,45.964000,Lowest,Share of product/service in total expenditure (%),19.458000,%
50,MKD,National,Fresh or Chilled Vegetables Other than Potatoes,0.077400,46.485000,Lowest,Share of product/service in total expenditure (%),22.320000,%
51,SRB,National,Fresh or Chilled Vegetables Other than Potatoes,0.069900,77.728933,Lowest,Share of product/service in total expenditure (%),44.773690,%
52,ALB,National,Fresh or Chilled Vegetables Other than Potatoes,0.084300,103.936000,Lowest,Share of product/service in total expenditure (%),57.851000,%
53,KAZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.036200,147.355000,Lowest,Share of product/service in total expenditure (%),94.239000,%
54,ARM,National,Fresh or Chilled Vegetables Other than Potatoes,0.074800,373.660000,Lowest,Share of product/service in total expenditure (%),230.056000,%
55,BLR,National,Fresh or Chilled Vegetables Other than Potatoes,0.008420,2978.510000,Lowest,Share of product/service in total expenditure (%),1103.222000,%
78,LVA,National,Fresh or Chilled Vegetables Other than Potatoes,0.011400,0.530000,Higher,Share of product/service in total expenditure (%),0.418000,%
79,MNE,National,Fresh or Chilled Vegetables Other than Potatoes,0.016200,0.755000,Higher,Share of product/service in total expenditure (%),0.484000,%
80,AZE,National,Fresh or Chilled Vegetables Other than Potatoes,0.019000,0.803000,Higher,Share of product/service in total expenditure (%),0.517000,%
81,BGR,National,Fresh or Chilled Vegetables Other than Potatoes,0.012900,1.477000,Higher,Share of product/service in total expenditure (%),0.811000,%
...,...,...,...,...,...,...,...,...,...
165977,GMB,Urban,Pharmaceuticals Products,0.004790,28.012000,Higher,Share of product/service in total expenditure (%),11.429000,%
165978,MUS,Urban,Pharmaceuticals Products,0.022800,30.784000,Higher,Share of product/service in total expenditure (%),21.785000,%
165979,MOZ,Urban,Pharmaceuticals Products,0.002200,33.960000,Higher,Share of product/service in total expenditure (%),16.373000,%
165980,LBR,Urban,Pharmaceuticals Products,NaN,71.403000,Higher,Share of product/service in total expenditure (%),42.322000,%
165981,KEN,Urban,Pharmaceuticals Products,0.002520,79.233000,Higher,Share of product/service in total expenditure (%),52.716000,%
165982,CPV,Urban,Pharmaceuticals Products,0.006490,83.259000,Higher,Share of product/service in total expenditure (%),84.787000,%
165983,NGA,Urban,Pharmaceuticals Products,0.000000,150.298025,Higher,Share of product/service in total expenditure (%),113.614462,%
165984,MWI,Urban,Pharmaceuticals Products,0.000006,150.487000,Higher,Share of product/service in total expenditure (%),79.412000,%
165985,MRT,Urban,Pharmaceuticals Products,0.006890,275.894000,Higher,Share of product/service in total expenditure (%),149.566000,%
165986,BEN,Urban,Pharmaceuticals Products,NaN,495.277000,Higher,Share of product/service in total expenditure (%),292.319000,%
165987,BFA,Urban,Pharmaceuticals Products,0.007890,495.277000,Higher,Share of product/service in total expenditure (%),249.766000,%
165988,CIV,Urban,Pharmaceuticals Products,0.015600,495.277000,Higher,Share of product/service in total expenditure (%),332.673000,%
165989,CMR,Urban,Pharmaceuticals Products,0.013400,495.277000,Higher,Share of product/service in total expenditure (%),307.585000,%
165990,COG,Urban,Pharmaceuticals Products,0.004270,495.277000,Higher,Share of product/service in total expenditure (%),436.561000,%
165991,GAB,Urban,Pharmaceuticals Products,0.008200,495.277000,Higher,Share of product/service in total expenditure (%),447.817000,%
165992,MLI,Urban,Pharmaceuticals Products,0.016700,495.277000,Higher,Share of product/service in total expenditure (%),301.384000,%
165993,NER,Urban,Pharmaceuticals Products,0.000293,495.277000,Higher,Share of product/service in total expenditure (%),280.465000,%
165994,TGO,Urban,Pharmaceuticals Products,NaN,495.277000,Higher,Share of product/service in total expenditure (%),294.397000,%
165995,SEN,Urban,Pharmaceuticals Products,NaN,495.277022,Higher,Share of product/service in total expenditure (%),305.950234,%
166034,TLS,Urban,Pharmaceuticals Products,0.000000,1.000000,All,Share of product/service in total expenditure (%),0.590000,%
166035,FJI,Urban,Pharmaceuticals Products,0.010100,1.918000,All,Share of product/service in total expenditure (%),1.756000,%
166036,PNG,Urban,Pharmaceuticals Products,0.004480,2.719000,All,Share of product/service in total expenditure (%),1.960000,%
166037,CHN,Urban,Pharmaceuticals Products,0.049500,6.770000,All,Share of product/service in total expenditure (%),4.225000,%
166038,THA,Urban,Pharmaceuticals Products,0.005130,31.686000,All,Share of product/service in total expenditure (%),18.073000,%
166039,PHL,Urban,Pharmaceuticals Products,0.007530,45.109664,All,Share of product/service in total expenditure (%),27.525623,%
166040,MNG,Urban,Pharmaceuticals Products,0.006550,1357.064000,All,Share of product/service in total expenditure (%),785.100000,%
166041,KHM,Urban,Pharmaceuticals Products,0.017200,4184.917000,All,Share of product/service in total expenditure (%),2134.943000,%
166042,LAO,Urban,Pharmaceuticals Products,0.008980,8258.770000,All,Share of product/service in total expenditure (%),4268.571000,%
166043,IDN,Urban,Pharmaceuticals Products,0.003930,9090.433000,All,Share of product/service in total expenditure (%),5467.129000,%
166044,VNM,Urban,Pharmaceuticals Products,0.017100,18612.917000,All,Share of product/service in total expenditure (%),8847.418000,%

In [34]:
dic = {}
for index, row in csp.iterrows():
    area = row["area"]
    consumption_segment = row["consumption_segment"]
    product = row["product"]
    country_code = row["country_code"]
    value = row["value"]
    i_index = str(area)+","+str(consumption_segment)+","+str(product)
    if not country_code in dic.keys():
        dic[country_code] = {}
    dic[country_code][i_index] = value

In [56]:
con = pd.DataFrame.from_dict(dic)
np.savetxt("../Data/Consumption/consumption_all_feature.txt",con)
with open("../Data/Consumption/consumption_country.txt", 'w') as f:
    for item in con.columns.values:
        f.write("%s\n" % item)
with open("../Data/Consumption/consumption_feature.txt", 'w') as f:
    for item in con.index.values:
        f.write("%s\n" % item)

In [57]:
con.index

Index(['National,All,Beef and Veal', 'National,All,Beer', 'National,All,Bread',
       'National,All,Butter and Margarine', 'National,All,Cheese',
       'National,All,Clothing Material, Other Articles of Clothing and Clothing Accessories',
       'National,All,Coffee, Tea and Cocoa', 'National,All,Dental Services',
       'National,All,Education', 'National,All,Eggs and Egg-Based Products',
       ...
       'Urban,Middle,Preserved Milk and Other Milk Products',
       'Urban,Middle,Preserved or Processed Fish and Seafood',
       'Urban,Middle,Rice', 'Urban,Middle,Shoes and Other Footwear',
       'Urban,Middle,Spirits', 'Urban,Middle,Sugar',
       'Urban,Middle,Therapeutic Appliances and Equipment',
       'Urban,Middle,Tobacco', 'Urban,Middle,Water Utility ',
       'Urban,Middle,Wine'],
      dtype='object', length=615)

In [95]:
df = pd.DataFrame(columns=['A'])
for i in range(5):
        df = df.append({'A': i}, ignore_index=True)

In [18]:
dic = {}
dic["a"] = 1

KeyError: ('a', 'b')