In [1]:
# This notebook mines the structure of "total" figures in consumption data

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.fftpack import fft

data_dir = "../Datasets/consumption.csv"
csp = pd.read_csv(data_dir)

In [2]:
csp = csp[csp["area"]=="National"]

In [3]:
csp = csp[csp["consumption_segment"]=="All"]

In [4]:
csp = csp[csp["indicator"]=="Annual household expenditure by product/service"]

In [5]:
ppp = csp["ppp_conversion_factor"]

In [6]:
data_dir = "../Datasets/health_indicators.csv"
health = pd.read_csv(data_dir)

In [7]:
health = health[health["year"]==2010];

In [8]:
health[["country_code","Population, total"]];

In [9]:
#csp = csp.head(200)

In [10]:
csp.groupby('country_code')
csp['buy']=0
for index, row in csp.iterrows():
    cc = row["country_code"]
    prod = row["product"]
    pp = health[health["country_code"]==cc]["Population, total"]
    print(pp)
    a = row['value']/(row['ppp_conversion_factor']*pp.values[0])
    csp.loc[(csp["country_code"]==cc) & (csp["product"]==prod), 'buy'] = a
    print(a)

4353    24512104.0
Name: Population, total, dtype: float64
65.52843597255105
5921    2040551.0
Name: Population, total, dtype: float64
52.773281548432685
7097    2173170.0
Name: Population, total, dtype: float64
28.979427281464176
3912    1202843.0
Name: Population, total, dtype: float64
10.47323894083921
8959    51584663.0
Name: Population, total, dtype: float64
25.044463182461623
3961    87702670.0
Name: Population, total, dtype: float64
68.76728897402268
4255    1692149.0
Name: Population, total, dtype: float64
40.61382851814513
6656    1250400.0
Name: Population, total, dtype: float64
94.37053055576726
6999    24221405.0
Name: Population, total, dtype: float64
54.64837428532643
5970    3948125.0
Name: Population, total, dtype: float64
37.16495386759361
5480    41350152.0
Name: Population, total, dtype: float64
69.40955804651301
2442    502384.0
Name: Population, total, dtype: float64
78.90915201321337
7440    158578261.0
Name: Population, total, dtype: float64
47.12629039838067
6313    15167095.0
Name: Population, total, dtype: float64
67.37361382221258
6607    3609543.0
Name: Population, total, dtype: float64
25.971888121354805
1903    9199259.0
Name: Population, total, dtype: float64
31.718778644899892
2344    15605217.0
Name: Population, total, dtype: float64
14.852580885730525
3128    20401331.0
Name: Population, total, dtype: float64
74.25075774713767
2540    19970495.0
Name: Population, total, dtype: float64
44.85815558531094
3030    4386693.0
Name: Population, total, dtype: float64
68.2346378111663
4206    1640210.0
Name: Population, total, dtype: float64
63.95453993518785
6460    15075085.0
Name: Population, total, dtype: float64
18.102002586588917
7391    16425578.0
Name: Population, total, dtype: float64
7.841541980909469
9694    6502952.0
Name: Population, total, dtype: float64
51.13324201284439
8469    12916229.0
Name: Population, total, dtype: float64
13.737411333121731
2736    11887202.0
Name: Population, total, dtype: float64
10.848748288832464
8273    10246842.0
Name: Population, total, dtype: float64
14.065750184630277
2981    64523263.0
Name: Population, total, dtype: float64
19.441219867423015
5823    2097555.0
Name: Population, total, dtype: float64
98.53199978252191
6901    619428.0
Name: Population, total, dtype: float64
138.7033887488948
1511    9054332.0
Name: Population, total, dtype: float64
122.59153783468972
2295    7395599.0
Name: Population, total, dtype: float64
118.2412724114615
2099    3722084.0
Name: Population, total, dtype: float64
149.35999562194354
874    72326914.0
Name: Population, total, dtype: float64
133.16164710523708
6117    3097282.0
Name: Population, total, dtype: float64
99.50642602570274
8224    20246871.0
Name: Population, total, dtype: float64
152.22519886525043
9498    7641630.0
Name: Population, total, dtype: float64
102.182743993862
10086    45870700.0
Name: Population, total, dtype: float64
169.93883177210205
6754    3562045.0
Name: Population, total, dtype: float64
78.67526829376303
678    142849449.0
Name: Population, total, dtype: float64
179.91747673760545
5725    5447900.0
Name: Population, total, dtype: float64
81.25231493513121
7489    2070739.0
Name: Population, total, dtype: float64
229.57236038156313
8518    7291436.0
Name: Population, total, dtype: float64
225.468412891899
1070    2913021.0
Name: Population, total, dtype: float64
267.0574506929355
5431    16321872.0
Name: Population, total, dtype: float64
99.2199387173168
1364    2877311.0
Name: Population, total, dtype: float64
91.7271069122039
1756    9490583.0
Name: Population, total, dtype: float64
90.93646947061215
6411    364511.0
Name: Population, total, dtype: float64
12.516923148243674
2001    727641.0
Name: Population, total, dtype: float64
61.92098658738341
335    1.230981e+09
Name: Population, total, dtype: float64
30.04246959097426
1021    28803167.0
Name: Population, total, dtype: float64
53.21572428484539
1658    152149102.0
Name: Population, total, dtype: float64
28.4842453942071
7195    27023137.0
Name: Population, total, dtype: float64
72.74557793439202
7685    170560182.0
Name: Population, total, dtype: float64
34.82592269268865
9057    20198353.0
Name: Population, total, dtype: float64
115.26210599218047
3716    6164626.0
Name: Population, total, dtype: float64
45.57697259434884
139    196796269.0
Name: Population, total, dtype: float64
48.793547075977095
7930    29373646.0
Name: Population, total, dtype: float64
81.86983152879527
2050    9918242.0
Name: Population, total, dtype: float64
83.78812159970178
4647    14630417.0
Name: Population, total, dtype: float64
84.05893417051534
580    117318941.0
Name: Population, total, dtype: float64
60.03872170347918
4892    8194778.0
Name: Population, total, dtype: float64
74.58542582294076
7342    5737723.0
Name: Population, total, dtype: float64
33.35419682589359
5333    2817210.0
Name: Population, total, dtype: float64
57.93182157816868
2883    45918097.0
Name: Population, total, dtype: float64
84.56244471942131
9645    1109591.0
Name: Population, total, dtype: float64
86.12357943342965
4059    859950.0
Name: Population, total, dtype: float64
49.937132833781064
7832    7108239.0
Name: Population, total, dtype: float64
162.33620893002774
188    1.337705e+09
Name: Population, total, dtype: float64
75.56451482335429
9596    67208808.0
Name: Population, total, dtype: float64
59.211142910119925
7979    93726624.0
Name: Population, total, dtype: float64
19.60291295345186
6852    2712650.0
Name: Population, total, dtype: float64
20.969583444185137
2491    14308740.0
Name: Population, total, dtype: float64
43.94716802769623
5774    6246274.0
Name: Population, total, dtype: float64
50.58133516762031
384    242524123.0
Name: Population, total, dtype: float64
38.522839673697455
10380    88472512.0
Name: Population, total, dtype: float64
23.43020031097125
5382    7182390.0
Name: Population, total, dtype: float64
70.21102359998086
5137    30762701.0
Name: Population, total, dtype: float64
146.8521785362476
3667    84107606.0
Name: Population, total, dtype: float64
67.13719797869071
6950    32409639.0
Name: Population, total, dtype: float64
76.26514220070021
3471    851146.0
Name: Population, total, dtype: float64
151.8246617931188
10527    23606779.0
Name: Population, total, dtype: float64
45.76139844105084
2393    8766930.0
Name: Population, total, dtype: float64
27.855533533875825
9547    46098591.0
Name: Population, total, dtype: float64
27.714809693203023
6264    21151640.0
Name: Population, total, dtype: float64
11.317376802958522
10037    33915133.0
Name: Population, total, dtype: float64
70.35020499389428
8616    6458720.0
Name: Population, total, dtype: float64
80.2579450519091
10576    13850033.0
Name: Population, total, dtype: float64
40.43744236234964
4696    10794170.0
Name: Population, total, dtype: float64
39.581524336036125
8420    174776.0
Name: Population, total, dtype: float64
124.2978606882515
5823    2097555.0
Name: Population, total, dtype: float64
50.90267482649742
6901    619428.0
Name: Population, total, dtype: float64
107.085573469888
1511    9054332.0
Name: Population, total, dtype: float64
13.79387755001942
2295    7395599.0
Name: Population, total, dtype: float64
37.823968094609086
2099    3722084.0
Name: Population, total, dtype: float64
98.41071133087056
874    72326914.0
Name: Population, total, dtype: float64
30.494007379126856
6117    3097282.0
Name: Population, total, dtype: float64
57.95261605092377
8224    20246871.0
Name: Population, total, dtype: float64
98.41154952019608
9498    7641630.0
Name: Population, total, dtype: float64
30.597835644270432
10086    45870700.0
Name: Population, total, dtype: float64
103.41836173167076
6754    3562045.0
Name: Population, total, dtype: float64
24.0435447797594
678    142849449.0
Name: Population, total, dtype: float64
92.04777215467438
5725    5447900.0
Name: Population, total, dtype: float64
55.17095727822251
7489    2070739.0
Name: Population, total, dtype: float64
125.91559483358719
8518    7291436.0
Name: Population, total, dtype: float64
82.77694375360109
1070    2913021.0
Name: Population, total, dtype: float64
99.26650484727428
5431    16321872.0
Name: Population, total, dtype: float64
66.87013204379063
1364    2877311.0
Name: Population, total, dtype: float64
6.851331113787374
1756    9490583.0
Name: Population, total, dtype: float64
72.57436387365371
4353    24512104.0
Name: Population, total, dtype: float64
0.5389061958380299
5921    2040551.0
Name: Population, total, dtype: float64
6.698779070428481
7097    2173170.0
Name: Population, total, dtype: float64

8.206626290978846
3912    1202843.0
Name: Population, total, dtype: float64
5.119904381938094
8959    51584663.0
Name: Population, total, dtype: float64
20.03705152563524
3961    87702670.0
Name: Population, total, dtype: float64
13.553332919515451
4255    1692149.0
Name: Population, total, dtype: float64
4.133062063605853
6656    1250400.0
Name: Population, total, dtype: float64
3.2257999548017025
6999    24221405.0
Name: Population, total, dtype: float64
0.11958934077999703
5970    3948125.0
Name: Population, total, dtype: float64
3.024063427963952
5480    41350152.0
Name: Population, total, dtype: float64
40.39094853833135
2442    502384.0
Name: Population, total, dtype: float64
3.840234017451163
7440    158578261.0
Name: Population, total, dtype: float64
0.6100681290780084
6313    15167095.0
Name: Population, total, dtype: float64
3.6620888556347237
6607    3609543.0
Name: Population, total, dtype: float64
33.11022058282911
1903    9199259.0
Name: Population, total, dtype: float64
6.625212032521534
2344    15605217.0
Name: Population, total, dtype: float64
1.4961996870316387
3128    20401331.0
Name: Population, total, dtype: float64
1.4933439725807105
2540    19970495.0
Name: Population, total, dtype: float64
1.4620578643378759
3030    4386693.0
Name: Population, total, dtype: float64
0.38275930204649794
4206    1640210.0
Name: Population, total, dtype: float64
1.7015485401945396
6460    15075085.0
Name: Population, total, dtype: float64
6.292881501416887
7391    16425578.0
Name: Population, total, dtype: float64
9.031276991490161
9694    6502952.0
Name: Population, total, dtype: float64
0.3846967559289172
8469    12916229.0
Name: Population, total, dtype: float64
11.021352969196496
2736    11887202.0
Name: Population, total, dtype: float64
3.894467490736351
8273    10246842.0
Name: Population, total, dtype: float64
4.38742611300469
2981    64523263.0
Name: Population, total, dtype: float64
0.05963605432528933
2393    8766930.0
Name: Population, total, dtype: float64
0.8973856850241624
9547    46098591.0
Name: Population, total, dtype: float64
5.733225821629496
6264    21151640.0
Name: Population, total, dtype: float64
1.2191074012147274
10037    33915133.0
Name: Population, total, dtype: float64
14.356282812484416
8616    6458720.0
Name: Population, total, dtype: float64
0.43348920432252774
10576    13850033.0
Name: Population, total, dtype: float64
4.236692064237297
4696    10794170.0
Name: Population, total, dtype: float64
1.186377963171866
8420    174776.0
Name: Population, total, dtype: float64
52.66376814676148
3716    6164626.0
Name: Population, total, dtype: float64
36.89943883051462
139    196796269.0
Name: Population, total, dtype: float64
0.0898375397262061
7930    29373646.0
Name: Population, total, dtype: float64
15.440930386817996
2050    9918242.0
Name: Population, total, dtype: float64
36.23342220693429
4647    14630417.0
Name: Population, total, dtype: float64
15.206644935299025
580    117318941.0
Name: Population, total, dtype: float64
17.025015482804083
4892    8194778.0
Name: Population, total, dtype: float64
29.906107979717575
7342    5737723.0
Name: Population, total, dtype: float64
10.848906233273793
5333    2817210.0
Name: Population, total, dtype: float64
8.000310681895341
2883    45918097.0
Name: Population, total, dtype: float64
26.391834374672033
9645    1109591.0
Name: Population, total, dtype: float64
0.3908660144723658
4059    859950.0
Name: Population, total, dtype: float64
11.286792472571847
7832    7108239.0
Name: Population, total, dtype: float64
0.06324422653079341
188    1.337705e+09
Name: Population, total, dtype: float64
23.244868030955338
9596    67208808.0
Name: Population, total, dtype: float64
24.150210168549492
7979    93726624.0
Name: Population, total, dtype: float64
0.7443046340164057
6852    2712650.0
Name: Population, total, dtype: float64
58.64260095621898
2491    14308740.0
Name: Population, total, dtype: float64
4.459493609671137
5774    6246274.0
Name: Population, total, dtype: float64
0.8770368265617359
384    242524123.0
Name: Population, total, dtype: float64
0.15053508551536282
10380    88472512.0
Name: Population, total, dtype: float64
4.2746826217526666
5382    7182390.0
Name: Population, total, dtype: float64
6.008085993969414
5137    30762701.0
Name: Population, total, dtype: float64
5.040345438874228
3667    84107606.0
Name: Population, total, dtype: float64
28.23067480025868
6950    32409639.0
Name: Population, total, dtype: float64
9.693237049704729
3471    851146.0
Name: Population, total, dtype: float64
26.92579887195843
10527    23606779.0
Name: Population, total, dtype: float64
31.453247765287568
6411    364511.0
Name: Population, total, dtype: float64
0.0
2001    727641.0
Name: Population, total, dtype: float64
9.823724548550615
335    1.230981e+09
Name: Population, total, dtype: float64
58.12351026224842
1021    28803167.0
Name: Population, total, dtype: float64
24.76646426111607
1658    152149102.0
Name: Population, total, dtype: float64
12.012821180992624
7195    27023137.0
Name: Population, total, dtype: float64
35.04566946647028
7685    170560182.0
Name: Population, total, dtype: float64
108.43315435757285
9057    20198353.0
Name: Population, total, dtype: float64
1.5948851658226384
5823    2097555.0
Name: Population, total, dtype: float64
107.61491973583871
6901    619428.0
Name: Population, total, dtype: float64
114.65613510294249
1511    9054332.0
Name: Population, total, dtype: float64
28.00998689868285
2295    7395599.0
Name: Population, total, dtype: float64
99.48598955047981
2099    3722084.0
Name: Population, total, dtype: float64
44.777988372441875
874    72326914.0
Name: Population, total, dtype: float64
46.99894014647722
6117    3097282.0
Name: Population, total, dtype: float64
26.20372137840288
8224    20246871.0
Name: Population, total, dtype: float64
33.39995366155537
9498    7641630.0
Name: Population, total, dtype: float64
21.721072115773307
10086    45870700.0
Name: Population, total, dtype: float64
10.487092433797828
6754    3562045.0
Name: Population, total, dtype: float64
30.881598733501534
678    142849449.0
Name: Population, total, dtype: float64
131.35812796346232
5725    5447900.0
Name: Population, total, dtype: float64
37.20545351314536
7489    2070739.0
Name: Population, total, dtype: float64
9.909720012844408
8518    7291436.0
Name: Population, total, dtype: float64
130.748719809368
1070    2913021.0
Name: Population, total, dtype: float64
18.82276309763356
5431    16321872.0
Name: Population, total, dtype: float64
63.684230043396745
1364    2877311.0
Name: Population, total, dtype: float64
32.33452602810546
9645    1109591.0
Name: Population, total, dtype: float64
24.208589868409142
4059    859950.0
Name: Population, total, dtype: float64
88.73030547810893
7832    7108239.0
Name: Population, total, dtype: float64
67.6616930877317
188    1.337705e+09
Name: Population, total, dtype: float64
163.49499975771008
9596    67208808.0
Name: Population, total, dtype: float64
4.4853951587153125
7979    93726624.0
Name: Population, total, dtype: float64
44.997787622029016
6852    2712650.0
Name: Population, total, dtype: float64
38.047318945537775
2491    14308740.0
Name: Population, total, dtype: float64
23.272963754622975
5774    6246274.0
Name: Population, total, dtype: float64
14.786203268916868
384    242524123.0
Name: Population, total, dtype: float64
29.222653985690986
10380    88472512.0
Name: Population, total, dtype: float64
49.6988651339393
4353    24512104.0
Name: Population, total, dtype: float64
112.31319455139861
5921    2040551.0
Name: Population, total, dtype: float64
38.12830314886641
7097    2173170.0
Name: Population, total, dtype: float64
46.493578768513004
3912    1202843.0
Name: Population, total, dtype: float64
50.075273910750795
8959    51584663.0
Name: Population, total, dtype: float64
110.05573980548608
3961    87702670.0
Name: Population, total, dtype: float64
9.81768466277899
4255    1692149.0
Name: Population, total, dtype: float64
14.228791932565336
6656    1250400.0
Name: Population, total, dtype: float64
68.52087131980056
6999    24221405.0
Name: Population, total, dtype: float64
1.4924186301479927
5970    3948125.0
Name: Population, total, dtype: float64
21.279753746047188
5480    41350152.0
Name: Population, total, dtype: float64
0.0
2442    502384.0
Name: Population, total, dtype: float64
28.90448802327587
7440    158578261.0
Name: Population, total, dtype: float64
12.385264816011873
6313    15167095.0
Name: Population, total, dtype: float64
7.381218990013214
6607    3609543.0
Name: Population, total, dtype: float64
10.096565901607667
1903    9199259.0
Name: Population, total, dtype: float64

15.306351125901386
2344    15605217.0
Name: Population, total, dtype: float64
10.512489867055885
3128    20401331.0
Name: Population, total, dtype: float64
20.846946761398762
2540    19970495.0
Name: Population, total, dtype: float64
26.315906403919602
3030    4386693.0
Name: Population, total, dtype: float64
26.51634297176366
4206    1640210.0
Name: Population, total, dtype: float64
40.21413857869951
6460    15075085.0
Name: Population, total, dtype: float64
3.641049515978509
7391    16425578.0
Name: Population, total, dtype: float64
4.022230604940187
9694    6502952.0
Name: Population, total, dtype: float64
10.635634542701451
8469    12916229.0
Name: Population, total, dtype: float64
0.8308823895910895
2736    11887202.0
Name: Population, total, dtype: float64
2.5840829344063896
8273    10246842.0
Name: Population, total, dtype: float64
13.750811625715956
2981    64523263.0
Name: Population, total, dtype: float64
7.648110362150554
2393    8766930.0
Name: Population, total, dtype: float64
2.4063076682138895
9547    46098591.0
Name: Population, total, dtype: float64
10.419255217322913
6264    21151640.0
Name: Population, total, dtype: float64
5.820165739785324
10037    33915133.0
Name: Population, total, dtype: float64
48.12782052595183
8616    6458720.0
Name: Population, total, dtype: float64
27.33949716759965
10576    13850033.0
Name: Population, total, dtype: float64
16.374223135719735
4696    10794170.0
Name: Population, total, dtype: float64
7.262152069817638
8420    174776.0
Name: Population, total, dtype: float64
23.019791729628814
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
147.11603866012297
7930    29373646.0
Name: Population, total, dtype: float64
63.20854916770783
2050    9918242.0
Name: Population, total, dtype: float64
98.53114878988038
4647    14630417.0
Name: Population, total, dtype: float64
66.57336494411362
580    117318941.0
Name: Population, total, dtype: float64
215.74725310709584
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
16.226773342367693
5333    2817210.0
Name: Population, total, dtype: float64
119.37362478958948
2883    45918097.0
Name: Population, total, dtype: float64
57.76834657508791
5382    7182390.0
Name: Population, total, dtype: float64
149.11325810234757
5137    30762701.0
Name: Population, total, dtype: float64
20.954508375804558
3667    84107606.0
Name: Population, total, dtype: float64
45.683369270334914
6950    32409639.0
Name: Population, total, dtype: float64
35.900558947849945
3471    851146.0
Name: Population, total, dtype: float64
9.254189117386256
10527    23606779.0
Name: Population, total, dtype: float64
41.759564302413494
1756    9490583.0
Name: Population, total, dtype: float64
98.09279853509382
6411    364511.0
Name: Population, total, dtype: float64
37.41012131301115
2001    727641.0
Name: Population, total, dtype: float64
20.149686267656488
335    1.230981e+09
Name: Population, total, dtype: float64
29.353888643782348
1021    28803167.0
Name: Population, total, dtype: float64
2.098854531805076
1658    152149102.0
Name: Population, total, dtype: float64
30.654318575236704
7195    27023137.0
Name: Population, total, dtype: float64
34.985074723298176
7685    170560182.0
Name: Population, total, dtype: float64
19.913562351773034
9057    20198353.0
Name: Population, total, dtype: float64
39.11166318051932
4353    24512104.0
Name: Population, total, dtype: float64
2.0918241621965312
5921    2040551.0
Name: Population, total, dtype: float64
3.9212705166224016
7097    2173170.0
Name: Population, total, dtype: float64
1.8264756660801724
3912    1202843.0
Name: Population, total, dtype: float64
1.5121465664273437
8959    51584663.0
Name: Population, total, dtype: float64
3.880902028262734
3961    87702670.0
Name: Population, total, dtype: float64
0.021421097000511903
4255    1692149.0
Name: Population, total, dtype: float64
0.20709023283712594
6656    1250400.0
Name: Population, total, dtype: float64
4.336295246205172
6999    24221405.0
Name: Population, total, dtype: float64
1.4257253392428366
5970    3948125.0
Name: Population, total, dtype: float64
1.555829904052348
5480    41350152.0
Name: Population, total, dtype: float64
0.5071553156365605
2442    502384.0
Name: Population, total, dtype: float64
15.132471633533829
7440    158578261.0
Name: Population, total, dtype: float64
0.3079770414078973
6313    15167095.0
Name: Population, total, dtype: float64
3.8230534900540922
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
0.4987737226200116
2344    15605217.0
Name: Population, total, dtype: float64
0.5201163176526202
3128    20401331.0
Name: Population, total, dtype: float64
6.798129295831588
2540    19970495.0
Name: Population, total, dtype: float64
1.4915976113884901
3030    4386693.0
Name: Population, total, dtype: float64
5.670506966435565
4206    1640210.0
Name: Population, total, dtype: float64
12.498471750375268
6460    15075085.0
Name: Population, total, dtype: float64
0.09118583799827543
7391    16425578.0
Name: Population, total, dtype: float64
0.0
9694    6502952.0
Name: Population, total, dtype: float64
1.0921643550959692
8469    12916229.0
Name: Population, total, dtype: float64
1.59307632140632
2736    11887202.0
Name: Population, total, dtype: float64
0.22236149066051322
8273    10246842.0
Name: Population, total, dtype: float64
0.44460838392686347
2981    64523263.0
Name: Population, total, dtype: float64
1.5948481282731115
2393    8766930.0
Name: Population, total, dtype: float64
0.19373236078822176
9547    46098591.0
Name: Population, total, dtype: float64
1.7335816612619248
6264    21151640.0
Name: Population, total, dtype: float64
3.566300915195921
10037    33915133.0
Name: Population, total, dtype: float64
3.8065487685189527
8616    6458720.0
Name: Population, total, dtype: float64
0.7391545013126241
10576    13850033.0
Name: Population, total, dtype: float64
2.057547272155032
4696    10794170.0
Name: Population, total, dtype: float64
2.25452694925583
8420    174776.0
Name: Population, total, dtype: float64
92.4725045030456
9645    1109591.0
Name: Population, total, dtype: float64
10.32531883446014
4059    859950.0
Name: Population, total, dtype: float64
1.829635949195012
7832    7108239.0
Name: Population, total, dtype: float64
95.59951738498704
188    1.337705e+09
Name: Population, total, dtype: float64
70.23444679573417
9596    67208808.0
Name: Population, total, dtype: float64
40.937230438256705
7979    93726624.0
Name: Population, total, dtype: float64
29.906852437963643
6852    2712650.0
Name: Population, total, dtype: float64
0.5376733025425868
2491    14308740.0
Name: Population, total, dtype: float64
25.920569068380725
5774    6246274.0
Name: Population, total, dtype: float64
33.92302845854996
384    242524123.0
Name: Population, total, dtype: float64
1.0664332282727262
10380    88472512.0
Name: Population, total, dtype: float64
76.90253870680637
5823    2097555.0
Name: Population, total, dtype: float64
103.36961442200437
6901    619428.0
Name: Population, total, dtype: float64
167.33229385793783
1511    9054332.0
Name: Population, total, dtype: float64
6.172194951881165
2295    7395599.0
Name: Population, total, dtype: float64
73.70586787989494
2099    3722084.0
Name: Population, total, dtype: float64
28.878627049409666
874    72326914.0
Name: Population, total, dtype: float64
0.0
6117    3097282.0
Name: Population, total, dtype: float64
97.16706667252151
8224    20246871.0
Name: Population, total, dtype: float64
97.38274317516597
9498    7641630.0
Name: Population, total, dtype: float64
0.015145157614297194
10086    45870700.0
Name: Population, total, dtype: float64
147.8343320314358
6754    3562045.0
Name: Population, total, dtype: float64
41.881969841360956
678    142849449.0
Name: Population, total, dtype: float64
100.25766612126307
5725    5447900.0
Name: Population, total, dtype: float64
10.566023585426933
7489    2070739.0
Name: Population, total, dtype: float64
88.73366598534011
8518    7291436.0
Name: Population, total, dtype: float64
149.3408668291856
1070    2913021.0
Name: Population, total, dtype: float64
17.501541439840278
5431    16321872.0
Name: Population, total, dtype: float64
43.44531403103345
1364    2877311.0
Name: Population, total, dtype: float64
10.114513136087762
1756    9490583.0
Name: Population, total, dtype: float64
118.279163658198
6411    364511.0
Name: Population, total, dtype: float64
0.0
2001    727641.0
Name: Population, total, dtype: float64
20.00684220559588
335    1.230981e+09
Name: Population, total, dtype: float64
0.34496179308198327
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
0.0
7195    27023137.0
Name: Population, total, dtype: float64
0.0
7685    170560182.0
Name: Population, total, dtype: float64
0.0
9057    20198353.0
Name: Population, total, dtype: float64
0.7101512076667074
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
11.440678947016897
7930    29373646.0
Name: Population, total, dtype: float64
4.215598700503659
2050    9918242.0
Name: Population, total, dtype: float64

10.969880899338028
4647    14630417.0
Name: Population, total, dtype: float64
13.342116874807466
580    117318941.0
Name: Population, total, dtype: float64
32.06783348247243
4892    8194778.0
Name: Population, total, dtype: float64
17.78185166425512
7342    5737723.0
Name: Population, total, dtype: float64
2.2400788161159544
5333    2817210.0
Name: Population, total, dtype: float64
11.223307111246637
2883    45918097.0
Name: Population, total, dtype: float64
29.996351783211587
5382    7182390.0
Name: Population, total, dtype: float64
0.0
5137    30762701.0
Name: Population, total, dtype: float64
0.0
3667    84107606.0
Name: Population, total, dtype: float64
0.04052224023676798
6950    32409639.0
Name: Population, total, dtype: float64
0.00118817965938155
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
0.0
4353    24512104.0
Name: Population, total, dtype: float64
29.655115889213533
5921    2040551.0
Name: Population, total, dtype: float64
20.42422416708449
7097    2173170.0
Name: Population, total, dtype: float64
12.58522255552392
3912    1202843.0
Name: Population, total, dtype: float64
1.276829078151875
8959    51584663.0
Name: Population, total, dtype: float64
10.98773289142723
3961    87702670.0
Name: Population, total, dtype: float64
7.721160517720142
4255    1692149.0
Name: Population, total, dtype: float64
13.574233610061176
6656    1250400.0
Name: Population, total, dtype: float64
23.541422172951478
6999    24221405.0
Name: Population, total, dtype: float64
2.9750891060271183
5970    3948125.0
Name: Population, total, dtype: float64
1.8520466528589994
5480    41350152.0
Name: Population, total, dtype: float64
6.952420972309542
2442    502384.0
Name: Population, total, dtype: float64
7.878410822999188
7440    158578261.0
Name: Population, total, dtype: float64
2.9292101965148536
6313    15167095.0
Name: Population, total, dtype: float64
11.048257961656722
5823    2097555.0
Name: Population, total, dtype: float64
1.003103839319689
6901    619428.0
Name: Population, total, dtype: float64
30.22493193800711
1511    9054332.0
Name: Population, total, dtype: float64
18.004670034043894
2295    7395599.0
Name: Population, total, dtype: float64
27.25485430496029
2099    3722084.0
Name: Population, total, dtype: float64
11.10176443275478
874    72326914.0
Name: Population, total, dtype: float64
60.18378809986202
6117    3097282.0
Name: Population, total, dtype: float64
0.43813570938575563
6607    3609543.0
Name: Population, total, dtype: float64
61.72395589219757
1903    9199259.0
Name: Population, total, dtype: float64
4.073009373157247
2344    15605217.0
Name: Population, total, dtype: float64
3.9659338633995964
3128    20401331.0
Name: Population, total, dtype: float64
5.325415896097274
2540    19970495.0
Name: Population, total, dtype: float64
3.9085348763238708
3030    4386693.0
Name: Population, total, dtype: float64
2.4583306235038185
4206    1640210.0
Name: Population, total, dtype: float64
4.2619836848138775
6460    15075085.0
Name: Population, total, dtype: float64
6.8834637437362725
7391    16425578.0
Name: Population, total, dtype: float64
4.690637646259543
9694    6502952.0
Name: Population, total, dtype: float64
3.097564237823776
8469    12916229.0
Name: Population, total, dtype: float64
7.8892848997683584
2736    11887202.0
Name: Population, total, dtype: float64
7.943568705981656
8273    10246842.0
Name: Population, total, dtype: float64
1.4957240125686504
2981    64523263.0
Name: Population, total, dtype: float64
2.2107118560890773
2393    8766930.0
Name: Population, total, dtype: float64
0.9907605876951859
9547    46098591.0
Name: Population, total, dtype: float64
4.748144937760365
6264    21151640.0
Name: Population, total, dtype: float64
0.5235998798203131
10037    33915133.0
Name: Population, total, dtype: float64
5.086406025142414
8616    6458720.0
Name: Population, total, dtype: float64
1.0814835507633493
10576    13850033.0
Name: Population, total, dtype: float64
2.3243366060380612
4696    10794170.0
Name: Population, total, dtype: float64
2.786790548438819
8420    174776.0
Name: Population, total, dtype: float64
0.0
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
2.590428646326341
7930    29373646.0
Name: Population, total, dtype: float64
7.206699805357618
2050    9918242.0
Name: Population, total, dtype: float64
8.529307558037573
4647    14630417.0
Name: Population, total, dtype: float64
0.0
580    117318941.0
Name: Population, total, dtype: float64
0.24338878485104226
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
0.07721006314356316
5333    2817210.0
Name: Population, total, dtype: float64
9.135672267944607
2883    45918097.0
Name: Population, total, dtype: float64
3.3451139551573754
5382    7182390.0
Name: Population, total, dtype: float64
85.03046798739132
5137    30762701.0
Name: Population, total, dtype: float64
46.052188543001066
3667    84107606.0
Name: Population, total, dtype: float64
2.9795074867897102
6950    32409639.0
Name: Population, total, dtype: float64
68.20365182958203
3471    851146.0
Name: Population, total, dtype: float64
108.06023069828106
10527    23606779.0
Name: Population, total, dtype: float64
51.46035262461776
8224    20246871.0
Name: Population, total, dtype: float64
13.329110938083485
9498    7641630.0
Name: Population, total, dtype: float64
17.98399622010762
10086    45870700.0
Name: Population, total, dtype: float64
1.2653661364396578
6754    3562045.0
Name: Population, total, dtype: float64
2.8666307049351354
678    142849449.0
Name: Population, total, dtype: float64
6.679391708336033
5725    5447900.0
Name: Population, total, dtype: float64
28.433186898871572
7489    2070739.0
Name: Population, total, dtype: float64
11.648175882548715
8518    7291436.0
Name: Population, total, dtype: float64
15.199047725522938
1070    2913021.0
Name: Population, total, dtype: float64
13.612411887816265
5431    16321872.0
Name: Population, total, dtype: float64
56.330647126226424
1364    2877311.0
Name: Population, total, dtype: float64
2.1216640308981622
1756    9490583.0
Name: Population, total, dtype: float64
0.04480683680598874
6411    364511.0
Name: Population, total, dtype: float64
0.6887896436366503
2001    727641.0
Name: Population, total, dtype: float64
2.501467556036901
335    1.230981e+09
Name: Population, total, dtype: float64
4.974450344666859
1021    28803167.0
Name: Population, total, dtype: float64
49.815727013842015
1658    152149102.0
Name: Population, total, dtype: float64
2.044149615580223
7195    27023137.0
Name: Population, total, dtype: float64
26.435996840071365
7685    170560182.0
Name: Population, total, dtype: float64
8.313546975878047
9057    20198353.0
Name: Population, total, dtype: float64
0.9903876944773186
9645    1109591.0
Name: Population, total, dtype: float64
0.7706900293342169
4059    859950.0
Name: Population, total, dtype: float64
28.59789081608151
7832    7108239.0
Name: Population, total, dtype: float64
33.684138058178775
188    1.337705e+09
Name: Population, total, dtype: float64
8.57123570177122
9596    67208808.0
Name: Population, total, dtype: float64
0.05749610710573759
7979    93726624.0
Name: Population, total, dtype: float64
0.0
6852    2712650.0
Name: Population, total, dtype: float64
126.31310416286199
2491    14308740.0
Name: Population, total, dtype: float64
11.082207544709073
5774    6246274.0
Name: Population, total, dtype: float64
0.4618832426065381
384    242524123.0
Name: Population, total, dtype: float64
0.18957214504372794
10380    88472512.0
Name: Population, total, dtype: float64
0.0
9645    1109591.0
Name: Population, total, dtype: float64
0.017936567832010298
4059    859950.0
Name: Population, total, dtype: float64
2.071661828487406
7832    7108239.0
Name: Population, total, dtype: float64
0.0
188    1.337705e+09
Name: Population, total, dtype: float64
2.3709139805790755
9596    67208808.0
Name: Population, total, dtype: float64
0.3168005176600784
7979    93726624.0
Name: Population, total, dtype: float64
0.004588896736187326
6852    2712650.0
Name: Population, total, dtype: float64
0.7338616059537338
2491    14308740.0
Name: Population, total, dtype: float64
3.675837203828752
5774    6246274.0
Name: Population, total, dtype: float64
0.370367075241695
384    242524123.0
Name: Population, total, dtype: float64
2.059248534539758
10380    88472512.0
Name: Population, total, dtype: float64
0.85795506878154
3716    6164626.0
Name: Population, total, dtype: float64
1.1349315855793622
139    196796269.0
Name: Population, total, dtype: float64
0.22429944696698215
7930    29373646.0
Name: Population, total, dtype: float64
19.61265922288596
2050    9918242.0
Name: Population, total, dtype: float64

1.0956493217808536
4647    14630417.0
Name: Population, total, dtype: float64
20.86915636879652
580    117318941.0
Name: Population, total, dtype: float64
0.01070064341340213
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
3.9684356297288073
5333    2817210.0
Name: Population, total, dtype: float64
5.117648564568265
2883    45918097.0
Name: Population, total, dtype: float64
31.139593303439348
5382    7182390.0
Name: Population, total, dtype: float64
2.912402809676009
5137    30762701.0
Name: Population, total, dtype: float64
6.802642982678589
3667    84107606.0
Name: Population, total, dtype: float64
13.817940501221296
6950    32409639.0
Name: Population, total, dtype: float64
16.886061041705474
3471    851146.0
Name: Population, total, dtype: float64
0.9460946727097422
10527    23606779.0
Name: Population, total, dtype: float64
0.7500194886762439
4353    24512104.0
Name: Population, total, dtype: float64
3.5875016320247055
5921    2040551.0
Name: Population, total, dtype: float64
0.0
7097    2173170.0
Name: Population, total, dtype: float64
1.8385777650678055
3912    1202843.0
Name: Population, total, dtype: float64
0.2581345573791271
8959    51584663.0
Name: Population, total, dtype: float64
1.55123309287187
3961    87702670.0
Name: Population, total, dtype: float64
1.137145136201486
4255    1692149.0
Name: Population, total, dtype: float64
1.0847169632507692
6656    1250400.0
Name: Population, total, dtype: float64
1.6697796241580936
6999    24221405.0
Name: Population, total, dtype: float64
1.3623150584206496
5970    3948125.0
Name: Population, total, dtype: float64
1.029111523878044
5480    41350152.0
Name: Population, total, dtype: float64
1.5023348452304333
2442    502384.0
Name: Population, total, dtype: float64
4.086764282543173
7440    158578261.0
Name: Population, total, dtype: float64
1.4280697123084254
6313    15167095.0
Name: Population, total, dtype: float64
0.06453723129996232
6607    3609543.0
Name: Population, total, dtype: float64
5.3357993889028625
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
1.1635491582802344
3128    20401331.0
Name: Population, total, dtype: float64
6.876276955930421
2540    19970495.0
Name: Population, total, dtype: float64
3.140303158295364
3030    4386693.0
Name: Population, total, dtype: float64
2.5879866237983182
4206    1640210.0
Name: Population, total, dtype: float64
2.290047117697411
6460    15075085.0
Name: Population, total, dtype: float64
0.266997356486804
7391    16425578.0
Name: Population, total, dtype: float64
2.6991324300143327
9694    6502952.0
Name: Population, total, dtype: float64
2.2066988514043566
8469    12916229.0
Name: Population, total, dtype: float64
2.402948113591397
2736    11887202.0
Name: Population, total, dtype: float64
2.2312512894175835
8273    10246842.0
Name: Population, total, dtype: float64
0.0
2981    64523263.0
Name: Population, total, dtype: float64
0.21559244488708348
2393    8766930.0
Name: Population, total, dtype: float64
1.0583418879679356
9547    46098591.0
Name: Population, total, dtype: float64
1.3108824223195426
6264    21151640.0
Name: Population, total, dtype: float64
0.14266100993526698
10037    33915133.0
Name: Population, total, dtype: float64
1.8992102458362867
8616    6458720.0
Name: Population, total, dtype: float64
1.3298279822858452
10576    13850033.0
Name: Population, total, dtype: float64
0.08852788897750662
4696    10794170.0
Name: Population, total, dtype: float64
1.565311727258468
8420    174776.0
Name: Population, total, dtype: float64
11.711943928575892
5823    2097555.0
Name: Population, total, dtype: float64
12.51025817835596
6901    619428.0
Name: Population, total, dtype: float64
6.910773356378855
1511    9054332.0
Name: Population, total, dtype: float64
0.1817219757990176
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
18.077411795469263
874    72326914.0
Name: Population, total, dtype: float64
6.35761613354094
6117    3097282.0
Name: Population, total, dtype: float64
4.41109308223334
8224    20246871.0
Name: Population, total, dtype: float64
4.373106460013785
9498    7641630.0
Name: Population, total, dtype: float64
5.822809228913631
10086    45870700.0
Name: Population, total, dtype: float64
7.140545187970669
6754    3562045.0
Name: Population, total, dtype: float64
4.309960322683059
678    142849449.0
Name: Population, total, dtype: float64
12.865070776592267
5725    5447900.0
Name: Population, total, dtype: float64
0.6746806945998637
7489    2070739.0
Name: Population, total, dtype: float64
0.0
8518    7291436.0
Name: Population, total, dtype: float64
22.060721951948565
1070    2913021.0
Name: Population, total, dtype: float64
14.300763378504262
5431    16321872.0
Name: Population, total, dtype: float64
0.5293791277280679
1364    2877311.0
Name: Population, total, dtype: float64
78.53224632155123
1756    9490583.0
Name: Population, total, dtype: float64
2.9161368673471495
6411    364511.0
Name: Population, total, dtype: float64
14.759711029862943
2001    727641.0
Name: Population, total, dtype: float64
0.0
335    1.230981e+09
Name: Population, total, dtype: float64
2.9677712330581545
1021    28803167.0
Name: Population, total, dtype: float64
1.8873192146340232
1658    152149102.0
Name: Population, total, dtype: float64
1.9654336815098976
7195    27023137.0
Name: Population, total, dtype: float64
6.558247232531511
7685    170560182.0
Name: Population, total, dtype: float64
3.3455745483531083
9057    20198353.0
Name: Population, total, dtype: float64
4.711687595134846
5823    2097555.0
Name: Population, total, dtype: float64
53.67025940055817
6901    619428.0
Name: Population, total, dtype: float64
14.440034463013252
1511    9054332.0
Name: Population, total, dtype: float64
15.588941505004854
2295    7395599.0
Name: Population, total, dtype: float64
8.711067630621015
2099    3722084.0
Name: Population, total, dtype: float64
30.14481894543198
874    72326914.0
Name: Population, total, dtype: float64
10.48710902577952
6117    3097282.0
Name: Population, total, dtype: float64
20.66261546303013
8224    20246871.0
Name: Population, total, dtype: float64
11.781383982844938
9645    1109591.0
Name: Population, total, dtype: float64
0.0
4059    859950.0
Name: Population, total, dtype: float64
9.916918164575181
7832    7108239.0
Name: Population, total, dtype: float64
34.97706546830332
188    1.337705e+09
Name: Population, total, dtype: float64
12.000476256816162
9596    67208808.0
Name: Population, total, dtype: float64
11.093636684289176
7979    93726624.0
Name: Population, total, dtype: float64
1.7357380861760268
6852    2712650.0
Name: Population, total, dtype: float64
0.0
2491    14308740.0
Name: Population, total, dtype: float64
4.793198808201085
5774    6246274.0
Name: Population, total, dtype: float64
0.09564368188384398
384    242524123.0
Name: Population, total, dtype: float64
11.954248574819154
10380    88472512.0
Name: Population, total, dtype: float64
0.9442894371152772
4353    24512104.0
Name: Population, total, dtype: float64
0.0
5921    2040551.0
Name: Population, total, dtype: float64
0.9105364355117329
7097    2173170.0
Name: Population, total, dtype: float64
4.853664470017811
3912    1202843.0
Name: Population, total, dtype: float64
0.41469270021980176
8959    51584663.0
Name: Population, total, dtype: float64
2.6216608370956807
3961    87702670.0
Name: Population, total, dtype: float64
1.452445990645131
4255    1692149.0
Name: Population, total, dtype: float64
0.0
6656    1250400.0
Name: Population, total, dtype: float64
11.353901301044306
6999    24221405.0
Name: Population, total, dtype: float64
1.7024402195113877
5970    3948125.0
Name: Population, total, dtype: float64
1.4175567277885086
5480    41350152.0
Name: Population, total, dtype: float64
1.294277635993368
2442    502384.0
Name: Population, total, dtype: float64
17.174160384045354
7440    158578261.0
Name: Population, total, dtype: float64
0.0
6313    15167095.0
Name: Population, total, dtype: float64
0.8356088004482983
6607    3609543.0
Name: Population, total, dtype: float64
35.62071483623862
1903    9199259.0
Name: Population, total, dtype: float64
0.5309261442835165
2344    15605217.0
Name: Population, total, dtype: float64
0.9744653357572644
3128    20401331.0
Name: Population, total, dtype: float64
2.326256931436642
2540    19970495.0
Name: Population, total, dtype: float64
1.960321803647149
3030    4386693.0
Name: Population, total, dtype: float64
2.5237109744947146
4206    1640210.0
Name: Population, total, dtype: float64
8.464415533079167
6460    15075085.0
Name: Population, total, dtype: float64
0.9790070808657332
7391    16425578.0
Name: Population, total, dtype: float64
3.1358561984151683
9694    6502952.0
Name: Population, total, dtype: float64
4.023557711922855
8469    12916229.0
Name: Population, total, dtype: float64
5.384449769306714
2736    11887202.0
Name: Population, total, dtype: float64
3.3269160863926723
8273    10246842.0

Name: Population, total, dtype: float64
0.4695639578496484
2981    64523263.0
Name: Population, total, dtype: float64
0.07239515654489902
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
0.42711701824607784
6264    21151640.0
Name: Population, total, dtype: float64
0.0
10037    33915133.0
Name: Population, total, dtype: float64
0.0
8616    6458720.0
Name: Population, total, dtype: float64
0.0
10576    13850033.0
Name: Population, total, dtype: float64
0.001036694985831497
4696    10794170.0
Name: Population, total, dtype: float64
0.7383203905746868
8420    174776.0
Name: Population, total, dtype: float64
13.211274455134289
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
6.361273000242485
7930    29373646.0
Name: Population, total, dtype: float64
23.35168483431805
2050    9918242.0
Name: Population, total, dtype: float64
0.0
4647    14630417.0
Name: Population, total, dtype: float64
12.963665719166265
580    117318941.0
Name: Population, total, dtype: float64
3.6274901955833108
4892    8194778.0
Name: Population, total, dtype: float64
7.147544063928268
7342    5737723.0
Name: Population, total, dtype: float64
1.2874228142797215
5333    2817210.0
Name: Population, total, dtype: float64
4.380716859194784
2883    45918097.0
Name: Population, total, dtype: float64
0.0
5382    7182390.0
Name: Population, total, dtype: float64
5.51707334347858
5137    30762701.0
Name: Population, total, dtype: float64
4.638819237701332
3667    84107606.0
Name: Population, total, dtype: float64
9.35932325738987
6950    32409639.0
Name: Population, total, dtype: float64
8.606431535673694
3471    851146.0
Name: Population, total, dtype: float64
56.56210254300247
10527    23606779.0
Name: Population, total, dtype: float64
3.4945400051330626
9498    7641630.0
Name: Population, total, dtype: float64
34.380196269625486
10086    45870700.0
Name: Population, total, dtype: float64
44.73420150823394
6754    3562045.0
Name: Population, total, dtype: float64
22.599240414953822
678    142849449.0
Name: Population, total, dtype: float64
57.57186067297165
5725    5447900.0
Name: Population, total, dtype: float64
2.2857358392313865
7489    2070739.0
Name: Population, total, dtype: float64
29.55428227715584
8518    7291436.0
Name: Population, total, dtype: float64
15.347575408395004
1070    2913021.0
Name: Population, total, dtype: float64
52.15434173340462
5431    16321872.0
Name: Population, total, dtype: float64
45.51193104486987
1364    2877311.0
Name: Population, total, dtype: float64
13.795510439010801
1756    9490583.0
Name: Population, total, dtype: float64
20.638013065437473
6411    364511.0
Name: Population, total, dtype: float64
7.529698271699151
2001    727641.0
Name: Population, total, dtype: float64
14.01958843896523
335    1.230981e+09
Name: Population, total, dtype: float64
0.34151734200612455
1021    28803167.0
Name: Population, total, dtype: float64
7.162852459628662
1658    152149102.0
Name: Population, total, dtype: float64
0.0
7195    27023137.0
Name: Population, total, dtype: float64
2.5369715236270807
7685    170560182.0
Name: Population, total, dtype: float64
0.0
9057    20198353.0
Name: Population, total, dtype: float64
0.6894976798783642
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
59.171994372905345
7930    29373646.0
Name: Population, total, dtype: float64
32.220875301953576
2050    9918242.0
Name: Population, total, dtype: float64
30.46000768463515
4647    14630417.0
Name: Population, total, dtype: float64
11.068350512177723
580    117318941.0
Name: Population, total, dtype: float64
24.408441194073326
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
6.489818178721215
5333    2817210.0
Name: Population, total, dtype: float64
42.658933705166454
2883    45918097.0
Name: Population, total, dtype: float64
30.752335098375866
5382    7182390.0
Name: Population, total, dtype: float64
23.632238567231873
5137    30762701.0
Name: Population, total, dtype: float64
0.0
3667    84107606.0
Name: Population, total, dtype: float64
8.79030597823382
6950    32409639.0
Name: Population, total, dtype: float64
28.554607798450043
3471    851146.0
Name: Population, total, dtype: float64
64.2101675159088
10527    23606779.0
Name: Population, total, dtype: float64
20.414227367568593
4353    24512104.0
Name: Population, total, dtype: float64
18.5176628847379
5921    2040551.0
Name: Population, total, dtype: float64
2.6536467399785515
7097    2173170.0
Name: Population, total, dtype: float64
28.95557221420645
3912    1202843.0
Name: Population, total, dtype: float64
10.608884844897855
8959    51584663.0
Name: Population, total, dtype: float64
47.25211823264878
3961    87702670.0
Name: Population, total, dtype: float64
4.294082280102706
4255    1692149.0
Name: Population, total, dtype: float64
4.298487993843326
6656    1250400.0
Name: Population, total, dtype: float64
11.46488829794342
6999    24221405.0
Name: Population, total, dtype: float64
4.165780688540335
5970    3948125.0
Name: Population, total, dtype: float64
1.792751660219554
5480    41350152.0
Name: Population, total, dtype: float64
7.648530412565386
2442    502384.0
Name: Population, total, dtype: float64
48.50884186693511
7440    158578261.0
Name: Population, total, dtype: float64
2.1558396922023415
6313    15167095.0
Name: Population, total, dtype: float64
4.970401416419004
6607    3609543.0
Name: Population, total, dtype: float64
30.389888093501014
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
6.256180447478028
3128    20401331.0
Name: Population, total, dtype: float64
12.32822247253421
2540    19970495.0
Name: Population, total, dtype: float64
7.181101814204352
3030    4386693.0
Name: Population, total, dtype: float64
15.123572839362394
4206    1640210.0
Name: Population, total, dtype: float64
34.23255677204169
6460    15075085.0
Name: Population, total, dtype: float64
4.31542463075604
7391    16425578.0
Name: Population, total, dtype: float64
7.750893998767151
9694    6502952.0
Name: Population, total, dtype: float64
6.855425854303471
8469    12916229.0
Name: Population, total, dtype: float64
12.916959260389365
2736    11887202.0
Name: Population, total, dtype: float64
0.8443663382342892
8273    10246842.0
Name: Population, total, dtype: float64
1.0562196689620682
2981    64523263.0
Name: Population, total, dtype: float64
3.4918470151517247
2393    8766930.0
Name: Population, total, dtype: float64
0.9707952521157458
9547    46098591.0
Name: Population, total, dtype: float64
0.7521310975195213
6264    21151640.0
Name: Population, total, dtype: float64
2.4331466770613606
10037    33915133.0
Name: Population, total, dtype: float64
28.372740098031933
8616    6458720.0
Name: Population, total, dtype: float64
2.80249979771862
10576    13850033.0
Name: Population, total, dtype: float64
5.020659513510641
4696    10794170.0
Name: Population, total, dtype: float64
2.1960038004144833
8420    174776.0
Name: Population, total, dtype: float64
22.641103088984607
5823    2097555.0
Name: Population, total, dtype: float64
36.84894919636383
6901    619428.0
Name: Population, total, dtype: float64
42.70114431618784
1511    9054332.0
Name: Population, total, dtype: float64
10.46403663574019
2295    7395599.0
Name: Population, total, dtype: float64
102.78467552479664
2099    3722084.0
Name: Population, total, dtype: float64
57.57342898379697
874    72326914.0
Name: Population, total, dtype: float64
42.851766936470355
6117    3097282.0
Name: Population, total, dtype: float64
9.688590639688291
8224    20246871.0
Name: Population, total, dtype: float64
0.0
9498    7641630.0
Name: Population, total, dtype: float64
6.718620254081732
10086    45870700.0
Name: Population, total, dtype: float64
14.391692431553626
6754    3562045.0
Name: Population, total, dtype: float64
0.0
678    142849449.0
Name: Population, total, dtype: float64
16.83024763163206
5725    5447900.0
Name: Population, total, dtype: float64
5.92198268085209
7489    2070739.0
Name: Population, total, dtype: float64
2.592922274500928
8518    7291436.0
Name: Population, total, dtype: float64
83.36903977901922
1070    2913021.0
Name: Population, total, dtype: float64
25.653837693380865
5431    16321872.0
Name: Population, total, dtype: float64
21.586665462493443
1364    2877311.0
Name: Population, total, dtype: float64
14.419763150513885
1756    9490583.0
Name: Population, total, dtype: float64
25.696910606302765
6411    364511.0
Name: Population, total, dtype: float64
22.124891522548605
2001    727641.0
Name: Population, total, dtype: float64
3.0976856662325654
335    1.230981e+09
Name: Population, total, dtype: float64
1.994151384798929
1021    28803167.0
Name: Population, total, dtype: float64
1.4494196175807894
1658    152149102.0
Name: Population, total, dtype: float64
0.16127682081647443
7195    27023137.0
Name: Population, total, dtype: float64
5.758245764699044
7685    170560182.0
Name: Population, total, dtype: float64
0.1671147711467762
9057    20198353.0
Name: Population, total, dtype: float64
5.753740365853446
9645    1109591.0
Name: Population, total, dtype: float64
0.23866378066408936
4059    859950.0
Name: Population, total, dtype: float64
24.55311219556258
7832    7108239.0
Name: Population, total, dtype: float64
0.0
188    1.337705e+09
Name: Population, total, dtype: float64
12.3067749704414
9596    67208808.0
Name: Population, total, dtype: float64
29.655547864724994
7979    93726624.0
Name: Population, total, dtype: float64
13.409980208869488
6852    2712650.0
Name: Population, total, dtype: float64
13.378236531892593
2491    14308740.0
Name: Population, total, dtype: float64
7.547605340635871
5774    6246274.0
Name: Population, total, dtype: float64
2.417726115377861
384    242524123.0
Name: Population, total, dtype: float64
4.941463681338817
10380    88472512.0
Name: Population, total, dtype: float64
5.510732254459618
4353    24512104.0
Name: Population, total, dtype: float64
16.557765254936577
5921    2040551.0
Name: Population, total, dtype: float64
0.2946177837672089
7097    2173170.0
Name: Population, total, dtype: float64
3.697903936101033
3912    1202843.0
Name: Population, total, dtype: float64
0.9190217908793237
8959    51584663.0
Name: Population, total, dtype: float64
1.700756218960079
3961    87702670.0
Name: Population, total, dtype: float64
1.021186007215676
4255    1692149.0
Name: Population, total, dtype: float64
3.7523180512345973
6656    1250400.0
Name: Population, total, dtype: float64
5.024610788766094
6999    24221405.0
Name: Population, total, dtype: float64
4.43540604181713
5970    3948125.0
Name: Population, total, dtype: float64
9.418234770600968
5480    41350152.0
Name: Population, total, dtype: float64
2.182418023989385
2442    502384.0
Name: Population, total, dtype: float64
0.1600177083348902
7440    158578261.0
Name: Population, total, dtype: float64
3.0649706849577565
6313    15167095.0
Name: Population, total, dtype: float64
0.05118640569253222
6607    3609543.0
Name: Population, total, dtype: float64
7.013157542793191
1903    9199259.0
Name: Population, total, dtype: float64
0.5522512605162959
2344    15605217.0
Name: Population, total, dtype: float64
1.0127225906193438
3128    20401331.0
Name: Population, total, dtype: float64

0.08000228206024539
2540    19970495.0
Name: Population, total, dtype: float64
1.3320831725086053
3030    4386693.0
Name: Population, total, dtype: float64
0.20793562615488317
4206    1640210.0
Name: Population, total, dtype: float64
0.0
6460    15075085.0
Name: Population, total, dtype: float64
0.0
7391    16425578.0
Name: Population, total, dtype: float64
0.5592460963983868
9694    6502952.0
Name: Population, total, dtype: float64
0.04491067554817949
8469    12916229.0
Name: Population, total, dtype: float64
0.09847848648267934
2736    11887202.0
Name: Population, total, dtype: float64
0.5308789281878742
8273    10246842.0
Name: Population, total, dtype: float64
38.466294903116655
2981    64523263.0
Name: Population, total, dtype: float64
0.0
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
6.447857524603628
6264    21151640.0
Name: Population, total, dtype: float64
0.039350339517309346
10037    33915133.0
Name: Population, total, dtype: float64
12.983969929221582
8616    6458720.0
Name: Population, total, dtype: float64
0.17855667042139545
10576    13850033.0
Name: Population, total, dtype: float64
0.008993680838333084
4696    10794170.0
Name: Population, total, dtype: float64
11.866598810452174
8420    174776.0
Name: Population, total, dtype: float64
3.3694510422029285
5823    2097555.0
Name: Population, total, dtype: float64
21.69818648162005
6901    619428.0
Name: Population, total, dtype: float64
11.9664710596505
1511    9054332.0
Name: Population, total, dtype: float64
33.563582039361606
2295    7395599.0
Name: Population, total, dtype: float64
58.17231535439373
2099    3722084.0
Name: Population, total, dtype: float64
21.659521109688363
874    72326914.0
Name: Population, total, dtype: float64
21.705503134279912
6117    3097282.0
Name: Population, total, dtype: float64
13.008284406058806
8224    20246871.0
Name: Population, total, dtype: float64
2.4232673840175862
9498    7641630.0
Name: Population, total, dtype: float64
17.833629708221157
10086    45870700.0
Name: Population, total, dtype: float64
7.765041255669118
6754    3562045.0
Name: Population, total, dtype: float64
13.323846380373034
678    142849449.0
Name: Population, total, dtype: float64
20.826823109532185
5725    5447900.0
Name: Population, total, dtype: float64
8.0009747782445
7489    2070739.0
Name: Population, total, dtype: float64
28.38616095778152
8518    7291436.0
Name: Population, total, dtype: float64
5.900070059069779
1070    2913021.0
Name: Population, total, dtype: float64
1.2926735117336698
5431    16321872.0
Name: Population, total, dtype: float64
17.393174662395925
1364    2877311.0
Name: Population, total, dtype: float64
43.47235131421784
1756    9490583.0
Name: Population, total, dtype: float64
5.322193331302003
6411    364511.0
Name: Population, total, dtype: float64
14.590276616274545
2001    727641.0
Name: Population, total, dtype: float64
1.9610793724931321
335    1.230981e+09
Name: Population, total, dtype: float64
3.578411561840794
1021    28803167.0
Name: Population, total, dtype: float64
19.212545530910912
1658    152149102.0
Name: Population, total, dtype: float64
1.1708660523867467
7195    27023137.0
Name: Population, total, dtype: float64
0.8114691351733789
7685    170560182.0
Name: Population, total, dtype: float64
0.8234241377021975
9645    1109591.0
Name: Population, total, dtype: float64
4.177737877427398
4059    859950.0
Name: Population, total, dtype: float64
0.645028981395724
7832    7108239.0
Name: Population, total, dtype: float64
66.68809149581527
188    1.337705e+09
Name: Population, total, dtype: float64
14.708412270781961
9596    67208808.0
Name: Population, total, dtype: float64
6.264477751012825
7979    93726624.0
Name: Population, total, dtype: float64
0.5428139507282868
6852    2712650.0
Name: Population, total, dtype: float64
1.1183659166434885
2491    14308740.0
Name: Population, total, dtype: float64
4.175013042929515
5774    6246274.0
Name: Population, total, dtype: float64
0.03705841295836085
384    242524123.0
Name: Population, total, dtype: float64
1.341622298955903
10380    88472512.0
Name: Population, total, dtype: float64
1.7994629363864443
3716    6164626.0
Name: Population, total, dtype: float64
19.70705791508481
139    196796269.0
Name: Population, total, dtype: float64
6.31595557806973
7930    29373646.0
Name: Population, total, dtype: float64
10.82751081592467
2050    9918242.0
Name: Population, total, dtype: float64
7.211874288508496
4647    14630417.0
Name: Population, total, dtype: float64
2.597958597032922
580    117318941.0
Name: Population, total, dtype: float64
0.2786337440155871
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
0.09622727329052021
5333    2817210.0
Name: Population, total, dtype: float64
8.031013608540315
2883    45918097.0
Name: Population, total, dtype: float64
0.0
5382    7182390.0
Name: Population, total, dtype: float64
15.53873972585192
5137    30762701.0
Name: Population, total, dtype: float64
10.193331718455763
3667    84107606.0
Name: Population, total, dtype: float64
6.038947273795709
6950    32409639.0
Name: Population, total, dtype: float64
4.337263211501728
3471    851146.0
Name: Population, total, dtype: float64
27.85448405752705
10527    23606779.0
Name: Population, total, dtype: float64
5.631894085095818
9057    20198353.0
Name: Population, total, dtype: float64
58.008052071032694
4353    24512104.0
Name: Population, total, dtype: float64
6.958247209633159
5921    2040551.0
Name: Population, total, dtype: float64
1.2932963455078674
7097    2173170.0
Name: Population, total, dtype: float64
5.854721940603485
3912    1202843.0
Name: Population, total, dtype: float64
4.639892857680431
8959    51584663.0
Name: Population, total, dtype: float64
14.764681889725589
3961    87702670.0
Name: Population, total, dtype: float64
30.693234939609447
4255    1692149.0
Name: Population, total, dtype: float64
22.271873303677626
6656    1250400.0
Name: Population, total, dtype: float64
48.0747214643896
6999    24221405.0
Name: Population, total, dtype: float64
0.9389891888426651
5970    3948125.0
Name: Population, total, dtype: float64
5.077304291782556
5480    41350152.0
Name: Population, total, dtype: float64
1.9361642206429575
2442    502384.0
Name: Population, total, dtype: float64
36.23122641927004
7440    158578261.0
Name: Population, total, dtype: float64
23.04431585653949
6313    15167095.0
Name: Population, total, dtype: float64
6.289401362289155
6607    3609543.0
Name: Population, total, dtype: float64
0.01479199929957349
1903    9199259.0
Name: Population, total, dtype: float64
13.270997102766877
2344    15605217.0
Name: Population, total, dtype: float64
9.028874357904098
3128    20401331.0
Name: Population, total, dtype: float64
25.97643984944592
2540    19970495.0
Name: Population, total, dtype: float64
16.036132636694326
3030    4386693.0
Name: Population, total, dtype: float64
23.609410564258468
4206    1640210.0
Name: Population, total, dtype: float64
4.2166269760822175
6460    15075085.0
Name: Population, total, dtype: float64
15.74403072566822
7391    16425578.0
Name: Population, total, dtype: float64
9.686934062462546
9694    6502952.0
Name: Population, total, dtype: float64
4.195119843865161
8469    12916229.0
Name: Population, total, dtype: float64
6.650942018160213
2736    11887202.0
Name: Population, total, dtype: float64
22.55172378433497
8273    10246842.0
Name: Population, total, dtype: float64
0.9983030797382266
2981    64523263.0
Name: Population, total, dtype: float64
7.9069834496572025
2393    8766930.0
Name: Population, total, dtype: float64
38.02887497871059
9547    46098591.0
Name: Population, total, dtype: float64
24.89786972842482
6264    21151640.0
Name: Population, total, dtype: float64
6.936565088372154
10037    33915133.0
Name: Population, total, dtype: float64
26.453297568909644
8616    6458720.0
Name: Population, total, dtype: float64
0.0
10576    13850033.0
Name: Population, total, dtype: float64
16.647856464815476
4696    10794170.0
Name: Population, total, dtype: float64
3.54967650880015
8420    174776.0
Name: Population, total, dtype: float64
26.285508812833896
5823    2097555.0
Name: Population, total, dtype: float64
53.815986690085595
6901    619428.0
Name: Population, total, dtype: float64
14.330704338291948
1511    9054332.0
Name: Population, total, dtype: float64
1.0839357696350922
2295    7395599.0
Name: Population, total, dtype: float64
112.46634997391556
2099    3722084.0
Name: Population, total, dtype: float64
6.019486191295929
874    72326914.0
Name: Population, total, dtype: float64
25.570910442100494
6117    3097282.0
Name: Population, total, dtype: float64
37.40000855022008
8224    20246871.0
Name: Population, total, dtype: float64
27.276612393553677
9498    7641630.0
Name: Population, total, dtype: float64
0.05174286244283983
10086    45870700.0
Name: Population, total, dtype: float64
74.81340129879251
6754    3562045.0
Name: Population, total, dtype: float64
9.821730415458592
678    142849449.0

Name: Population, total, dtype: float64
39.64426138484159
5725    5447900.0
Name: Population, total, dtype: float64
13.80661779410067
7489    2070739.0
Name: Population, total, dtype: float64
19.078080813498506
8518    7291436.0
Name: Population, total, dtype: float64
6.34542889647436
1070    2913021.0
Name: Population, total, dtype: float64
33.26217601737166
5431    16321872.0
Name: Population, total, dtype: float64
60.55291456161527
1364    2877311.0
Name: Population, total, dtype: float64
34.548070840722175
1756    9490583.0
Name: Population, total, dtype: float64
22.27614471578519
6411    364511.0
Name: Population, total, dtype: float64
6.683921429095807
2001    727641.0
Name: Population, total, dtype: float64
13.654099569673665
335    1.230981e+09
Name: Population, total, dtype: float64
27.773472605193493
1021    28803167.0
Name: Population, total, dtype: float64
26.991761027001438
1658    152149102.0
Name: Population, total, dtype: float64
8.348678202048866
7195    27023137.0
Name: Population, total, dtype: float64
0.0
7685    170560182.0
Name: Population, total, dtype: float64
13.823199407014533
9057    20198353.0
Name: Population, total, dtype: float64
3.0398328585381087
9645    1109591.0
Name: Population, total, dtype: float64
6.793925672933482
4059    859950.0
Name: Population, total, dtype: float64
10.76391161296791
7832    7108239.0
Name: Population, total, dtype: float64
1.9295615443500114
188    1.337705e+09
Name: Population, total, dtype: float64
21.745801863383036
9596    67208808.0
Name: Population, total, dtype: float64
3.851269500135448
7979    93726624.0
Name: Population, total, dtype: float64
5.683615107048723
6852    2712650.0
Name: Population, total, dtype: float64
3.301199113811027
2491    14308740.0
Name: Population, total, dtype: float64
10.274349021963221
5774    6246274.0
Name: Population, total, dtype: float64
0.4500628296366889
384    242524123.0
Name: Population, total, dtype: float64
18.408265417050963
10380    88472512.0
Name: Population, total, dtype: float64
4.469321531533466
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
0.7496318417298432
7930    29373646.0
Name: Population, total, dtype: float64
5.008136307486076
2050    9918242.0
Name: Population, total, dtype: float64
13.318795670684995
4647    14630417.0
Name: Population, total, dtype: float64
0.0
580    117318941.0
Name: Population, total, dtype: float64
5.299386927595227
4892    8194778.0
Name: Population, total, dtype: float64
0.8664722797101365
7342    5737723.0
Name: Population, total, dtype: float64
0.0
5333    2817210.0
Name: Population, total, dtype: float64
13.6997096376911
2883    45918097.0
Name: Population, total, dtype: float64
22.873383846855493
5382    7182390.0
Name: Population, total, dtype: float64
17.47608025284307
5137    30762701.0
Name: Population, total, dtype: float64
49.03776476233425
3667    84107606.0
Name: Population, total, dtype: float64
0.31052209168465905
6950    32409639.0
Name: Population, total, dtype: float64
29.934955427091815
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
42.01168542385367
4353    24512104.0
Name: Population, total, dtype: float64
0.08321961390631719
5921    2040551.0
Name: Population, total, dtype: float64
0.4336273790730583
7097    2173170.0
Name: Population, total, dtype: float64
0.9870998575338764
3912    1202843.0
Name: Population, total, dtype: float64
0.8536634035475605
8959    51584663.0
Name: Population, total, dtype: float64
5.865289657500906
3961    87702670.0
Name: Population, total, dtype: float64
2.220026759154739
4255    1692149.0
Name: Population, total, dtype: float64
0.056451022954936834
6656    1250400.0
Name: Population, total, dtype: float64
14.397182544000424
6999    24221405.0
Name: Population, total, dtype: float64
0.028739108846022317
5970    3948125.0
Name: Population, total, dtype: float64
0.21181246593158554
5480    41350152.0
Name: Population, total, dtype: float64
0.049890001589957
2442    502384.0
Name: Population, total, dtype: float64
8.317394226478006
7440    158578261.0
Name: Population, total, dtype: float64
0.04655798815260359
6313    15167095.0
Name: Population, total, dtype: float64
0.1293587373687464
6607    3609543.0
Name: Population, total, dtype: float64
0.14938463182998363
1903    9199259.0
Name: Population, total, dtype: float64
0.02183410618133036
2344    15605217.0
Name: Population, total, dtype: float64
0.01699443013556128
3128    20401331.0
Name: Population, total, dtype: float64
0.39325796862169143
2540    19970495.0
Name: Population, total, dtype: float64
0.059385066668376035
3030    4386693.0
Name: Population, total, dtype: float64
0.35951509908668955
4206    1640210.0
Name: Population, total, dtype: float64
5.752758925206168
6460    15075085.0
Name: Population, total, dtype: float64
0.4729979897070489
7391    16425578.0
Name: Population, total, dtype: float64
1.4961661119050762
9694    6502952.0
Name: Population, total, dtype: float64
0.10497184783801691
9645    1109591.0
Name: Population, total, dtype: float64
0.2586519625974873
4059    859950.0
Name: Population, total, dtype: float64
1.1472864138549137
7832    7108239.0
Name: Population, total, dtype: float64
0.2868973601030625
188    1.337705e+09
Name: Population, total, dtype: float64
0.760992716373793
9596    67208808.0
Name: Population, total, dtype: float64
0.30830054942963686
7979    93726624.0
Name: Population, total, dtype: float64
0.0
6852    2712650.0
Name: Population, total, dtype: float64
8.360746825124929
2491    14308740.0
Name: Population, total, dtype: float64
0.28077187605512877
5774    6246274.0
Name: Population, total, dtype: float64
0.014011326716528672
384    242524123.0
Name: Population, total, dtype: float64
0.09486096591592318
10380    88472512.0
Name: Population, total, dtype: float64
0.0
3716    6164626.0
Name: Population, total, dtype: float64
36.02199961272839
139    196796269.0
Name: Population, total, dtype: float64
17.624519195989713
7930    29373646.0
Name: Population, total, dtype: float64
18.98977156169636
2050    9918242.0
Name: Population, total, dtype: float64
24.066712422474428
4647    14630417.0
Name: Population, total, dtype: float64
16.525268063751206
580    117318941.0
Name: Population, total, dtype: float64
21.420803085967684
4892    8194778.0
Name: Population, total, dtype: float64
45.11389826157889
7342    5737723.0
Name: Population, total, dtype: float64
8.68099627218729
5333    2817210.0
Name: Population, total, dtype: float64
8.15164683239537
2883    45918097.0
Name: Population, total, dtype: float64
35.6444985212009
5382    7182390.0
Name: Population, total, dtype: float64
27.99276987017669
5137    30762701.0
Name: Population, total, dtype: float64
27.48932439565904
3667    84107606.0
Name: Population, total, dtype: float64
25.61738930805994
6950    32409639.0
Name: Population, total, dtype: float64
5.054047672662949
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
3.9170034492874106
8469    12916229.0
Name: Population, total, dtype: float64
0.3124233074979529
2736    11887202.0
Name: Population, total, dtype: float64
0.0
8273    10246842.0
Name: Population, total, dtype: float64
0.13220487218336555
2981    64523263.0
Name: Population, total, dtype: float64
0.012835971810402103
2393    8766930.0
Name: Population, total, dtype: float64
0.10407467684360379
9547    46098591.0
Name: Population, total, dtype: float64
0.0008212358668681881
6264    21151640.0
Name: Population, total, dtype: float64
0.10473657166174415
10037    33915133.0
Name: Population, total, dtype: float64
0.0
8616    6458720.0
Name: Population, total, dtype: float64
0.06990481535162583
10576    13850033.0
Name: Population, total, dtype: float64
0.15637771973102801
4696    10794170.0
Name: Population, total, dtype: float64
0.48820892753804834
8420    174776.0
Name: Population, total, dtype: float64
0.0
5823    2097555.0
Name: Population, total, dtype: float64
101.80961922869437
6901    619428.0
Name: Population, total, dtype: float64
134.9563569965402
1511    9054332.0
Name: Population, total, dtype: float64
24.037351163360885
2295    7395599.0
Name: Population, total, dtype: float64
91.50183988293239
2099    3722084.0
Name: Population, total, dtype: float64
71.49230945139215
874    72326914.0
Name: Population, total, dtype: float64
54.969787461987494
6117    3097282.0
Name: Population, total, dtype: float64
21.10319181478817
8224    20246871.0
Name: Population, total, dtype: float64
108.12817571347549
9498    7641630.0
Name: Population, total, dtype: float64
2.5575775295722205
10086    45870700.0
Name: Population, total, dtype: float64
92.5709151067083
6754    3562045.0
Name: Population, total, dtype: float64
58.78400453984885
678    142849449.0
Name: Population, total, dtype: float64
97.13797067863464
5725    5447900.0
Name: Population, total, dtype: float64
6.11992699526805
7489    2070739.0
Name: Population, total, dtype: float64
158.81293751360192
8518    7291436.0
Name: Population, total, dtype: float64
68.22305155080454
1070    2913021.0
Name: Population, total, dtype: float64
136.13037108938803
5431    16321872.0
Name: Population, total, dtype: float64
25.540346057857477
1364    2877311.0
Name: Population, total, dtype: float64
67.38927728174421
1756    9490583.0
Name: Population, total, dtype: float64
53.17040315394579
6411    364511.0
Name: Population, total, dtype: float64
0.40482000854488553
2001    727641.0
Name: Population, total, dtype: float64
41.50978210160889
335    1.230981e+09
Name: Population, total, dtype: float64
0.4470835286174114
1021    28803167.0
Name: Population, total, dtype: float64
1.8419478905365139
1658    152149102.0
Name: Population, total, dtype: float64
0.5610427535370152
7195    27023137.0
Name: Population, total, dtype: float64
0.0024858551505209307
7685    170560182.0
Name: Population, total, dtype: float64
0.08990549004513049
9057    20198353.0
Name: Population, total, dtype: float64
2.819198138483751
9645    1109591.0
Name: Population, total, dtype: float64
13.411393778336619
4059    859950.0
Name: Population, total, dtype: float64
14.763276550617912
7832    7108239.0
Name: Population, total, dtype: float64
13.002799380165088
188    1.337705e+09
Name: Population, total, dtype: float64
43.97992787656347
9596    67208808.0
Name: Population, total, dtype: float64
16.716562904912355
7979    93726624.0
Name: Population, total, dtype: float64
9.25002830557713
6852    2712650.0
Name: Population, total, dtype: float64
50.21312204870174
3716    6164626.0
Name: Population, total, dtype: float64
1.692829931654639
139    196796269.0
Name: Population, total, dtype: float64
127.90397192845097
7930    29373646.0
Name: Population, total, dtype: float64
44.01701747800873
2050    9918242.0
Name: Population, total, dtype: float64
18.367862899892877
4647    14630417.0
Name: Population, total, dtype: float64
33.275656755013294
580    117318941.0
Name: Population, total, dtype: float64
52.26279130946734
4892    8194778.0
Name: Population, total, dtype: float64
14.657287149674008
7342    5737723.0
Name: Population, total, dtype: float64
3.4488129272149832
5333    2817210.0
Name: Population, total, dtype: float64
69.95040714977117
2883    45918097.0
Name: Population, total, dtype: float64
28.00193990200673
5382    7182390.0
Name: Population, total, dtype: float64
25.594732171042843
5137    30762701.0
Name: Population, total, dtype: float64
40.95267092968024
3667    84107606.0
Name: Population, total, dtype: float64
14.346233789431697
6950    32409639.0
Name: Population, total, dtype: float64
24.161325088570848
3471    851146.0
Name: Population, total, dtype: float64
6.002797155793176
10527    23606779.0
Name: Population, total, dtype: float64
20.982565760911342
4353    24512104.0
Name: Population, total, dtype: float64
17.79194761940922
5921    2040551.0
Name: Population, total, dtype: float64
67.9888241738024
7097    2173170.0
Name: Population, total, dtype: float64
17.788868155160518
3912    1202843.0
Name: Population, total, dtype: float64
13.643706772013504
8959    51584663.0
Name: Population, total, dtype: float64
57.37799628668736
3961    87702670.0
Name: Population, total, dtype: float64

16.812882809951457
4255    1692149.0
Name: Population, total, dtype: float64
30.723917889760294
6656    1250400.0
Name: Population, total, dtype: float64
33.71448045966581
6999    24221405.0
Name: Population, total, dtype: float64
6.18431442015522
5970    3948125.0
Name: Population, total, dtype: float64
10.625007720833633
5480    41350152.0
Name: Population, total, dtype: float64
15.031612398189436
2442    502384.0
Name: Population, total, dtype: float64
20.774657243702148
7440    158578261.0
Name: Population, total, dtype: float64
4.20760096897048
6313    15167095.0
Name: Population, total, dtype: float64
3.605626026288665
6607    3609543.0
Name: Population, total, dtype: float64
27.445250915852274
1903    9199259.0
Name: Population, total, dtype: float64
10.029859466214683
2344    15605217.0
Name: Population, total, dtype: float64
11.141615698233267
3128    20401331.0
Name: Population, total, dtype: float64
15.020100198409683
2540    19970495.0
Name: Population, total, dtype: float64
17.337105915111945
3030    4386693.0
Name: Population, total, dtype: float64
12.484870939532295
4206    1640210.0
Name: Population, total, dtype: float64
24.50060421119597
6460    15075085.0
Name: Population, total, dtype: float64
7.92294318647644
7391    16425578.0
Name: Population, total, dtype: float64
7.838973586213845
9694    6502952.0
Name: Population, total, dtype: float64
8.25444701215437
8469    12916229.0
Name: Population, total, dtype: float64
10.371917977182868
2736    11887202.0
Name: Population, total, dtype: float64
8.447370955779148
8273    10246842.0
Name: Population, total, dtype: float64
8.122404083802644
2981    64523263.0
Name: Population, total, dtype: float64
2.7283462606982747
2393    8766930.0
Name: Population, total, dtype: float64
1.768264846778063
9547    46098591.0
Name: Population, total, dtype: float64
5.021180309059951
6264    21151640.0
Name: Population, total, dtype: float64
2.500424250543374
10037    33915133.0
Name: Population, total, dtype: float64
5.921464343296049
8616    6458720.0
Name: Population, total, dtype: float64
32.46520971981168
10576    13850033.0
Name: Population, total, dtype: float64
3.421136385504773
4696    10794170.0
Name: Population, total, dtype: float64
8.54926833137216
8420    174776.0
Name: Population, total, dtype: float64
18.57502301943682
5823    2097555.0
Name: Population, total, dtype: float64
90.42957448099261
6901    619428.0
Name: Population, total, dtype: float64
151.85141665888824
1511    9054332.0
Name: Population, total, dtype: float64
50.84758374689224
2295    7395599.0
Name: Population, total, dtype: float64
53.58364715613853
2099    3722084.0
Name: Population, total, dtype: float64
138.9409857428802
874    72326914.0
Name: Population, total, dtype: float64
52.46438141859599
6117    3097282.0
Name: Population, total, dtype: float64
126.05361779058745
8224    20246871.0
Name: Population, total, dtype: float64
94.21212982433288
9498    7641630.0
Name: Population, total, dtype: float64
0.0
10086    45870700.0
Name: Population, total, dtype: float64
106.14162297829554
6754    3562045.0
Name: Population, total, dtype: float64
109.99161773034507
678    142849449.0
Name: Population, total, dtype: float64
158.8558448278203
5725    5447900.0
Name: Population, total, dtype: float64
46.02825152653636
7489    2070739.0
Name: Population, total, dtype: float64
167.9344710929572
8518    7291436.0
Name: Population, total, dtype: float64
129.07828134468446
1070    2913021.0
Name: Population, total, dtype: float64
39.19836379886087
5431    16321872.0
Name: Population, total, dtype: float64
76.90165083492614
1364    2877311.0
Name: Population, total, dtype: float64
24.51104631074005
1756    9490583.0
Name: Population, total, dtype: float64
190.55001011649478
6411    364511.0
Name: Population, total, dtype: float64
15.261230821464485
2001    727641.0
Name: Population, total, dtype: float64
30.52994887851167
335    1.230981e+09
Name: Population, total, dtype: float64
8.497674873707583
1021    28803167.0
Name: Population, total, dtype: float64
20.60066466698271
1658    152149102.0
Name: Population, total, dtype: float64
6.489396944042575
7195    27023137.0
Name: Population, total, dtype: float64
9.783513374556891
7685    170560182.0
Name: Population, total, dtype: float64
9.5888886635907
9057    20198353.0
Name: Population, total, dtype: float64
7.9793123203075025
2491    14308740.0
Name: Population, total, dtype: float64
16.619239091453903
5774    6246274.0
Name: Population, total, dtype: float64
6.933104476074287
384    242524123.0
Name: Population, total, dtype: float64
6.064792816652228
10380    88472512.0
Name: Population, total, dtype: float64
8.689361640423261
4353    24512104.0
Name: Population, total, dtype: float64
24.500807923932427
5921    2040551.0
Name: Population, total, dtype: float64
1.958000140019402
7097    2173170.0
Name: Population, total, dtype: float64
13.100274176457747
3912    1202843.0
Name: Population, total, dtype: float64
0.2335613113524606
8959    51584663.0
Name: Population, total, dtype: float64
4.351448030868955
3961    87702670.0
Name: Population, total, dtype: float64
0.1151869103102278
4255    1692149.0
Name: Population, total, dtype: float64
25.942725076449488
6656    1250400.0
Name: Population, total, dtype: float64
65.17146575524109
6999    24221405.0
Name: Population, total, dtype: float64
16.5727835357689
5970    3948125.0
Name: Population, total, dtype: float64
47.001440616325525
5480    41350152.0
Name: Population, total, dtype: float64
6.296294528537402
2442    502384.0
Name: Population, total, dtype: float64
93.07887068419585
7440    158578261.0
Name: Population, total, dtype: float64
20.236365334516606
6313    15167095.0
Name: Population, total, dtype: float64
7.823709950569614
6607    3609543.0
Name: Population, total, dtype: float64
16.280040212388364
1903    9199259.0
Name: Population, total, dtype: float64
35.498056614781085
2344    15605217.0
Name: Population, total, dtype: float64
2.6185300027717497
3128    20401331.0
Name: Population, total, dtype: float64
36.975086467494506
2540    19970495.0
Name: Population, total, dtype: float64
18.80405578318523
3030    4386693.0
Name: Population, total, dtype: float64
79.44452981560251
4206    1640210.0
Name: Population, total, dtype: float64
63.840767006525894
6460    15075085.0
Name: Population, total, dtype: float64
8.572971792550463
7391    16425578.0
Name: Population, total, dtype: float64
0.435450820293929
9694    6502952.0
Name: Population, total, dtype: float64
6.726318702476901
8469    12916229.0
Name: Population, total, dtype: float64
46.550322007792076
2736    11887202.0
Name: Population, total, dtype: float64
8.478973003622274
8273    10246842.0
Name: Population, total, dtype: float64
3.6813958110279645
2981    64523263.0
Name: Population, total, dtype: float64
9.447333375135903
2393    8766930.0
Name: Population, total, dtype: float64
4.652268583492377
9547    46098591.0
Name: Population, total, dtype: float64
9.81247395061387
6264    21151640.0
Name: Population, total, dtype: float64
6.937495811711802
10037    33915133.0
Name: Population, total, dtype: float64
9.150811011499664
8616    6458720.0
Name: Population, total, dtype: float64
32.50345035909666
10576    13850033.0
Name: Population, total, dtype: float64
12.720008570075557
4696    10794170.0
Name: Population, total, dtype: float64
24.96251512133901
8420    174776.0
Name: Population, total, dtype: float64
417.84287915370436
9645    1109591.0
Name: Population, total, dtype: float64
18.478825065317626
4059    859950.0
Name: Population, total, dtype: float64
32.899858013411546
7832    7108239.0
Name: Population, total, dtype: float64
82.99327192640793
188    1.337705e+09
Name: Population, total, dtype: float64
38.34135995834427
9596    67208808.0
Name: Population, total, dtype: float64
86.05335984056715
7979    93726624.0
Name: Population, total, dtype: float64
55.82543237703297
6852    2712650.0
Name: Population, total, dtype: float64
0.5200560793140065
2491    14308740.0
Name: Population, total, dtype: float64
93.02533197619795
5774    6246274.0
Name: Population, total, dtype: float64
72.1974609914658
384    242524123.0
Name: Population, total, dtype: float64
36.88318153106259
10380    88472512.0
Name: Population, total, dtype: float64
58.6885088612591
5823    2097555.0
Name: Population, total, dtype: float64
30.918702464234993
6901    619428.0
Name: Population, total, dtype: float64
38.67141947193404
1511    9054332.0
Name: Population, total, dtype: float64
17.98943532686596
2295    7395599.0
Name: Population, total, dtype: float64
26.283567383914733
2099    3722084.0
Name: Population, total, dtype: float64
55.07891297792297
874    72326914.0
Name: Population, total, dtype: float64

13.803141500371419
6117    3097282.0
Name: Population, total, dtype: float64
48.41278971666604
8224    20246871.0
Name: Population, total, dtype: float64
41.41332744042993
9498    7641630.0
Name: Population, total, dtype: float64
2.1077385220150435
10086    45870700.0
Name: Population, total, dtype: float64
99.08259673896659
6754    3562045.0
Name: Population, total, dtype: float64
52.38953495291695
678    142849449.0
Name: Population, total, dtype: float64
67.15299384562546
5725    5447900.0
Name: Population, total, dtype: float64
4.980518986277792
7489    2070739.0
Name: Population, total, dtype: float64
50.649025887302
8518    7291436.0
Name: Population, total, dtype: float64
22.89447926114973
1070    2913021.0
Name: Population, total, dtype: float64
86.8321206560836
5431    16321872.0
Name: Population, total, dtype: float64
29.82911572088342
1364    2877311.0
Name: Population, total, dtype: float64
8.243643891774989
1756    9490583.0
Name: Population, total, dtype: float64
67.92046870301918
6411    364511.0
Name: Population, total, dtype: float64
23.16303817451105
2001    727641.0
Name: Population, total, dtype: float64
10.299204116816602
335    1.230981e+09
Name: Population, total, dtype: float64
0.07250529685063505
1021    28803167.0
Name: Population, total, dtype: float64
1.7298558659187133
1658    152149102.0
Name: Population, total, dtype: float64
60.10305228323353
7195    27023137.0
Name: Population, total, dtype: float64
11.195257794980828
7685    170560182.0
Name: Population, total, dtype: float64
2.028881865962198
9057    20198353.0
Name: Population, total, dtype: float64
63.53707303237085
3716    6164626.0
Name: Population, total, dtype: float64
10.603686587667774
139    196796269.0
Name: Population, total, dtype: float64
15.343320617295598
7930    29373646.0
Name: Population, total, dtype: float64
34.150795476659496
2050    9918242.0
Name: Population, total, dtype: float64
13.442894507011953
4647    14630417.0
Name: Population, total, dtype: float64
9.155774244755175
580    117318941.0
Name: Population, total, dtype: float64
7.0805464056354
4892    8194778.0
Name: Population, total, dtype: float64
13.912328246194352
7342    5737723.0
Name: Population, total, dtype: float64
1.5191451344246498
5333    2817210.0
Name: Population, total, dtype: float64
54.342243080056804
2883    45918097.0
Name: Population, total, dtype: float64
26.40414675033817
5382    7182390.0
Name: Population, total, dtype: float64
11.513129006856326
5137    30762701.0
Name: Population, total, dtype: float64
27.948196574934254
3667    84107606.0
Name: Population, total, dtype: float64
32.74448632993685
6950    32409639.0
Name: Population, total, dtype: float64
13.366141285494098
3471    851146.0
Name: Population, total, dtype: float64
26.489901490718715
10527    23606779.0
Name: Population, total, dtype: float64
19.343389782944634
4353    24512104.0
Name: Population, total, dtype: float64
86.50453187952554
5921    2040551.0
Name: Population, total, dtype: float64
2.3293477072295055
7097    2173170.0
Name: Population, total, dtype: float64
3.5421554794187307
9645    1109591.0
Name: Population, total, dtype: float64
2.882320430207686
4059    859950.0
Name: Population, total, dtype: float64
24.884194590165954
7832    7108239.0
Name: Population, total, dtype: float64
71.601102385326
188    1.337705e+09
Name: Population, total, dtype: float64
20.35568123618237
9596    67208808.0
Name: Population, total, dtype: float64
15.241326651090167
7979    93726624.0
Name: Population, total, dtype: float64
14.036352963258409
6852    2712650.0
Name: Population, total, dtype: float64
0.35824908623403967
2491    14308740.0
Name: Population, total, dtype: float64
23.794145643981587
5774    6246274.0
Name: Population, total, dtype: float64
8.301201250856494
384    242524123.0
Name: Population, total, dtype: float64
9.544571926307595
10380    88472512.0
Name: Population, total, dtype: float64
3.954536536715374
5823    2097555.0
Name: Population, total, dtype: float64
38.11626986667401
6901    619428.0
Name: Population, total, dtype: float64
11.54813686882118
1511    9054332.0
Name: Population, total, dtype: float64
2.0661906044455147
2295    7395599.0
Name: Population, total, dtype: float64
3.3561577407148158
2099    3722084.0
Name: Population, total, dtype: float64
16.541316328628525
874    72326914.0
Name: Population, total, dtype: float64
0.2984471800967386
6117    3097282.0
Name: Population, total, dtype: float64
24.515028812362228
8224    20246871.0
Name: Population, total, dtype: float64
4.260190508428413
9498    7641630.0
Name: Population, total, dtype: float64
0.398355371398195
10086    45870700.0
Name: Population, total, dtype: float64
44.744483616238355
6754    3562045.0
Name: Population, total, dtype: float64
24.599129534603875
678    142849449.0
Name: Population, total, dtype: float64
57.47169722321632
5725    5447900.0
Name: Population, total, dtype: float64
2.1071426619368707
7489    2070739.0
Name: Population, total, dtype: float64
0.0
8518    7291436.0
Name: Population, total, dtype: float64
41.09724662437182
1070    2913021.0
Name: Population, total, dtype: float64
3.7758732459554007
5431    16321872.0
Name: Population, total, dtype: float64
8.353693331519146
1364    2877311.0
Name: Population, total, dtype: float64
2.2206704313284047
1756    9490583.0
Name: Population, total, dtype: float64
40.17442923550906
6411    364511.0
Name: Population, total, dtype: float64
26.99609449135242
2001    727641.0
Name: Population, total, dtype: float64
14.778814583160582
335    1.230981e+09
Name: Population, total, dtype: float64
8.36317651105029
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
4.109460870250553
7195    27023137.0
Name: Population, total, dtype: float64
1.1057044032843406
7685    170560182.0
Name: Population, total, dtype: float64
0.7001335987545874
9057    20198353.0
Name: Population, total, dtype: float64
39.49129232791888
3912    1202843.0
Name: Population, total, dtype: float64
3.46395067025643
8959    51584663.0
Name: Population, total, dtype: float64
7.257258259489464
3961    87702670.0
Name: Population, total, dtype: float64
0.08044011695250707
4255    1692149.0
Name: Population, total, dtype: float64
15.305534332128525
6656    1250400.0
Name: Population, total, dtype: float64
24.31804119491495
6999    24221405.0
Name: Population, total, dtype: float64
10.748099376471693
5970    3948125.0
Name: Population, total, dtype: float64
13.284163835045996
5480    41350152.0
Name: Population, total, dtype: float64
3.7682816023185675
2442    502384.0
Name: Population, total, dtype: float64
19.14762536490347
7440    158578261.0
Name: Population, total, dtype: float64
11.821542505304079
6313    15167095.0
Name: Population, total, dtype: float64
16.72207097882784
6607    3609543.0
Name: Population, total, dtype: float64
3.0452969170774282
1903    9199259.0
Name: Population, total, dtype: float64
8.131175077440298
2344    15605217.0
Name: Population, total, dtype: float64
7.084371257967041
3128    20401331.0
Name: Population, total, dtype: float64
30.894387317061955
2540    19970495.0
Name: Population, total, dtype: float64
14.754815192029675
3030    4386693.0
Name: Population, total, dtype: float64
85.11385568531874
4206    1640210.0
Name: Population, total, dtype: float64
26.1511306946269
6460    15075085.0
Name: Population, total, dtype: float64
9.173537649706802
7391    16425578.0
Name: Population, total, dtype: float64
0.9091950512405572
9694    6502952.0
Name: Population, total, dtype: float64
20.08501572698774
8469    12916229.0
Name: Population, total, dtype: float64
9.619983169065499
2736    11887202.0
Name: Population, total, dtype: float64
14.913753736931461
8273    10246842.0
Name: Population, total, dtype: float64
0.3841932936646555
2981    64523263.0
Name: Population, total, dtype: float64
17.592449037722144
2393    8766930.0
Name: Population, total, dtype: float64
3.076168791613581
9547    46098591.0
Name: Population, total, dtype: float64
15.794715171972268
6264    21151640.0
Name: Population, total, dtype: float64
4.171614021453995
10037    33915133.0
Name: Population, total, dtype: float64
7.847378430492158
8616    6458720.0
Name: Population, total, dtype: float64
62.994755459308074
10576    13850033.0
Name: Population, total, dtype: float64
12.948229390214744
4696    10794170.0
Name: Population, total, dtype: float64
24.440697185003188
8420    174776.0
Name: Population, total, dtype: float64
136.64424362616214
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
2.0744499920097934
7930    29373646.0
Name: Population, total, dtype: float64
13.188199427802816
2050    9918242.0
Name: Population, total, dtype: float64
9.67332060541796
4647    14630417.0
Name: Population, total, dtype: float64
2.3633543710333513
580    117318941.0
Name: Population, total, dtype: float64
9.443544985775937
4892    8194778.0
Name: Population, total, dtype: float64
1.758615551587473
7342    5737723.0
Name: Population, total, dtype: float64
2.9925134732421887
5333    2817210.0
Name: Population, total, dtype: float64
41.37881638347736
2883    45918097.0
Name: Population, total, dtype: float64
0.0
5382    7182390.0
Name: Population, total, dtype: float64
4.9870734216865396
5137    30762701.0
Name: Population, total, dtype: float64
0.5760651225214066
3667    84107606.0
Name: Population, total, dtype: float64
3.8222733828820985
6950    32409639.0
Name: Population, total, dtype: float64
12.121407944484966
3471    851146.0
Name: Population, total, dtype: float64
6.668786293104602
10527    23606779.0
Name: Population, total, dtype: float64
9.643705152240791
5823    2097555.0
Name: Population, total, dtype: float64
84.59358386722278
6901    619428.0
Name: Population, total, dtype: float64
96.79786098446355
1511    9054332.0
Name: Population, total, dtype: float64
68.67850986619558
2295    7395599.0
Name: Population, total, dtype: float64
86.77241337893305
2099    3722084.0
Name: Population, total, dtype: float64
160.1977766633023
874    72326914.0
Name: Population, total, dtype: float64
82.62437356685324
6117    3097282.0
Name: Population, total, dtype: float64
61.16910312014326
8224    20246871.0
Name: Population, total, dtype: float64
93.90167659030475
9498    7641630.0
Name: Population, total, dtype: float64
73.67159416426537
10086    45870700.0
Name: Population, total, dtype: float64

140.7754425732654
6754    3562045.0
Name: Population, total, dtype: float64
32.74320509537881
678    142849449.0
Name: Population, total, dtype: float64
144.4908487611077
5725    5447900.0
Name: Population, total, dtype: float64
45.19982120091119
7489    2070739.0
Name: Population, total, dtype: float64
101.39131214027255
8518    7291436.0
Name: Population, total, dtype: float64
209.1964230142059
1070    2913021.0
Name: Population, total, dtype: float64
225.62388721912137
5431    16321872.0
Name: Population, total, dtype: float64
61.4703436835812
1364    2877311.0
Name: Population, total, dtype: float64
37.384812487886386
1756    9490583.0
Name: Population, total, dtype: float64
130.2980208073001
6411    364511.0
Name: Population, total, dtype: float64
33.88493377854012
2001    727641.0
Name: Population, total, dtype: float64
32.61128622627645
335    1.230981e+09
Name: Population, total, dtype: float64
12.470603959889736
1021    28803167.0
Name: Population, total, dtype: float64
47.81918095138456
1658    152149102.0
Name: Population, total, dtype: float64
18.62128842429419
7195    27023137.0
Name: Population, total, dtype: float64
18.629695496487763
7685    170560182.0
Name: Population, total, dtype: float64
17.523372960748517
9057    20198353.0
Name: Population, total, dtype: float64
26.03643119330889
9645    1109591.0
Name: Population, total, dtype: float64
16.952401899683025
4059    859950.0
Name: Population, total, dtype: float64
13.883710282197104
7832    7108239.0
Name: Population, total, dtype: float64
187.3988526065403
188    1.337705e+09
Name: Population, total, dtype: float64
48.775746344159295
9596    67208808.0
Name: Population, total, dtype: float64
65.3766567129817
7979    93726624.0
Name: Population, total, dtype: float64
21.255616473160956
6852    2712650.0
Name: Population, total, dtype: float64
11.239966028760607
2491    14308740.0
Name: Population, total, dtype: float64
30.49099418931541
5774    6246274.0
Name: Population, total, dtype: float64
17.58453101094669
384    242524123.0
Name: Population, total, dtype: float64
25.22424129791748
10380    88472512.0
Name: Population, total, dtype: float64
20.54885061381207
4353    24512104.0
Name: Population, total, dtype: float64
40.84018110851275
5921    2040551.0
Name: Population, total, dtype: float64
7.060692504002033
7097    2173170.0
Name: Population, total, dtype: float64
6.930466931291954
3912    1202843.0
Name: Population, total, dtype: float64
6.486568821843985
8959    51584663.0
Name: Population, total, dtype: float64
10.944343335638452
3961    87702670.0
Name: Population, total, dtype: float64
2.2401857846891637
4255    1692149.0
Name: Population, total, dtype: float64
9.819321539021027
6656    1250400.0
Name: Population, total, dtype: float64
37.36494681123661
6999    24221405.0
Name: Population, total, dtype: float64
3.475888837015716
5970    3948125.0
Name: Population, total, dtype: float64
16.24770344895023
5480    41350152.0
Name: Population, total, dtype: float64
26.816670310350467
2442    502384.0
Name: Population, total, dtype: float64
50.514059833484225
7440    158578261.0
Name: Population, total, dtype: float64
8.746756739481699
6313    15167095.0
Name: Population, total, dtype: float64
16.051142274978297
6607    3609543.0
Name: Population, total, dtype: float64
5.04010011759543
1903    9199259.0
Name: Population, total, dtype: float64
4.445253279400949
2344    15605217.0
Name: Population, total, dtype: float64
0.8900314117249707
3128    20401331.0
Name: Population, total, dtype: float64
33.53450391579068
2540    19970495.0
Name: Population, total, dtype: float64
0.023462920385264166
3030    4386693.0
Name: Population, total, dtype: float64
4.23969202153457
4206    1640210.0
Name: Population, total, dtype: float64
26.20284493568418
6460    15075085.0
Name: Population, total, dtype: float64
10.006061112325762
7391    16425578.0
Name: Population, total, dtype: float64
0.7521954938909887
9694    6502952.0
Name: Population, total, dtype: float64
6.361764182680404
8469    12916229.0
Name: Population, total, dtype: float64
8.597556506401647
2736    11887202.0
Name: Population, total, dtype: float64
6.457899669152169
8273    10246842.0
Name: Population, total, dtype: float64
6.672268762207167
2981    64523263.0
Name: Population, total, dtype: float64
1.6541495846408825
2393    8766930.0
Name: Population, total, dtype: float64
11.844115274026516
9547    46098591.0
Name: Population, total, dtype: float64
8.690652799393213
6264    21151640.0
Name: Population, total, dtype: float64
3.6403954113966837
10037    33915133.0
Name: Population, total, dtype: float64
11.525896279839333
8616    6458720.0
Name: Population, total, dtype: float64
19.861146695915593
10576    13850033.0
Name: Population, total, dtype: float64
7.680828793472674
4696    10794170.0
Name: Population, total, dtype: float64
18.444865469275673
8420    174776.0
Name: Population, total, dtype: float64
257.4027233620509
3716    6164626.0
Name: Population, total, dtype: float64
20.154585852541903
139    196796269.0
Name: Population, total, dtype: float64
33.59324982684604
7930    29373646.0
Name: Population, total, dtype: float64
72.96044419007113
2050    9918242.0
Name: Population, total, dtype: float64
74.49971152447675
4647    14630417.0
Name: Population, total, dtype: float64
61.67165988697938
580    117318941.0
Name: Population, total, dtype: float64
26.107252980033675
4892    8194778.0
Name: Population, total, dtype: float64
49.435806009418826
7342    5737723.0
Name: Population, total, dtype: float64
10.05476816829211
5333    2817210.0
Name: Population, total, dtype: float64
59.078446232027666
2883    45918097.0
Name: Population, total, dtype: float64
77.92899076493833
5382    7182390.0
Name: Population, total, dtype: float64
66.12695849101625
5137    30762701.0
Name: Population, total, dtype: float64
61.306824762474626
3667    84107606.0
Name: Population, total, dtype: float64
31.46459976612021
6950    32409639.0
Name: Population, total, dtype: float64
53.53139021352157
3471    851146.0
Name: Population, total, dtype: float64
29.405680894684263
10527    23606779.0
Name: Population, total, dtype: float64
36.9329201915154
4353    24512104.0
Name: Population, total, dtype: float64
2.972574023280124
5921    2040551.0
Name: Population, total, dtype: float64
1.4533122689651623
7097    2173170.0
Name: Population, total, dtype: float64
42.09702946437298
3912    1202843.0
Name: Population, total, dtype: float64
15.158743290974993
8959    51584663.0
Name: Population, total, dtype: float64
491.7824307642342
3961    87702670.0
Name: Population, total, dtype: float64
0.05797449008494825
4255    1692149.0
Name: Population, total, dtype: float64
0.060889182950865116
6656    1250400.0
Name: Population, total, dtype: float64
23.52044094845353
6999    24221405.0
Name: Population, total, dtype: float64
15.600548187491661
5970    3948125.0
Name: Population, total, dtype: float64
0.9735580039375936
5480    41350152.0
Name: Population, total, dtype: float64
0.2583872980685487
2442    502384.0
Name: Population, total, dtype: float64
9.940032086681406
7440    158578261.0
Name: Population, total, dtype: float64
0.17625005748904166
6313    15167095.0
Name: Population, total, dtype: float64
0.4782972830610377
6607    3609543.0
Name: Population, total, dtype: float64
0.0
9645    1109591.0
Name: Population, total, dtype: float64
0.0
4059    859950.0
Name: Population, total, dtype: float64
77.18920015877387
7832    7108239.0
Name: Population, total, dtype: float64
3.731282705885382
188    1.337705e+09
Name: Population, total, dtype: float64
9.028145826634237
9596    67208808.0
Name: Population, total, dtype: float64
9.975184898613186
7979    93726624.0
Name: Population, total, dtype: float64
24.623524441950327
6852    2712650.0
Name: Population, total, dtype: float64
11.372224581433892
2491    14308740.0
Name: Population, total, dtype: float64
0.0
5774    6246274.0
Name: Population, total, dtype: float64
0.13397114199484106
384    242524123.0
Name: Population, total, dtype: float64
2.542363537232149
10380    88472512.0
Name: Population, total, dtype: float64
7.869685649334186
3716    6164626.0
Name: Population, total, dtype: float64
0.6942093685938
139    196796269.0
Name: Population, total, dtype: float64
0.8780437773481946
7930    29373646.0
Name: Population, total, dtype: float64
0.0
2050    9918242.0
Name: Population, total, dtype: float64
2.298885365934196
4647    14630417.0
Name: Population, total, dtype: float64
45.65711879308059
580    117318941.0
Name: Population, total, dtype: float64
12.779315092250275
4892    8194778.0
Name: Population, total, dtype: float64
4.105634030928806
7342    5737723.0
Name: Population, total, dtype: float64
0.578481754450645
5333    2817210.0
Name: Population, total, dtype: float64
68.44797018110991
2883    45918097.0
Name: Population, total, dtype: float64
146.31067900968478
5382    7182390.0
Name: Population, total, dtype: float64
6.94829243767277
5137    30762701.0
Name: Population, total, dtype: float64
0.09651886186938063
3667    84107606.0
Name: Population, total, dtype: float64
0.4173133541378808
6950    32409639.0
Name: Population, total, dtype: float64
31.84551734780326
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
0.4306340894557947
3128    20401331.0
Name: Population, total, dtype: float64
0.8519060270802316
2540    19970495.0
Name: Population, total, dtype: float64

1.4607851147599673
3030    4386693.0
Name: Population, total, dtype: float64
0.6345884197161616
4206    1640210.0
Name: Population, total, dtype: float64
17.959613225306075
6460    15075085.0
Name: Population, total, dtype: float64
0.85242091905292
7391    16425578.0
Name: Population, total, dtype: float64
0.42061319983065304
9694    6502952.0
Name: Population, total, dtype: float64
0.6429236652419319
8469    12916229.0
Name: Population, total, dtype: float64
0.0
2736    11887202.0
Name: Population, total, dtype: float64
0.0007194017843013256
8273    10246842.0
Name: Population, total, dtype: float64
1.5065343525260182
2981    64523263.0
Name: Population, total, dtype: float64
0.004248349037558936
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
0.6901750070393017
6264    21151640.0
Name: Population, total, dtype: float64
0.00013891928392869248
10037    33915133.0
Name: Population, total, dtype: float64
0.20688646389641485
8616    6458720.0
Name: Population, total, dtype: float64
0.16247479575690016
10576    13850033.0
Name: Population, total, dtype: float64
0.0
4696    10794170.0
Name: Population, total, dtype: float64
0.1574534721160088
8420    174776.0
Name: Population, total, dtype: float64
0.0
5823    2097555.0
Name: Population, total, dtype: float64
102.47369096252064
6901    619428.0
Name: Population, total, dtype: float64
7.625779594872305
1511    9054332.0
Name: Population, total, dtype: float64
0.0
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
140.1711061355802
874    72326914.0
Name: Population, total, dtype: float64
6.1951547435656
6117    3097282.0
Name: Population, total, dtype: float64
22.708234386193954
8224    20246871.0
Name: Population, total, dtype: float64
12.461912785139653
9498    7641630.0
Name: Population, total, dtype: float64
1.5510770969800611
10086    45870700.0
Name: Population, total, dtype: float64
0.0
6754    3562045.0
Name: Population, total, dtype: float64
1.7616341898658694
678    142849449.0
Name: Population, total, dtype: float64
47.073267681470554
5725    5447900.0
Name: Population, total, dtype: float64
0.024984913585147723
7489    2070739.0
Name: Population, total, dtype: float64
0.6858563277344749
8518    7291436.0
Name: Population, total, dtype: float64
42.61055743576697
1070    2913021.0
Name: Population, total, dtype: float64
7.642285066306946
5431    16321872.0
Name: Population, total, dtype: float64
0.024082989447038267
1364    2877311.0
Name: Population, total, dtype: float64
0.0
1756    9490583.0
Name: Population, total, dtype: float64
44.66526635131962
6411    364511.0
Name: Population, total, dtype: float64
0.3329877707174017
2001    727641.0
Name: Population, total, dtype: float64
8.339138387202366
335    1.230981e+09
Name: Population, total, dtype: float64
0.32997841103885517
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
1.7166794564848629
7195    27023137.0
Name: Population, total, dtype: float64
6.991183185761755
7685    170560182.0
Name: Population, total, dtype: float64
0.7302016824501598
9057    20198353.0
Name: Population, total, dtype: float64
7.349500174365039
4353    24512104.0
Name: Population, total, dtype: float64
44.939008928078195
5921    2040551.0
Name: Population, total, dtype: float64
11.440811404847926
7097    2173170.0
Name: Population, total, dtype: float64
6.815527918933986
3912    1202843.0
Name: Population, total, dtype: float64
13.25598269475681
8959    51584663.0
Name: Population, total, dtype: float64
17.528818067841424
3961    87702670.0
Name: Population, total, dtype: float64
0.7314677154657907
4255    1692149.0
Name: Population, total, dtype: float64
50.87570181464627
6656    1250400.0
Name: Population, total, dtype: float64
63.6276767840075
6999    24221405.0
Name: Population, total, dtype: float64
16.262464112001545
5970    3948125.0
Name: Population, total, dtype: float64
123.13516019569308
5480    41350152.0
Name: Population, total, dtype: float64
17.208490538223135
2442    502384.0
Name: Population, total, dtype: float64
106.03007742544455
7440    158578261.0
Name: Population, total, dtype: float64
37.82318899680002
6313    15167095.0
Name: Population, total, dtype: float64
12.678428307161179
6607    3609543.0
Name: Population, total, dtype: float64
119.0424837907109
1903    9199259.0
Name: Population, total, dtype: float64
23.52019986963598
2344    15605217.0
Name: Population, total, dtype: float64
17.19247583471176
3128    20401331.0
Name: Population, total, dtype: float64
96.6319678322653
2540    19970495.0
Name: Population, total, dtype: float64
15.125014134560926
3030    4386693.0
Name: Population, total, dtype: float64
33.19843725027049
4206    1640210.0
Name: Population, total, dtype: float64
54.69567515361423
6460    15075085.0
Name: Population, total, dtype: float64
62.039211960486654
7391    16425578.0
Name: Population, total, dtype: float64
26.85572038069776
9694    6502952.0
Name: Population, total, dtype: float64
20.397973055577545
8469    12916229.0
Name: Population, total, dtype: float64
77.63032317281015
2736    11887202.0
Name: Population, total, dtype: float64
23.578491312389303
8273    10246842.0
Name: Population, total, dtype: float64
11.153230251605226
2981    64523263.0
Name: Population, total, dtype: float64
9.177983939799997
2393    8766930.0
Name: Population, total, dtype: float64
10.358168176038212
9547    46098591.0
Name: Population, total, dtype: float64
33.32995834228054
6264    21151640.0
Name: Population, total, dtype: float64
72.57514615721475
10037    33915133.0
Name: Population, total, dtype: float64
13.080576739608318
8616    6458720.0
Name: Population, total, dtype: float64
176.66020234365294
10576    13850033.0
Name: Population, total, dtype: float64
7.4137853112493675
4696    10794170.0
Name: Population, total, dtype: float64
163.06012316428678
8420    174776.0
Name: Population, total, dtype: float64
251.3986313144576
5823    2097555.0
Name: Population, total, dtype: float64
7.857488606665415
6901    619428.0
Name: Population, total, dtype: float64
4.810764407840516
1511    9054332.0
Name: Population, total, dtype: float64
15.941679708195736
2295    7395599.0
Name: Population, total, dtype: float64
13.472613426874052
2099    3722084.0
Name: Population, total, dtype: float64
16.388365924813776
874    72326914.0
Name: Population, total, dtype: float64
21.04312535104067
6117    3097282.0
Name: Population, total, dtype: float64
9.46136393930084
8224    20246871.0
Name: Population, total, dtype: float64
19.052367673476105
9498    7641630.0
Name: Population, total, dtype: float64
92.07813506017145
10086    45870700.0
Name: Population, total, dtype: float64
25.93556695312671
6754    3562045.0
Name: Population, total, dtype: float64
28.391528327946205
678    142849449.0
Name: Population, total, dtype: float64
14.83259072672574
5725    5447900.0
Name: Population, total, dtype: float64
2.561362027107827
7489    2070739.0
Name: Population, total, dtype: float64
40.334686451808004
8518    7291436.0
Name: Population, total, dtype: float64
12.05027677686036
1070    2913021.0
Name: Population, total, dtype: float64
53.88570667332539
5431    16321872.0
Name: Population, total, dtype: float64
35.27831807145165
1364    2877311.0
Name: Population, total, dtype: float64
11.129708202368692
1756    9490583.0
Name: Population, total, dtype: float64
7.089252019988936
6411    364511.0
Name: Population, total, dtype: float64
23.401770601115683
2001    727641.0
Name: Population, total, dtype: float64
110.42468142643806
335    1.230981e+09
Name: Population, total, dtype: float64
56.628653752977655
1021    28803167.0
Name: Population, total, dtype: float64
80.51480073303524
1658    152149102.0
Name: Population, total, dtype: float64
151.7943838573374
7195    27023137.0
Name: Population, total, dtype: float64
129.7689910363404
7685    170560182.0
Name: Population, total, dtype: float64
19.51131670253176
9057    20198353.0
Name: Population, total, dtype: float64
156.6050579973003
9645    1109591.0
Name: Population, total, dtype: float64
146.17873803828988
4059    859950.0
Name: Population, total, dtype: float64
41.03847455770658
7832    7108239.0
Name: Population, total, dtype: float64
292.2008371883239
188    1.337705e+09
Name: Population, total, dtype: float64
40.02189525825926
9596    67208808.0
Name: Population, total, dtype: float64
168.0208476338158
7979    93726624.0
Name: Population, total, dtype: float64
108.06007163500911
6852    2712650.0
Name: Population, total, dtype: float64
18.87346173015236
2491    14308740.0
Name: Population, total, dtype: float64
72.37787295949367
5774    6246274.0
Name: Population, total, dtype: float64
240.72944859865913
384    242524123.0
Name: Population, total, dtype: float64
92.32881764533514
10380    88472512.0
Name: Population, total, dtype: float64
144.28278053418157
3716    6164626.0
Name: Population, total, dtype: float64
19.70099249281441
139    196796269.0
Name: Population, total, dtype: float64
32.48993574435747
7930    29373646.0
Name: Population, total, dtype: float64
52.42756393433974
2050    9918242.0
Name: Population, total, dtype: float64
61.96287609506842
4647    14630417.0
Name: Population, total, dtype: float64
15.55964673579479
580    117318941.0
Name: Population, total, dtype: float64
10.113844047837881
4892    8194778.0
Name: Population, total, dtype: float64
25.889940328510033
7342    5737723.0
Name: Population, total, dtype: float64
22.27813394496228
5333    2817210.0
Name: Population, total, dtype: float64
22.655328912521945
2883    45918097.0
Name: Population, total, dtype: float64
86.73951098995785
5382    7182390.0
Name: Population, total, dtype: float64
45.2760766216083
5137    30762701.0
Name: Population, total, dtype: float64
27.525713814449535
3667    84107606.0
Name: Population, total, dtype: float64
24.526342100956594
6950    32409639.0
Name: Population, total, dtype: float64
6.086857971543561
3471    851146.0
Name: Population, total, dtype: float64
61.262478176941215
10527    23606779.0
Name: Population, total, dtype: float64
43.29949010746425
4353    24512104.0
Name: Population, total, dtype: float64
79.4015632099605
5921    2040551.0
Name: Population, total, dtype: float64
7.534269592643845
7097    2173170.0
Name: Population, total, dtype: float64
0.0
3912    1202843.0
Name: Population, total, dtype: float64
2.917412431988979
8959    51584663.0
Name: Population, total, dtype: float64
11.176670926753387
3961    87702670.0
Name: Population, total, dtype: float64
13.577896903993551
4255    1692149.0
Name: Population, total, dtype: float64
9.698407760243192
6656    1250400.0
Name: Population, total, dtype: float64
25.104461239376082
6999    24221405.0
Name: Population, total, dtype: float64
12.393460336865132
5970    3948125.0
Name: Population, total, dtype: float64
17.812619268766458
5480    41350152.0
Name: Population, total, dtype: float64
16.313582407725917
2442    502384.0
Name: Population, total, dtype: float64
46.601193880793964
7440    158578261.0
Name: Population, total, dtype: float64
49.74775988495751
6313    15167095.0
Name: Population, total, dtype: float64
18.988477560570377
6607    3609543.0
Name: Population, total, dtype: float64
2.6750284222878964
1903    9199259.0
Name: Population, total, dtype: float64
30.355186337419493
2344    15605217.0
Name: Population, total, dtype: float64
1.0580598191540667
3128    20401331.0
Name: Population, total, dtype: float64
65.07475541321222
2540    19970495.0
Name: Population, total, dtype: float64
24.673894839630513
3030    4386693.0
Name: Population, total, dtype: float64
57.64711469901208
4206    1640210.0
Name: Population, total, dtype: float64
123.22705769352
6460    15075085.0
Name: Population, total, dtype: float64
6.145303918171055
7391    16425578.0
Name: Population, total, dtype: float64
2.378041552293567
9694    6502952.0
Name: Population, total, dtype: float64
34.20341505989606
8469    12916229.0
Name: Population, total, dtype: float64
24.716217069661415
2736    11887202.0
Name: Population, total, dtype: float64
0.6985045398397958
8273    10246842.0
Name: Population, total, dtype: float64
48.067775630969805
2981    64523263.0
Name: Population, total, dtype: float64
35.30588847731045
5823    2097555.0
Name: Population, total, dtype: float64
44.38857860699719
6901    619428.0
Name: Population, total, dtype: float64
38.628693470174056
1511    9054332.0
Name: Population, total, dtype: float64
52.12712232776031
2295    7395599.0
Name: Population, total, dtype: float64
37.42369051352042
2099    3722084.0
Name: Population, total, dtype: float64
33.91539827291937
874    72326914.0
Name: Population, total, dtype: float64
18.44058751677773
6117    3097282.0
Name: Population, total, dtype: float64
45.61637667742959
8224    20246871.0
Name: Population, total, dtype: float64
34.52740181774385
9498    7641630.0
Name: Population, total, dtype: float64
57.79752464159486
10086    45870700.0
Name: Population, total, dtype: float64
133.91452867666212
6754    3562045.0
Name: Population, total, dtype: float64
48.809575215194215
678    142849449.0
Name: Population, total, dtype: float64
64.9232559595396
5725    5447900.0
Name: Population, total, dtype: float64
31.235899161443516
7489    2070739.0
Name: Population, total, dtype: float64
43.43391566556569
8518    7291436.0
Name: Population, total, dtype: float64
37.8394645503584
1070    2913021.0
Name: Population, total, dtype: float64
38.89861795303804
5431    16321872.0
Name: Population, total, dtype: float64
68.44635083345896
1364    2877311.0
Name: Population, total, dtype: float64
23.303629794171783
1756    9490583.0
Name: Population, total, dtype: float64
24.855866508378792
6411    364511.0
Name: Population, total, dtype: float64
2.1990722082590413
2001    727641.0
Name: Population, total, dtype: float64
16.195643746232484
335    1.230981e+09
Name: Population, total, dtype: float64
8.897118504451818
1021    28803167.0
Name: Population, total, dtype: float64
18.038204058220582
1658    152149102.0
Name: Population, total, dtype: float64
11.080499782306843
7195    27023137.0
Name: Population, total, dtype: float64
14.183027999577762
7685    170560182.0
Name: Population, total, dtype: float64
11.366737489030577
9057    20198353.0
Name: Population, total, dtype: float64
19.06202854183287
9645    1109591.0
Name: Population, total, dtype: float64
34.500363173976965
4059    859950.0
Name: Population, total, dtype: float64
29.393515270329463
7832    7108239.0
Name: Population, total, dtype: float64
364.9803964477427
188    1.337705e+09
Name: Population, total, dtype: float64
3.9702952506599165
9596    67208808.0
Name: Population, total, dtype: float64
0.13572755328600103
7979    93726624.0
Name: Population, total, dtype: float64
7.121569688157336
6852    2712650.0
Name: Population, total, dtype: float64
16.130384599928313
2491    14308740.0
Name: Population, total, dtype: float64
3.7642332711677966
5774    6246274.0
Name: Population, total, dtype: float64
0.5571314632949642
384    242524123.0
Name: Population, total, dtype: float64
4.490948787467237
10380    88472512.0
Name: Population, total, dtype: float64
2.1628470802203776
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
8.646923868094865
7930    29373646.0
Name: Population, total, dtype: float64
53.61449226503851
2050    9918242.0
Name: Population, total, dtype: float64
59.85716875553997
4647    14630417.0
Name: Population, total, dtype: float64
11.967301872627127
580    117318941.0
Name: Population, total, dtype: float64
8.39081607189865
4892    8194778.0
Name: Population, total, dtype: float64
9.663937439973132
7342    5737723.0
Name: Population, total, dtype: float64
3.9236093665131158
5333    2817210.0
Name: Population, total, dtype: float64
37.02504014649458
2883    45918097.0
Name: Population, total, dtype: float64
47.297144588940405
5382    7182390.0
Name: Population, total, dtype: float64
19.163573659255842
5137    30762701.0
Name: Population, total, dtype: float64
32.26007983779768
3667    84107606.0
Name: Population, total, dtype: float64
11.30749381943834
6950    32409639.0
Name: Population, total, dtype: float64
26.40307997943426
3471    851146.0
Name: Population, total, dtype: float64
39.467643736155416
10527    23606779.0
Name: Population, total, dtype: float64
20.425905738842513
2393    8766930.0
Name: Population, total, dtype: float64
67.41292871864991
9547    46098591.0
Name: Population, total, dtype: float64
14.55911622586019
6264    21151640.0
Name: Population, total, dtype: float64
9.588936240427765
10037    33915133.0
Name: Population, total, dtype: float64
77.79966946774566
8616    6458720.0
Name: Population, total, dtype: float64
41.273907170947396
10576    13850033.0
Name: Population, total, dtype: float64
7.393555759388511
4696    10794170.0
Name: Population, total, dtype: float64
23.535283840956613
8420    174776.0
Name: Population, total, dtype: float64
47.37073338486327
4353    24512104.0
Name: Population, total, dtype: float64
0.1639591892565035
5921    2040551.0
Name: Population, total, dtype: float64
1.497215720592783
7097    2173170.0
Name: Population, total, dtype: float64
0.2454993767928369
3912    1202843.0
Name: Population, total, dtype: float64
0.022372947560457674
8959    51584663.0
Name: Population, total, dtype: float64
0.31433237059301244
3961    87702670.0
Name: Population, total, dtype: float64
0.013545860123448642
4255    1692149.0
Name: Population, total, dtype: float64
1.3313655703726768
6656    1250400.0
Name: Population, total, dtype: float64
0.3133858967287916
6999    24221405.0
Name: Population, total, dtype: float64
0.09542871912985151
5970    3948125.0
Name: Population, total, dtype: float64
0.0
5480    41350152.0
Name: Population, total, dtype: float64
0.2168683808784219
2442    502384.0
Name: Population, total, dtype: float64
0.6867388552224866
7440    158578261.0
Name: Population, total, dtype: float64
10.664405886377242
6313    15167095.0
Name: Population, total, dtype: float64
1.9248023120109892
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
1.3431924063086669
3128    20401331.0
Name: Population, total, dtype: float64
0.925906673599113
2540    19970495.0
Name: Population, total, dtype: float64
0.5883127962072091
3030    4386693.0
Name: Population, total, dtype: float64
0.5330362400735389
4206    1640210.0
Name: Population, total, dtype: float64
1.431685817135029
6460    15075085.0
Name: Population, total, dtype: float64
0.0
7391    16425578.0
Name: Population, total, dtype: float64
0.22775489160267104
9694    6502952.0
Name: Population, total, dtype: float64
0.767263146406932
8469    12916229.0
Name: Population, total, dtype: float64
0.4271887830380791
2736    11887202.0
Name: Population, total, dtype: float64

0.0
8273    10246842.0
Name: Population, total, dtype: float64
1.9633465993304982
2981    64523263.0
Name: Population, total, dtype: float64
0.2512949638748036
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
1.2532996370961091
6264    21151640.0
Name: Population, total, dtype: float64
0.0006034855646542079
10037    33915133.0
Name: Population, total, dtype: float64
0.01839818839991214
8616    6458720.0
Name: Population, total, dtype: float64
0.36671994821208453
10576    13850033.0
Name: Population, total, dtype: float64
0.3223406392944178
4696    10794170.0
Name: Population, total, dtype: float64
0.011877744706308516
8420    174776.0
Name: Population, total, dtype: float64
17.32932929768495
5823    2097555.0
Name: Population, total, dtype: float64
2.155312956704125
6901    619428.0
Name: Population, total, dtype: float64
0.9106739778372978
1511    9054332.0
Name: Population, total, dtype: float64
1.9046803454037846
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
6.950064443090784
874    72326914.0
Name: Population, total, dtype: float64
1.245250296473994
6117    3097282.0
Name: Population, total, dtype: float64
1.1152981449989041
8224    20246871.0
Name: Population, total, dtype: float64
0.5163259436415597
9498    7641630.0
Name: Population, total, dtype: float64
0.0
10086    45870700.0
Name: Population, total, dtype: float64
0.009726080950837287
6754    3562045.0
Name: Population, total, dtype: float64
3.117537747749607
678    142849449.0
Name: Population, total, dtype: float64
3.090436761163301
5725    5447900.0
Name: Population, total, dtype: float64
1.1126304671611975
7489    2070739.0
Name: Population, total, dtype: float64
0.43474390173254523
8518    7291436.0
Name: Population, total, dtype: float64
3.4705333839980415
1070    2913021.0
Name: Population, total, dtype: float64
0.0
5431    16321872.0
Name: Population, total, dtype: float64
0.0
1364    2877311.0
Name: Population, total, dtype: float64
1.1312953615358115
1756    9490583.0
Name: Population, total, dtype: float64
8.669596177580775
6411    364511.0
Name: Population, total, dtype: float64
1.0879328578422154
2001    727641.0
Name: Population, total, dtype: float64
0.2108441276674395
335    1.230981e+09
Name: Population, total, dtype: float64
0.0
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
0.0
7195    27023137.0
Name: Population, total, dtype: float64
1.5640802597382677
7685    170560182.0
Name: Population, total, dtype: float64
0.4085532075710316
9057    20198353.0
Name: Population, total, dtype: float64
1.563428200067288
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
0.0
7930    29373646.0
Name: Population, total, dtype: float64
0.0
2050    9918242.0
Name: Population, total, dtype: float64
2.491160421634079
4647    14630417.0
Name: Population, total, dtype: float64
1.805620635087614
580    117318941.0
Name: Population, total, dtype: float64
0.0
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
0.5156821037118587
5333    2817210.0
Name: Population, total, dtype: float64
1.5401196343864516
2883    45918097.0
Name: Population, total, dtype: float64
3.4680052392533622
5382    7182390.0
Name: Population, total, dtype: float64
0.009386829944412926
5137    30762701.0
Name: Population, total, dtype: float64
1.391671438132604
3667    84107606.0
Name: Population, total, dtype: float64
0.7502227455432241
6950    32409639.0
Name: Population, total, dtype: float64
0.5268713713568627
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
1.5045121682728364
9645    1109591.0
Name: Population, total, dtype: float64
0.0
4059    859950.0
Name: Population, total, dtype: float64
0.1912376620137766
7832    7108239.0
Name: Population, total, dtype: float64
0.0
188    1.337705e+09
Name: Population, total, dtype: float64
12.219325483022251
9596    67208808.0
Name: Population, total, dtype: float64
1.1073890783809461
7979    93726624.0
Name: Population, total, dtype: float64
0.3030232889031826
6852    2712650.0
Name: Population, total, dtype: float64
0.20313824559588575
2491    14308740.0
Name: Population, total, dtype: float64
1.8969136061016447
5774    6246274.0
Name: Population, total, dtype: float64
0.8401889598971938
384    242524123.0
Name: Population, total, dtype: float64
0.0
10380    88472512.0
Name: Population, total, dtype: float64
0.5958021271521072
3716    6164626.0
Name: Population, total, dtype: float64
30.71292431931342
139    196796269.0
Name: Population, total, dtype: float64
41.1399512878669
7930    29373646.0
Name: Population, total, dtype: float64
104.20265793252464
2050    9918242.0
Name: Population, total, dtype: float64
103.1460978055247
4647    14630417.0
Name: Population, total, dtype: float64
51.42849175312923
580    117318941.0
Name: Population, total, dtype: float64
42.15567480478198
4892    8194778.0
Name: Population, total, dtype: float64
44.65115543970013
7342    5737723.0
Name: Population, total, dtype: float64
17.763637469941763
5333    2817210.0
Name: Population, total, dtype: float64
107.30454292407605
2883    45918097.0
Name: Population, total, dtype: float64
66.02328451437663
5382    7182390.0
Name: Population, total, dtype: float64
105.08989016505606
5137    30762701.0
Name: Population, total, dtype: float64
45.593929953040444
3667    84107606.0
Name: Population, total, dtype: float64
54.96499752789714
6950    32409639.0
Name: Population, total, dtype: float64
52.986089477527564
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
57.20646572799902
4353    24512104.0
Name: Population, total, dtype: float64
12.159237554988609
5921    2040551.0
Name: Population, total, dtype: float64
32.78989417753013
7097    2173170.0
Name: Population, total, dtype: float64
11.276890022631184
3912    1202843.0
Name: Population, total, dtype: float64
19.979855957358957
8959    51584663.0
Name: Population, total, dtype: float64
56.13172535575853
3961    87702670.0
Name: Population, total, dtype: float64
3.044315675940319
4255    1692149.0
Name: Population, total, dtype: float64
8.37620509584831
6656    1250400.0
Name: Population, total, dtype: float64
76.84553408367206
6999    24221405.0
Name: Population, total, dtype: float64
2.439009955556745
5970    3948125.0
Name: Population, total, dtype: float64
13.659543140752165
5480    41350152.0
Name: Population, total, dtype: float64
10.093639830872961
2442    502384.0
Name: Population, total, dtype: float64
61.317178255414234
7440    158578261.0
Name: Population, total, dtype: float64
3.2406524722100634
6313    15167095.0
Name: Population, total, dtype: float64
21.532389178548897
6607    3609543.0
Name: Population, total, dtype: float64
12.039605952551767
1903    9199259.0
Name: Population, total, dtype: float64
12.921592029041348
2344    15605217.0
Name: Population, total, dtype: float64
0.5254148914262718
3128    20401331.0
Name: Population, total, dtype: float64
11.794904371836843
2540    19970495.0
Name: Population, total, dtype: float64
4.192430104157207
3030    4386693.0
Name: Population, total, dtype: float64
35.93791452655558
4206    1640210.0
Name: Population, total, dtype: float64
84.52275175029942
6460    15075085.0
Name: Population, total, dtype: float64
4.886051123817398
7391    16425578.0
Name: Population, total, dtype: float64
1.1964366811077838
9694    6502952.0
Name: Population, total, dtype: float64
7.598044045843388
8469    12916229.0
Name: Population, total, dtype: float64
9.155937597609368
2736    11887202.0
Name: Population, total, dtype: float64
8.724523755987668
8273    10246842.0
Name: Population, total, dtype: float64
0.7363342080752825
2981    64523263.0
Name: Population, total, dtype: float64
4.374564868323394
2393    8766930.0
Name: Population, total, dtype: float64
1.2625750997946343
9547    46098591.0
Name: Population, total, dtype: float64
7.210997122625824
6264    21151640.0
Name: Population, total, dtype: float64
1.7003287912028227
10037    33915133.0
Name: Population, total, dtype: float64
11.381111842876178
8616    6458720.0
Name: Population, total, dtype: float64
14.600665841581595
10576    13850033.0
Name: Population, total, dtype: float64
17.877342831478312
4696    10794170.0
Name: Population, total, dtype: float64
6.258001610253216
8420    174776.0
Name: Population, total, dtype: float64
122.34841394017408
9645    1109591.0
Name: Population, total, dtype: float64
18.959739784405826
4059    859950.0
Name: Population, total, dtype: float64
50.466693817686334
7832    7108239.0
Name: Population, total, dtype: float64
101.57139547387712
188    1.337705e+09
Name: Population, total, dtype: float64
32.54585206859518
9596    67208808.0
Name: Population, total, dtype: float64
41.97216112322482
7979    93726624.0
Name: Population, total, dtype: float64
22.96272409219419
6852    2712650.0
Name: Population, total, dtype: float64
1.7543470799474925
2491    14308740.0
Name: Population, total, dtype: float64
17.404550834145333
5774    6246274.0
Name: Population, total, dtype: float64
26.186424292562982
384    242524123.0
Name: Population, total, dtype: float64
15.404416370526139
10380    88472512.0
Name: Population, total, dtype: float64
26.459383943437306
5823    2097555.0
Name: Population, total, dtype: float64
51.08563621675768
6901    619428.0
Name: Population, total, dtype: float64
52.25988271130652
1511    9054332.0
Name: Population, total, dtype: float64
50.7217083963197
2295    7395599.0
Name: Population, total, dtype: float64

65.08491691961936
2099    3722084.0
Name: Population, total, dtype: float64
78.65328946833803
874    72326914.0
Name: Population, total, dtype: float64
42.33124684520701
6117    3097282.0
Name: Population, total, dtype: float64
41.695698423655436
8224    20246871.0
Name: Population, total, dtype: float64
104.83715072317365
9498    7641630.0
Name: Population, total, dtype: float64
13.34772713775197
10086    45870700.0
Name: Population, total, dtype: float64
126.9668627884401
6754    3562045.0
Name: Population, total, dtype: float64
62.89538706978207
678    142849449.0
Name: Population, total, dtype: float64
121.43133317296002
5725    5447900.0
Name: Population, total, dtype: float64
11.606480480508935
7489    2070739.0
Name: Population, total, dtype: float64
82.22090659577368
8518    7291436.0
Name: Population, total, dtype: float64
115.72435779347862
1070    2913021.0
Name: Population, total, dtype: float64
90.84924270894635
5431    16321872.0
Name: Population, total, dtype: float64
52.92252464818137
1364    2877311.0
Name: Population, total, dtype: float64
35.17049482887169
1756    9490583.0
Name: Population, total, dtype: float64
137.974422670789
6411    364511.0
Name: Population, total, dtype: float64
0.037770408655238924
2001    727641.0
Name: Population, total, dtype: float64
6.104218777067672
335    1.230981e+09
Name: Population, total, dtype: float64
6.08737118633962
1021    28803167.0
Name: Population, total, dtype: float64
13.405465626581549
1658    152149102.0
Name: Population, total, dtype: float64
18.601276245155884
7195    27023137.0
Name: Population, total, dtype: float64
27.33589241656868
7685    170560182.0
Name: Population, total, dtype: float64
20.191302892835868
9057    20198353.0
Name: Population, total, dtype: float64
20.82670203838605
9645    1109591.0
Name: Population, total, dtype: float64
0.12618533483455327
4059    859950.0
Name: Population, total, dtype: float64
1.0344474224477478
7832    7108239.0
Name: Population, total, dtype: float64
112.77446639091364
188    1.337705e+09
Name: Population, total, dtype: float64
16.596398207306787
9596    67208808.0
Name: Population, total, dtype: float64
1.3057930187786804
7979    93726624.0
Name: Population, total, dtype: float64
5.774555810471878
6852    2712650.0
Name: Population, total, dtype: float64
5.647083281527364
2491    14308740.0
Name: Population, total, dtype: float64
11.853440033358103
5774    6246274.0
Name: Population, total, dtype: float64
6.35856458505987
384    242524123.0
Name: Population, total, dtype: float64
16.204494269558367
10380    88472512.0
Name: Population, total, dtype: float64
6.145273231881603
4353    24512104.0
Name: Population, total, dtype: float64
1.2067848612170573
5921    2040551.0
Name: Population, total, dtype: float64
7.125787181610456
7097    2173170.0
Name: Population, total, dtype: float64
3.533802639064283
3912    1202843.0
Name: Population, total, dtype: float64
4.948348864807247
8959    51584663.0
Name: Population, total, dtype: float64
0.6138694003502946
3961    87702670.0
Name: Population, total, dtype: float64
0.24972429114599629
4255    1692149.0
Name: Population, total, dtype: float64
1.0229815909988669
6656    1250400.0
Name: Population, total, dtype: float64
11.77569299283949
6999    24221405.0
Name: Population, total, dtype: float64
0.047818507342854796
5970    3948125.0
Name: Population, total, dtype: float64
0.7689808503352077
5480    41350152.0
Name: Population, total, dtype: float64
2.6057814988314196
2442    502384.0
Name: Population, total, dtype: float64
0.92784519494882
7440    158578261.0
Name: Population, total, dtype: float64
11.511379800382718
6313    15167095.0
Name: Population, total, dtype: float64
4.1461772698967305
6607    3609543.0
Name: Population, total, dtype: float64
8.146941014447885
1903    9199259.0
Name: Population, total, dtype: float64
3.6050795280054855
2344    15605217.0
Name: Population, total, dtype: float64
3.9608846627980725
3128    20401331.0
Name: Population, total, dtype: float64
7.581685021358139
2540    19970495.0
Name: Population, total, dtype: float64
5.137590012050636
3030    4386693.0
Name: Population, total, dtype: float64
18.776707373399777
4206    1640210.0
Name: Population, total, dtype: float64
6.31115728084702
6460    15075085.0
Name: Population, total, dtype: float64
0.29368713868535223
7391    16425578.0
Name: Population, total, dtype: float64
1.0182483179404902
9694    6502952.0
Name: Population, total, dtype: float64
1.7658564481055787
8469    12916229.0
Name: Population, total, dtype: float64
1.1903348422490545
2736    11887202.0
Name: Population, total, dtype: float64
2.434718187017883
8273    10246842.0
Name: Population, total, dtype: float64
2.6831189602570427
2981    64523263.0
Name: Population, total, dtype: float64
4.11246120730564
2393    8766930.0
Name: Population, total, dtype: float64
1.028927828787559
9547    46098591.0
Name: Population, total, dtype: float64
0.029827128465263513
6264    21151640.0
Name: Population, total, dtype: float64
0.1026620179349565
10037    33915133.0
Name: Population, total, dtype: float64
14.172798452520459
8616    6458720.0
Name: Population, total, dtype: float64
1.2085756781342725
10576    13850033.0
Name: Population, total, dtype: float64
0.34893350691626807
4696    10794170.0
Name: Population, total, dtype: float64
0.5279266463068971
8420    174776.0
Name: Population, total, dtype: float64
7.530194342148972
5823    2097555.0
Name: Population, total, dtype: float64
11.864137590862654
6901    619428.0
Name: Population, total, dtype: float64
1.4197750162413236
1511    9054332.0
Name: Population, total, dtype: float64
20.818790083397086
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
31.51319664973862
874    72326914.0
Name: Population, total, dtype: float64
7.502973011332127
6117    3097282.0
Name: Population, total, dtype: float64
12.57370557188926
8224    20246871.0
Name: Population, total, dtype: float64
8.142960314510663
9498    7641630.0
Name: Population, total, dtype: float64
20.549602878439764
10086    45870700.0
Name: Population, total, dtype: float64
36.72729168282406
6754    3562045.0
Name: Population, total, dtype: float64
33.89618297953194
678    142849449.0
Name: Population, total, dtype: float64
29.674179464908224
5725    5447900.0
Name: Population, total, dtype: float64
4.876066404612826
7489    2070739.0
Name: Population, total, dtype: float64
0.0
8518    7291436.0
Name: Population, total, dtype: float64
2.3838470481045833
1070    2913021.0
Name: Population, total, dtype: float64
0.0
5431    16321872.0
Name: Population, total, dtype: float64
6.741973429992183
1364    2877311.0
Name: Population, total, dtype: float64
49.53686237555612
1756    9490583.0
Name: Population, total, dtype: float64
2.837322447661925
6411    364511.0
Name: Population, total, dtype: float64
5.519481127052005
2001    727641.0
Name: Population, total, dtype: float64
3.095918983835822
335    1.230981e+09
Name: Population, total, dtype: float64
2.7770278619541413
1021    28803167.0
Name: Population, total, dtype: float64
3.0030231108984933
1658    152149102.0
Name: Population, total, dtype: float64
2.956106832028084
7195    27023137.0
Name: Population, total, dtype: float64
4.364699508666229
7685    170560182.0
Name: Population, total, dtype: float64
2.9224190032625725
9057    20198353.0
Name: Population, total, dtype: float64
5.409130076766669
3716    6164626.0
Name: Population, total, dtype: float64
19.747774088767688
139    196796269.0
Name: Population, total, dtype: float64
2.2714908834040166
7930    29373646.0
Name: Population, total, dtype: float64
19.569646746897234
2050    9918242.0
Name: Population, total, dtype: float64
5.701551950211187
4647    14630417.0
Name: Population, total, dtype: float64
18.511289541563094
580    117318941.0
Name: Population, total, dtype: float64
10.359220165128585
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
0.9642311536803981
5333    2817210.0
Name: Population, total, dtype: float64
7.497176103264149
2883    45918097.0
Name: Population, total, dtype: float64
57.94815701243399
5382    7182390.0
Name: Population, total, dtype: float64
17.27189609506953
5137    30762701.0
Name: Population, total, dtype: float64
11.036074784652556
3667    84107606.0
Name: Population, total, dtype: float64
14.98281223735131
6950    32409639.0
Name: Population, total, dtype: float64
7.080935183252433
3471    851146.0
Name: Population, total, dtype: float64
1.9604413038710076
10527    23606779.0
Name: Population, total, dtype: float64
16.220626238163042
4353    24512104.0
Name: Population, total, dtype: float64
15.183336387919292
5921    2040551.0
Name: Population, total, dtype: float64
8.388771547424241
7097    2173170.0
Name: Population, total, dtype: float64
5.331374403303743
3912    1202843.0
Name: Population, total, dtype: float64
6.461245184455973
8959    51584663.0
Name: Population, total, dtype: float64
13.547599653849897
3961    87702670.0
Name: Population, total, dtype: float64
4.995131010955545
4255    1692149.0
Name: Population, total, dtype: float64
11.469603100611623
6656    1250400.0
Name: Population, total, dtype: float64
86.828028407086
6999    24221405.0
Name: Population, total, dtype: float64
0.6325776088222855
5970    3948125.0
Name: Population, total, dtype: float64
2.7590002483429155
5480    41350152.0
Name: Population, total, dtype: float64
3.421642001614949
2442    502384.0
Name: Population, total, dtype: float64
126.46456018531127
7440    158578261.0
Name: Population, total, dtype: float64
5.447482204020425
6313    15167095.0
Name: Population, total, dtype: float64
3.4042130964924664
6607    3609543.0
Name: Population, total, dtype: float64
24.212654699564435
1903    9199259.0
Name: Population, total, dtype: float64
0.34421805177035464
2344    15605217.0
Name: Population, total, dtype: float64
1.5230332399285464
3128    20401331.0
Name: Population, total, dtype: float64
8.546356151842346
2540    19970495.0
Name: Population, total, dtype: float64
2.9715943213012763
3030    4386693.0
Name: Population, total, dtype: float64
9.958272004008206
4206    1640210.0
Name: Population, total, dtype: float64
29.18937129765041
6460    15075085.0
Name: Population, total, dtype: float64
5.955340974063941
7391    16425578.0
Name: Population, total, dtype: float64
1.3338193796350468
9694    6502952.0
Name: Population, total, dtype: float64
3.623055033741862
8469    12916229.0
Name: Population, total, dtype: float64
11.169067760417699
2736    11887202.0
Name: Population, total, dtype: float64
2.5753900848451767
8273    10246842.0
Name: Population, total, dtype: float64
2.5291577461642336
2981    64523263.0
Name: Population, total, dtype: float64
2.046765955455083
2393    8766930.0
Name: Population, total, dtype: float64
0.6699377016194338
9547    46098591.0
Name: Population, total, dtype: float64
1.8112810211937005
6264    21151640.0
Name: Population, total, dtype: float64
1.6043175460912347
10037    33915133.0
Name: Population, total, dtype: float64
0.0
8616    6458720.0
Name: Population, total, dtype: float64
9.15683494189691
10576    13850033.0
Name: Population, total, dtype: float64

0.7570655934243841
4696    10794170.0
Name: Population, total, dtype: float64
7.8663067712423445
8420    174776.0
Name: Population, total, dtype: float64
61.953308186959354
3716    6164626.0
Name: Population, total, dtype: float64
12.023997097018558
139    196796269.0
Name: Population, total, dtype: float64
51.31659975863509
7930    29373646.0
Name: Population, total, dtype: float64
64.37046660646777
2050    9918242.0
Name: Population, total, dtype: float64
38.78771143408697
4647    14630417.0
Name: Population, total, dtype: float64
37.128284717715786
580    117318941.0
Name: Population, total, dtype: float64
10.860773422561186
4892    8194778.0
Name: Population, total, dtype: float64
29.167212154022714
7342    5737723.0
Name: Population, total, dtype: float64
5.055296965120391
5333    2817210.0
Name: Population, total, dtype: float64
35.83822618098604
2883    45918097.0
Name: Population, total, dtype: float64
17.108117834206997
5382    7182390.0
Name: Population, total, dtype: float64
60.44532023115456
5137    30762701.0
Name: Population, total, dtype: float64
38.91450926522787
3667    84107606.0
Name: Population, total, dtype: float64
5.422367976440675
6950    32409639.0
Name: Population, total, dtype: float64
45.381207513291265
3471    851146.0
Name: Population, total, dtype: float64
42.523309014891076
10527    23606779.0
Name: Population, total, dtype: float64
61.06915241070887
9645    1109591.0
Name: Population, total, dtype: float64
6.4073655907630265
4059    859950.0
Name: Population, total, dtype: float64
21.27580277949624
7832    7108239.0
Name: Population, total, dtype: float64
9.992450381902477
188    1.337705e+09
Name: Population, total, dtype: float64
14.666405482196845
9596    67208808.0
Name: Population, total, dtype: float64
25.640328931681005
7979    93726624.0
Name: Population, total, dtype: float64
23.96400710843677
6852    2712650.0
Name: Population, total, dtype: float64
15.166765662933756
2491    14308740.0
Name: Population, total, dtype: float64
5.077789492203623
5774    6246274.0
Name: Population, total, dtype: float64
1.9886349969271966
384    242524123.0
Name: Population, total, dtype: float64
18.735270803688913
10380    88472512.0
Name: Population, total, dtype: float64
10.107392273885159
5823    2097555.0
Name: Population, total, dtype: float64
77.21586356199474
6901    619428.0
Name: Population, total, dtype: float64
85.01062056879242
1511    9054332.0
Name: Population, total, dtype: float64
21.23534095259467
2295    7395599.0
Name: Population, total, dtype: float64
85.61429052679468
2099    3722084.0
Name: Population, total, dtype: float64
76.59430051061545
874    72326914.0
Name: Population, total, dtype: float64
39.63167552586934
6117    3097282.0
Name: Population, total, dtype: float64
97.23702180552651
8224    20246871.0
Name: Population, total, dtype: float64
32.216615964577485
9498    7641630.0
Name: Population, total, dtype: float64
11.243552341507327
10086    45870700.0
Name: Population, total, dtype: float64
66.6803662378225
6754    3562045.0
Name: Population, total, dtype: float64
35.1812060355992
678    142849449.0
Name: Population, total, dtype: float64
109.09993923233496
5725    5447900.0
Name: Population, total, dtype: float64
25.377540739302827
7489    2070739.0
Name: Population, total, dtype: float64
58.12920540889579
8518    7291436.0
Name: Population, total, dtype: float64
89.80585279059969
1070    2913021.0
Name: Population, total, dtype: float64
34.08423476245143
5431    16321872.0
Name: Population, total, dtype: float64
60.713701514323624
1364    2877311.0
Name: Population, total, dtype: float64
26.770401919154015
1756    9490583.0
Name: Population, total, dtype: float64
188.36872795712424
6411    364511.0
Name: Population, total, dtype: float64
62.649181122797835
2001    727641.0
Name: Population, total, dtype: float64
46.36669543886165
335    1.230981e+09
Name: Population, total, dtype: float64
2.197347264168819
1021    28803167.0
Name: Population, total, dtype: float64
38.84848960265675
1658    152149102.0
Name: Population, total, dtype: float64
1.7934844826596303
7195    27023137.0
Name: Population, total, dtype: float64
11.827906596352513
7685    170560182.0
Name: Population, total, dtype: float64
17.626766108863222
9057    20198353.0
Name: Population, total, dtype: float64
53.902713917927834
4353    24512104.0
Name: Population, total, dtype: float64
8.465464171374865
5921    2040551.0
Name: Population, total, dtype: float64
4.388474498497111
7097    2173170.0
Name: Population, total, dtype: float64
3.087009016049883
3912    1202843.0
Name: Population, total, dtype: float64
1.7978234835519966
8959    51584663.0
Name: Population, total, dtype: float64
9.939968978255466
3961    87702670.0
Name: Population, total, dtype: float64
48.68760961801564
4255    1692149.0
Name: Population, total, dtype: float64
11.010952252760168
6656    1250400.0
Name: Population, total, dtype: float64
17.10480823689782
6999    24221405.0
Name: Population, total, dtype: float64
0.2209219257209491
5970    3948125.0
Name: Population, total, dtype: float64
2.556309266847384
5480    41350152.0
Name: Population, total, dtype: float64
9.660044283602058
2442    502384.0
Name: Population, total, dtype: float64
28.363978801870864
7440    158578261.0
Name: Population, total, dtype: float64
3.8003091111098963
6313    15167095.0
Name: Population, total, dtype: float64
3.230589111122769
6607    3609543.0
Name: Population, total, dtype: float64
46.81678866257394
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
5.273881391042044
3128    20401331.0
Name: Population, total, dtype: float64
7.438647572293908
2540    19970495.0
Name: Population, total, dtype: float64
2.706380236386298
3030    4386693.0
Name: Population, total, dtype: float64
2.4646415609097287
4206    1640210.0
Name: Population, total, dtype: float64
6.239842635253866
6460    15075085.0
Name: Population, total, dtype: float64
12.973173545536998
7391    16425578.0
Name: Population, total, dtype: float64
2.1627980050798197
9694    6502952.0
Name: Population, total, dtype: float64
1.325550357186862
8469    12916229.0
Name: Population, total, dtype: float64
19.084571492459727
2736    11887202.0
Name: Population, total, dtype: float64
14.600580342949195
8273    10246842.0
Name: Population, total, dtype: float64
0.40231948736756357
2981    64523263.0
Name: Population, total, dtype: float64
1.6114293568859397
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
3.913165520739594
6264    21151640.0
Name: Population, total, dtype: float64
6.126747240681482
10037    33915133.0
Name: Population, total, dtype: float64
1.7633002314564563
8616    6458720.0
Name: Population, total, dtype: float64
6.053423624623541
10576    13850033.0
Name: Population, total, dtype: float64
2.2135906650767634
4696    10794170.0
Name: Population, total, dtype: float64
0.05465289015334952
8420    174776.0
Name: Population, total, dtype: float64
11.230965088765114
5823    2097555.0
Name: Population, total, dtype: float64
61.43050867415137
6901    619428.0
Name: Population, total, dtype: float64
37.5919209481827
1511    9054332.0
Name: Population, total, dtype: float64
20.99545491421484
2295    7395599.0
Name: Population, total, dtype: float64
22.69094392419346
2099    3722084.0
Name: Population, total, dtype: float64
134.29315258914045
874    72326914.0
Name: Population, total, dtype: float64
33.8451092782626
6117    3097282.0
Name: Population, total, dtype: float64
63.30178361955327
8224    20246871.0
Name: Population, total, dtype: float64
43.751020573424945
9498    7641630.0
Name: Population, total, dtype: float64
22.915556651827558
10086    45870700.0
Name: Population, total, dtype: float64
83.07896465966394
6754    3562045.0
Name: Population, total, dtype: float64
25.020295403153092
678    142849449.0
Name: Population, total, dtype: float64
49.12469742900634
5725    5447900.0
Name: Population, total, dtype: float64
14.344230264651207
7489    2070739.0
Name: Population, total, dtype: float64
53.13780932304116
8518    7291436.0
Name: Population, total, dtype: float64
87.33311822966026
1070    2913021.0
Name: Population, total, dtype: float64
20.7168493604553
5431    16321872.0
Name: Population, total, dtype: float64
46.361849485506745
1364    2877311.0
Name: Population, total, dtype: float64
0.0
1756    9490583.0
Name: Population, total, dtype: float64
78.69360244308217
9645    1109591.0
Name: Population, total, dtype: float64
14.545196546615765
4059    859950.0
Name: Population, total, dtype: float64
8.324014785518203
7832    7108239.0
Name: Population, total, dtype: float64
24.699672708913518
188    1.337705e+09
Name: Population, total, dtype: float64
13.88905800845124
9596    67208808.0
Name: Population, total, dtype: float64
2.0416195633344443
7979    93726624.0
Name: Population, total, dtype: float64
14.075554307614482
6852    2712650.0
Name: Population, total, dtype: float64
8.804482692965545
2491    14308740.0
Name: Population, total, dtype: float64
9.147414705658917
5774    6246274.0

Name: Population, total, dtype: float64
3.870619402068349
384    242524123.0
Name: Population, total, dtype: float64
7.560059962290342
10380    88472512.0
Name: Population, total, dtype: float64
8.105475757325962
3716    6164626.0
Name: Population, total, dtype: float64
28.970006459878515
139    196796269.0
Name: Population, total, dtype: float64
11.507370655892394
7930    29373646.0
Name: Population, total, dtype: float64
15.236778010166773
2050    9918242.0
Name: Population, total, dtype: float64
38.38594913609409
4647    14630417.0
Name: Population, total, dtype: float64
14.839293500522766
580    117318941.0
Name: Population, total, dtype: float64
6.036974249217649
4892    8194778.0
Name: Population, total, dtype: float64
11.61737744004582
7342    5737723.0
Name: Population, total, dtype: float64
5.7287471919143735
5333    2817210.0
Name: Population, total, dtype: float64
20.25553784356971
2883    45918097.0
Name: Population, total, dtype: float64
39.67681271889156
5382    7182390.0
Name: Population, total, dtype: float64
38.68294370355571
5137    30762701.0
Name: Population, total, dtype: float64
17.472239450507285
3667    84107606.0
Name: Population, total, dtype: float64
12.564473931441576
6950    32409639.0
Name: Population, total, dtype: float64
40.338456314779684
3471    851146.0
Name: Population, total, dtype: float64
2.097728044827369
10527    23606779.0
Name: Population, total, dtype: float64
17.467599634305163
6411    364511.0
Name: Population, total, dtype: float64
9.316042563532822
2001    727641.0
Name: Population, total, dtype: float64
12.170264243383377
335    1.230981e+09
Name: Population, total, dtype: float64
13.233081828666743
1021    28803167.0
Name: Population, total, dtype: float64
21.30118949202908
1658    152149102.0
Name: Population, total, dtype: float64
2.03473282748084
7195    27023137.0
Name: Population, total, dtype: float64
3.8374669915024673
7685    170560182.0
Name: Population, total, dtype: float64
11.575357890855589
9057    20198353.0
Name: Population, total, dtype: float64
23.322111481854705
4353    24512104.0
Name: Population, total, dtype: float64
2.4549739347903072
5921    2040551.0
Name: Population, total, dtype: float64
2.0255704219389057
7097    2173170.0
Name: Population, total, dtype: float64
7.234635963697056
3912    1202843.0
Name: Population, total, dtype: float64
22.989754794516376
8959    51584663.0
Name: Population, total, dtype: float64
12.107691520855036
3961    87702670.0
Name: Population, total, dtype: float64
1.315724421500195
4255    1692149.0
Name: Population, total, dtype: float64
1.9022733250018624
6656    1250400.0
Name: Population, total, dtype: float64
12.913526012736286
6999    24221405.0
Name: Population, total, dtype: float64
0.5005361902812039
5970    3948125.0
Name: Population, total, dtype: float64
7.327893927524611
5480    41350152.0
Name: Population, total, dtype: float64
12.786460374163994
2442    502384.0
Name: Population, total, dtype: float64
5.653852876839545
7440    158578261.0
Name: Population, total, dtype: float64
12.544159168657854
6313    15167095.0
Name: Population, total, dtype: float64
0.0732888101075543
6607    3609543.0
Name: Population, total, dtype: float64
9.171142988794065
1903    9199259.0
Name: Population, total, dtype: float64
2.9429713251946885
2344    15605217.0
Name: Population, total, dtype: float64
0.7247285504156996
3128    20401331.0
Name: Population, total, dtype: float64
2.222692923618823
2540    19970495.0
Name: Population, total, dtype: float64
2.5370366088608765
3030    4386693.0
Name: Population, total, dtype: float64
2.4765587248266527
4206    1640210.0
Name: Population, total, dtype: float64
12.311199746454658
6460    15075085.0
Name: Population, total, dtype: float64
2.1569453855202205
7391    16425578.0
Name: Population, total, dtype: float64
2.519263434640858
9694    6502952.0
Name: Population, total, dtype: float64
2.2811714804999843
8469    12916229.0
Name: Population, total, dtype: float64
2.7584086622463446
2736    11887202.0
Name: Population, total, dtype: float64
1.2841515017866152
8273    10246842.0
Name: Population, total, dtype: float64
2.7522287382379544
2981    64523263.0
Name: Population, total, dtype: float64
1.599614505225277
2393    8766930.0
Name: Population, total, dtype: float64
1.0888343912804201
9547    46098591.0
Name: Population, total, dtype: float64
3.783732943258855
6264    21151640.0
Name: Population, total, dtype: float64
0.02202178464742617
10037    33915133.0
Name: Population, total, dtype: float64
1.8334789847826736
8616    6458720.0
Name: Population, total, dtype: float64
10.322761811506721
10576    13850033.0
Name: Population, total, dtype: float64
0.1695644645354677
4696    10794170.0
Name: Population, total, dtype: float64
1.5268914483202507
8420    174776.0
Name: Population, total, dtype: float64
5.4532381055099055
9645    1109591.0
Name: Population, total, dtype: float64
0.030208958197744235
4059    859950.0
Name: Population, total, dtype: float64
13.763169615333625
7832    7108239.0
Name: Population, total, dtype: float64
3.6762597858166375
188    1.337705e+09
Name: Population, total, dtype: float64
18.997708399679226
9596    67208808.0
Name: Population, total, dtype: float64
24.325489078649984
7979    93726624.0
Name: Population, total, dtype: float64
5.047567063873446
6852    2712650.0
Name: Population, total, dtype: float64
0.7078780159481645
2491    14308740.0
Name: Population, total, dtype: float64
1.6337053667103871
5774    6246274.0
Name: Population, total, dtype: float64
3.045240323104041
384    242524123.0
Name: Population, total, dtype: float64
0.0
10380    88472512.0
Name: Population, total, dtype: float64
3.935698349650672
3716    6164626.0
Name: Population, total, dtype: float64
9.273778573561561
139    196796269.0
Name: Population, total, dtype: float64
84.17274116730238
7930    29373646.0
Name: Population, total, dtype: float64
35.616259520084576
2050    9918242.0
Name: Population, total, dtype: float64
2.5170311755920043
4647    14630417.0
Name: Population, total, dtype: float64
26.65762277012228
580    117318941.0
Name: Population, total, dtype: float64
24.399132007634822
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
3.204574816347103
5333    2817210.0
Name: Population, total, dtype: float64
14.041978217966099
2883    45918097.0
Name: Population, total, dtype: float64
100.79517098240518
5382    7182390.0
Name: Population, total, dtype: float64
7.773832817401458
5137    30762701.0
Name: Population, total, dtype: float64
10.50627955605449
3667    84107606.0
Name: Population, total, dtype: float64
9.575617566044272
6950    32409639.0
Name: Population, total, dtype: float64
17.348892976411168
3471    851146.0
Name: Population, total, dtype: float64
4.730295654642462
10527    23606779.0
Name: Population, total, dtype: float64
27.138904518110643
5823    2097555.0
Name: Population, total, dtype: float64
30.217808934733867
6901    619428.0
Name: Population, total, dtype: float64
22.177911928691135
1511    9054332.0
Name: Population, total, dtype: float64
1.1615953785396038
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
22.25323902627075
874    72326914.0
Name: Population, total, dtype: float64
17.578477960269463
6117    3097282.0
Name: Population, total, dtype: float64
11.468842085280334
8224    20246871.0
Name: Population, total, dtype: float64
6.107367940760613
9498    7641630.0
Name: Population, total, dtype: float64
7.4531952620891495
10086    45870700.0
Name: Population, total, dtype: float64
2.899391324573356
6754    3562045.0
Name: Population, total, dtype: float64
17.585190716699426
678    142849449.0
Name: Population, total, dtype: float64
7.230733208264529
5725    5447900.0
Name: Population, total, dtype: float64
1.3200274644541106
7489    2070739.0
Name: Population, total, dtype: float64
14.550369658690286
8518    7291436.0
Name: Population, total, dtype: float64
23.661423614191417
1070    2913021.0
Name: Population, total, dtype: float64
35.42548358859613
5431    16321872.0
Name: Population, total, dtype: float64
4.866745328352454
1364    2877311.0
Name: Population, total, dtype: float64
0.7791389671954625
1756    9490583.0
Name: Population, total, dtype: float64
22.146877450591703
6411    364511.0
Name: Population, total, dtype: float64
62.63238864338339
2001    727641.0
Name: Population, total, dtype: float64
0.6412370060103755
335    1.230981e+09
Name: Population, total, dtype: float64
5.550652976246307
1021    28803167.0
Name: Population, total, dtype: float64
6.419330795876365
1658    152149102.0
Name: Population, total, dtype: float64
2.257055995751359
7195    27023137.0
Name: Population, total, dtype: float64
9.245112619101926
7685    170560182.0
Name: Population, total, dtype: float64
4.429910852510676
9057    20198353.0
Name: Population, total, dtype: float64
4.981291138100166
9645    1109591.0
Name: Population, total, dtype: float64
3.3893316271414653
4059    859950.0
Name: Population, total, dtype: float64
3.4089772124803037
7832    7108239.0
Name: Population, total, dtype: float64
10.784442331135542
188    1.337705e+09
Name: Population, total, dtype: float64
10.239570358391566
9596    67208808.0
Name: Population, total, dtype: float64
12.92218574062175
7979    93726624.0
Name: Population, total, dtype: float64
3.383785964268596
6852    2712650.0
Name: Population, total, dtype: float64
10.431887625341714
2491    14308740.0
Name: Population, total, dtype: float64
6.390735955151877
5774    6246274.0
Name: Population, total, dtype: float64
3.9622826430336393
384    242524123.0
Name: Population, total, dtype: float64
0.22977121468291492
10380    88472512.0
Name: Population, total, dtype: float64
5.621365599006252
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
1.7710260011448875
7930    29373646.0
Name: Population, total, dtype: float64
3.80516869529285
2050    9918242.0
Name: Population, total, dtype: float64
2.5666712731012202
4647    14630417.0
Name: Population, total, dtype: float64
3.605199280569981
580    117318941.0
Name: Population, total, dtype: float64
1.283737436463744
4892    8194778.0
Name: Population, total, dtype: float64
1.8192531028430605
7342    5737723.0
Name: Population, total, dtype: float64
0.8069648049099426
5333    2817210.0
Name: Population, total, dtype: float64
4.122877150984781
2883    45918097.0
Name: Population, total, dtype: float64
5.059101237618485
4353    24512104.0
Name: Population, total, dtype: float64
12.084901153200137
5921    2040551.0
Name: Population, total, dtype: float64
0.4831698950643196
7097    2173170.0
Name: Population, total, dtype: float64
0.8447640244583471
3912    1202843.0
Name: Population, total, dtype: float64
0.3253669836116029
8959    51584663.0
Name: Population, total, dtype: float64
4.168358809814808
3961    87702670.0
Name: Population, total, dtype: float64
1.3795262085970175
4255    1692149.0
Name: Population, total, dtype: float64
0.0
6656    1250400.0
Name: Population, total, dtype: float64
25.830951112857562
6999    24221405.0
Name: Population, total, dtype: float64
0.6516196159988836
5970    3948125.0
Name: Population, total, dtype: float64
2.315488696432502
5480    41350152.0
Name: Population, total, dtype: float64
3.9559910275106525
2442    502384.0
Name: Population, total, dtype: float64
2.8942832306840542
7440    158578261.0
Name: Population, total, dtype: float64

0.4152061853296965
6313    15167095.0
Name: Population, total, dtype: float64
0.9547462296989312
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
3.247303981360566
2344    15605217.0
Name: Population, total, dtype: float64
0.3219650421362688
3128    20401331.0
Name: Population, total, dtype: float64
2.8894278796726915
2540    19970495.0
Name: Population, total, dtype: float64
0.5045759915450418
3030    4386693.0
Name: Population, total, dtype: float64
2.0813270775063923
4206    1640210.0
Name: Population, total, dtype: float64
4.026642992250127
6460    15075085.0
Name: Population, total, dtype: float64
0.032026983056975926
7391    16425578.0
Name: Population, total, dtype: float64
0.0591374065390622
9694    6502952.0
Name: Population, total, dtype: float64
3.0735299242734384
8469    12916229.0
Name: Population, total, dtype: float64
0.7804043787040884
2736    11887202.0
Name: Population, total, dtype: float64
5.207328496696005
8273    10246842.0
Name: Population, total, dtype: float64
0.17201216910547582
2981    64523263.0
Name: Population, total, dtype: float64
1.732635277502118
2393    8766930.0
Name: Population, total, dtype: float64
1.9171213517160408
9547    46098591.0
Name: Population, total, dtype: float64
6.079172168155257
6264    21151640.0
Name: Population, total, dtype: float64
0.45507213384261447
10037    33915133.0
Name: Population, total, dtype: float64
4.789346622429483
8616    6458720.0
Name: Population, total, dtype: float64
3.959437192217937
10576    13850033.0
Name: Population, total, dtype: float64
1.8908787603833555
4696    10794170.0
Name: Population, total, dtype: float64
0.3881929177124342
8420    174776.0
Name: Population, total, dtype: float64
37.215752291098354
5823    2097555.0
Name: Population, total, dtype: float64
43.20405341151413
6901    619428.0
Name: Population, total, dtype: float64
15.176239224462858
1511    9054332.0
Name: Population, total, dtype: float64
3.605231190483905
2295    7395599.0
Name: Population, total, dtype: float64
38.87476206024725
2099    3722084.0
Name: Population, total, dtype: float64
15.962925059677492
874    72326914.0
Name: Population, total, dtype: float64
5.4274655607966436
6117    3097282.0
Name: Population, total, dtype: float64
45.092565828834275
8224    20246871.0
Name: Population, total, dtype: float64
28.01112721894905
9498    7641630.0
Name: Population, total, dtype: float64
0.5151198034008989
10086    45870700.0
Name: Population, total, dtype: float64
34.4990508182324
6754    3562045.0
Name: Population, total, dtype: float64
5.184966878236432
678    142849449.0
Name: Population, total, dtype: float64
67.27200564264258
5725    5447900.0
Name: Population, total, dtype: float64
4.899014394177365
7489    2070739.0
Name: Population, total, dtype: float64
21.262716792701614
8518    7291436.0
Name: Population, total, dtype: float64
20.020208297446857
1070    2913021.0
Name: Population, total, dtype: float64
9.779440250895632
5431    16321872.0
Name: Population, total, dtype: float64
30.100438881248866
1364    2877311.0
Name: Population, total, dtype: float64
9.710237715561014
1756    9490583.0
Name: Population, total, dtype: float64
53.281720891741934
6411    364511.0
Name: Population, total, dtype: float64
0.0
2001    727641.0
Name: Population, total, dtype: float64
1.0136521004281012
335    1.230981e+09
Name: Population, total, dtype: float64
3.774809880044849
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
0.0
7195    27023137.0
Name: Population, total, dtype: float64
1.423903757360446
7685    170560182.0
Name: Population, total, dtype: float64
0.0
9057    20198353.0
Name: Population, total, dtype: float64
17.1896048710016
5382    7182390.0
Name: Population, total, dtype: float64
0.4766432470806602
5137    30762701.0
Name: Population, total, dtype: float64
0.2254609453931484
3667    84107606.0
Name: Population, total, dtype: float64
0.006241555511316767
6950    32409639.0
Name: Population, total, dtype: float64
0.09471140570844935
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
0.0
4353    24512104.0
Name: Population, total, dtype: float64
0.7884214605778644
5921    2040551.0
Name: Population, total, dtype: float64
0.6616930085293764
7097    2173170.0
Name: Population, total, dtype: float64
1.1527757280742614
3912    1202843.0
Name: Population, total, dtype: float64
0.6192687270698031
8959    51584663.0
Name: Population, total, dtype: float64
4.862286361324193
3961    87702670.0
Name: Population, total, dtype: float64
1.0841926474154373
4255    1692149.0
Name: Population, total, dtype: float64
0.18682663047485923
6656    1250400.0
Name: Population, total, dtype: float64
8.9649900198106
6999    24221405.0
Name: Population, total, dtype: float64
0.6761175768754301
5970    3948125.0
Name: Population, total, dtype: float64
2.37328756368748
5480    41350152.0
Name: Population, total, dtype: float64
0.5380276148696451
2442    502384.0
Name: Population, total, dtype: float64
7.085337405634687
7440    158578261.0
Name: Population, total, dtype: float64
0.49906488497700535
6313    15167095.0
Name: Population, total, dtype: float64
0.5882670733262273
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
2.133911349036291
2344    15605217.0
Name: Population, total, dtype: float64
0.08347119241997218
3128    20401331.0
Name: Population, total, dtype: float64
1.2318743234942542
2540    19970495.0
Name: Population, total, dtype: float64
4.901121853916513
3030    4386693.0
Name: Population, total, dtype: float64
3.9993393111975606
4206    1640210.0
Name: Population, total, dtype: float64
7.830731155790421
6460    15075085.0
Name: Population, total, dtype: float64
0.045609589549037294
7391    16425578.0
Name: Population, total, dtype: float64
0.0
9694    6502952.0
Name: Population, total, dtype: float64
0.8454588806441814
9645    1109591.0
Name: Population, total, dtype: float64
2.536787551082534
4059    859950.0
Name: Population, total, dtype: float64
0.48956586777771294
7832    7108239.0
Name: Population, total, dtype: float64
0.8317701257567135
188    1.337705e+09
Name: Population, total, dtype: float64
3.3344243042414625
9596    67208808.0
Name: Population, total, dtype: float64
0.2300450498724145
7979    93726624.0
Name: Population, total, dtype: float64
1.0366601839763214
6852    2712650.0
Name: Population, total, dtype: float64
1.4060479306181082
2491    14308740.0
Name: Population, total, dtype: float64
0.8471283354776851
5774    6246274.0
Name: Population, total, dtype: float64
0.0
384    242524123.0
Name: Population, total, dtype: float64
0.05409380308668563
10380    88472512.0
Name: Population, total, dtype: float64
0.0
5823    2097555.0
Name: Population, total, dtype: float64
30.28458428797922
6901    619428.0
Name: Population, total, dtype: float64
16.31463030782278
1511    9054332.0
Name: Population, total, dtype: float64
0.5230737108695284
2295    7395599.0
Name: Population, total, dtype: float64
43.43332447420268
2099    3722084.0
Name: Population, total, dtype: float64
17.13626797399709
874    72326914.0
Name: Population, total, dtype: float64
0.5837746656026747
6117    3097282.0
Name: Population, total, dtype: float64
32.31353899760047
8224    20246871.0
Name: Population, total, dtype: float64
42.12907938347252
9498    7641630.0
Name: Population, total, dtype: float64
0.6571045493682178
10086    45870700.0
Name: Population, total, dtype: float64
13.889229499411655
6754    3562045.0
Name: Population, total, dtype: float64
6.098726403523424
678    142849449.0
Name: Population, total, dtype: float64
11.514586327394833
5725    5447900.0
Name: Population, total, dtype: float64
1.934617432895878
7489    2070739.0
Name: Population, total, dtype: float64
17.141708340575608
8518    7291436.0
Name: Population, total, dtype: float64
12.83547476265262
1070    2913021.0
Name: Population, total, dtype: float64
11.796716389685907
5431    16321872.0
Name: Population, total, dtype: float64
11.149530338029004
1364    2877311.0
Name: Population, total, dtype: float64
2.755319837837777
1756    9490583.0
Name: Population, total, dtype: float64
45.00931085222823
6411    364511.0
Name: Population, total, dtype: float64
0.0
2001    727641.0
Name: Population, total, dtype: float64
19.171436521037243
335    1.230981e+09
Name: Population, total, dtype: float64

0.14486810106674416
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
0.0
7195    27023137.0
Name: Population, total, dtype: float64
10.402507155383834
7685    170560182.0
Name: Population, total, dtype: float64
0.0
9057    20198353.0
Name: Population, total, dtype: float64
0.035669219290114414
8469    12916229.0
Name: Population, total, dtype: float64
2.0978617879389194
2736    11887202.0
Name: Population, total, dtype: float64
1.9884157548934174
8273    10246842.0
Name: Population, total, dtype: float64
0.11981843005476496
2981    64523263.0
Name: Population, total, dtype: float64
1.193663233907177
2393    8766930.0
Name: Population, total, dtype: float64
1.0954979350380751
9547    46098591.0
Name: Population, total, dtype: float64
0.01069048893148827
6264    21151640.0
Name: Population, total, dtype: float64
0.22753606687737224
10037    33915133.0
Name: Population, total, dtype: float64
0.062226057786397275
8616    6458720.0
Name: Population, total, dtype: float64
5.306030708197948
10576    13850033.0
Name: Population, total, dtype: float64
1.0436782621646563
4696    10794170.0
Name: Population, total, dtype: float64
2.84917757248852
8420    174776.0
Name: Population, total, dtype: float64
41.773031485668106
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
2.4884680011176687
7930    29373646.0
Name: Population, total, dtype: float64
0.0
2050    9918242.0
Name: Population, total, dtype: float64
2.3339597105169805
4647    14630417.0
Name: Population, total, dtype: float64
0.0
580    117318941.0
Name: Population, total, dtype: float64
0.22423272055765325
4892    8194778.0
Name: Population, total, dtype: float64
0.22725618510051396
7342    5737723.0
Name: Population, total, dtype: float64
0.08413354697555084
5333    2817210.0
Name: Population, total, dtype: float64
1.6376290298962703
2883    45918097.0
Name: Population, total, dtype: float64
1.0629707799702866
5382    7182390.0
Name: Population, total, dtype: float64
0.021086348614687337
5137    30762701.0
Name: Population, total, dtype: float64
0.014771955708512618
3667    84107606.0
Name: Population, total, dtype: float64
0.001040259664506442
6950    32409639.0
Name: Population, total, dtype: float64
0.15687445993105836
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
0.0
4353    24512104.0
Name: Population, total, dtype: float64
1.5789418173563603
5921    2040551.0
Name: Population, total, dtype: float64
16.891208690239917
7097    2173170.0
Name: Population, total, dtype: float64
22.748262053162808
3912    1202843.0
Name: Population, total, dtype: float64
8.020217870020483
8959    51584663.0
Name: Population, total, dtype: float64
31.79422742199979
3961    87702670.0
Name: Population, total, dtype: float64
20.955600700047597
4255    1692149.0
Name: Population, total, dtype: float64
100.9358753601067
6656    1250400.0
Name: Population, total, dtype: float64
33.96208453138925
6999    24221405.0
Name: Population, total, dtype: float64
2.4996693740652676
5970    3948125.0
Name: Population, total, dtype: float64
0.7579601223534531
5480    41350152.0
Name: Population, total, dtype: float64
25.136426972940434
2442    502384.0
Name: Population, total, dtype: float64
39.14283562827029
7440    158578261.0
Name: Population, total, dtype: float64
21.018775161370357
6313    15167095.0
Name: Population, total, dtype: float64
8.932891214242575
6607    3609543.0
Name: Population, total, dtype: float64
55.421830735602136
1903    9199259.0
Name: Population, total, dtype: float64
5.3587658232728845
5823    2097555.0
Name: Population, total, dtype: float64
14.133496462428305
6901    619428.0
Name: Population, total, dtype: float64
84.87469541347585
1511    9054332.0
Name: Population, total, dtype: float64
92.19189672070291
2295    7395599.0
Name: Population, total, dtype: float64
12.15370691745602
2099    3722084.0
Name: Population, total, dtype: float64
243.62860306650904
874    72326914.0
Name: Population, total, dtype: float64
52.212779797008544
6117    3097282.0
Name: Population, total, dtype: float64
38.4753176425737
8224    20246871.0
Name: Population, total, dtype: float64
40.78190879527152
9498    7641630.0
Name: Population, total, dtype: float64
121.7118766100393
10086    45870700.0
Name: Population, total, dtype: float64
41.85066665467038
6754    3562045.0
Name: Population, total, dtype: float64
17.936493151515215
678    142849449.0
Name: Population, total, dtype: float64
125.9733166567985
5725    5447900.0
Name: Population, total, dtype: float64
87.70337241693025
7489    2070739.0
Name: Population, total, dtype: float64
136.90698029867718
8518    7291436.0
Name: Population, total, dtype: float64
95.51119204754393
1070    2913021.0
Name: Population, total, dtype: float64
237.13196848523108
5431    16321872.0
Name: Population, total, dtype: float64
145.32520691961489
1364    2877311.0
Name: Population, total, dtype: float64
48.670462345520306
1756    9490583.0
Name: Population, total, dtype: float64
20.069997892536172
6411    364511.0
Name: Population, total, dtype: float64
0.01578327131950548
2001    727641.0
Name: Population, total, dtype: float64
36.145763612662954
335    1.230981e+09
Name: Population, total, dtype: float64
1.526749626937053
1021    28803167.0
Name: Population, total, dtype: float64
43.75033088848385
1658    152149102.0
Name: Population, total, dtype: float64
17.763783715905987
7195    27023137.0
Name: Population, total, dtype: float64
9.521156569569014
7685    170560182.0
Name: Population, total, dtype: float64
18.06145146565625
9057    20198353.0
Name: Population, total, dtype: float64
6.870244758751281
9645    1109591.0
Name: Population, total, dtype: float64
23.35720867006287
4059    859950.0
Name: Population, total, dtype: float64
13.235215044684624
7832    7108239.0
Name: Population, total, dtype: float64
2.903417760312063
188    1.337705e+09
Name: Population, total, dtype: float64
12.446924942477986
9596    67208808.0
Name: Population, total, dtype: float64
11.096749222036637
7979    93726624.0
Name: Population, total, dtype: float64
6.571775203043206
6852    2712650.0
Name: Population, total, dtype: float64
48.05225571715856
2491    14308740.0
Name: Population, total, dtype: float64
22.433450102209672
5774    6246274.0
Name: Population, total, dtype: float64
41.159716626916534
384    242524123.0
Name: Population, total, dtype: float64
4.130123420231731
10380    88472512.0
Name: Population, total, dtype: float64
12.378670481158323
2344    15605217.0
Name: Population, total, dtype: float64
3.21231481639224
3128    20401331.0
Name: Population, total, dtype: float64
27.27888201598764
2540    19970495.0
Name: Population, total, dtype: float64
19.90548672279008
3030    4386693.0
Name: Population, total, dtype: float64
31.784872705786476
4206    1640210.0
Name: Population, total, dtype: float64
25.856242927847713
6460    15075085.0
Name: Population, total, dtype: float64
19.600749271951642
7391    16425578.0
Name: Population, total, dtype: float64
8.136663153647616
9694    6502952.0
Name: Population, total, dtype: float64
6.73801953308048
8469    12916229.0
Name: Population, total, dtype: float64
16.23132152099834
2736    11887202.0
Name: Population, total, dtype: float64
38.127802193828316
8273    10246842.0
Name: Population, total, dtype: float64
7.995736279834266
2981    64523263.0
Name: Population, total, dtype: float64
3.051270407625084
2393    8766930.0
Name: Population, total, dtype: float64
2.580397170231652
9547    46098591.0
Name: Population, total, dtype: float64
17.439473171703465
6264    21151640.0
Name: Population, total, dtype: float64
10.974459457098874
10037    33915133.0
Name: Population, total, dtype: float64
22.835241796131918
8616    6458720.0
Name: Population, total, dtype: float64
6.864471574477764
10576    13850033.0
Name: Population, total, dtype: float64
9.711582061419653
4696    10794170.0
Name: Population, total, dtype: float64
10.63742678397373
8420    174776.0
Name: Population, total, dtype: float64
8.610373568216998
3716    6164626.0
Name: Population, total, dtype: float64
20.160993808121468
139    196796269.0
Name: Population, total, dtype: float64
86.77072294310021
7930    29373646.0
Name: Population, total, dtype: float64
33.338313834718754
2050    9918242.0
Name: Population, total, dtype: float64
162.79125940683096
4647    14630417.0
Name: Population, total, dtype: float64
85.53474986392447
580    117318941.0
Name: Population, total, dtype: float64
49.47146503106813
4892    8194778.0
Name: Population, total, dtype: float64
85.85814685923499
7342    5737723.0
Name: Population, total, dtype: float64
11.0634090020856
5333    2817210.0
Name: Population, total, dtype: float64
4.7990288650620885
2883    45918097.0
Name: Population, total, dtype: float64
78.55534321123409
5382    7182390.0
Name: Population, total, dtype: float64
29.847351656962882
5137    30762701.0
Name: Population, total, dtype: float64
39.01098372397014
3667    84107606.0
Name: Population, total, dtype: float64
75.13492388093114
6950    32409639.0
Name: Population, total, dtype: float64
83.96340821771012
3471    851146.0
Name: Population, total, dtype: float64
9.13828589508109
10527    23606779.0
Name: Population, total, dtype: float64
30.804776431642587
9645    1109591.0
Name: Population, total, dtype: float64
0.5974785105197337
4059    859950.0
Name: Population, total, dtype: float64
2.596910444414512
7832    7108239.0
Name: Population, total, dtype: float64
4.727268915030309
188    1.337705e+09
Name: Population, total, dtype: float64
3.9665036167989647
9596    67208808.0
Name: Population, total, dtype: float64
0.006698626705235324
7979    93726624.0
Name: Population, total, dtype: float64
0.1792864562851107
6852    2712650.0
Name: Population, total, dtype: float64
17.393591021603797
2491    14308740.0
Name: Population, total, dtype: float64
11.333775980761503
5774    6246274.0
Name: Population, total, dtype: float64
0.44765376954168806
384    242524123.0
Name: Population, total, dtype: float64
1.1455446500944269
10380    88472512.0
Name: Population, total, dtype: float64
7.654857782065206
3716    6164626.0
Name: Population, total, dtype: float64
34.43488042020702
139    196796269.0
Name: Population, total, dtype: float64
116.6324643432184
7930    29373646.0
Name: Population, total, dtype: float64
1.0429882611267194
2050    9918242.0
Name: Population, total, dtype: float64
2.0268031624222353
4647    14630417.0
Name: Population, total, dtype: float64
65.84427385553523
580    117318941.0
Name: Population, total, dtype: float64
80.34522462499437
4892    8194778.0
Name: Population, total, dtype: float64
2.872278803472281
7342    5737723.0
Name: Population, total, dtype: float64
0.03216304781005627
5333    2817210.0
Name: Population, total, dtype: float64
3.353910521439721
2883    45918097.0
Name: Population, total, dtype: float64
60.58912002935585
4353    24512104.0
Name: Population, total, dtype: float64
15.283045033582916
5921    2040551.0
Name: Population, total, dtype: float64
9.270663448938793
7097    2173170.0
Name: Population, total, dtype: float64
4.5009060750877135
3912    1202843.0
Name: Population, total, dtype: float64
0.9673756001382451
8959    51584663.0
Name: Population, total, dtype: float64
3.000157033205491

3961    87702670.0
Name: Population, total, dtype: float64
3.4713546294285385
4255    1692149.0
Name: Population, total, dtype: float64
21.069047501852793
6656    1250400.0
Name: Population, total, dtype: float64
7.679666823348225
6999    24221405.0
Name: Population, total, dtype: float64
1.1538667751219185
5970    3948125.0
Name: Population, total, dtype: float64
1.5149988128210718
5480    41350152.0
Name: Population, total, dtype: float64
3.68146713704891
2442    502384.0
Name: Population, total, dtype: float64
0.5178839859044732
7440    158578261.0
Name: Population, total, dtype: float64
8.44353033358734
6313    15167095.0
Name: Population, total, dtype: float64
0.09821882720322532
6607    3609543.0
Name: Population, total, dtype: float64
1.053750348677659
1903    9199259.0
Name: Population, total, dtype: float64
3.792612117897345
2344    15605217.0
Name: Population, total, dtype: float64
13.374831255910465
3128    20401331.0
Name: Population, total, dtype: float64
0.0
2540    19970495.0
Name: Population, total, dtype: float64
10.865654014364514
3030    4386693.0
Name: Population, total, dtype: float64
15.344166211023959
4206    1640210.0
Name: Population, total, dtype: float64
0.0049225414846754845
6460    15075085.0
Name: Population, total, dtype: float64
3.638390287616289
7391    16425578.0
Name: Population, total, dtype: float64
20.42259072178222
9694    6502952.0
Name: Population, total, dtype: float64
6.867752144059932
8469    12916229.0
Name: Population, total, dtype: float64
19.667422189211027
2736    11887202.0
Name: Population, total, dtype: float64
12.505489908902439
8273    10246842.0
Name: Population, total, dtype: float64
1.2231872305608265
2981    64523263.0
Name: Population, total, dtype: float64
4.668679866442236
2393    8766930.0
Name: Population, total, dtype: float64
0.6823610388046282
9547    46098591.0
Name: Population, total, dtype: float64
5.571698363104668
6264    21151640.0
Name: Population, total, dtype: float64
2.9253489641213206
10037    33915133.0
Name: Population, total, dtype: float64
0.5622187853661611
8616    6458720.0
Name: Population, total, dtype: float64
24.04671857956882
10576    13850033.0
Name: Population, total, dtype: float64
0.2964470157273996
4696    10794170.0
Name: Population, total, dtype: float64
7.002831213008222
8420    174776.0
Name: Population, total, dtype: float64
19.89681308664478
5823    2097555.0
Name: Population, total, dtype: float64
14.39304071718315
6901    619428.0
Name: Population, total, dtype: float64
2.634057419783232
1511    9054332.0
Name: Population, total, dtype: float64
1.8154285222656588
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
10.053463183987576
874    72326914.0
Name: Population, total, dtype: float64
11.033172895501513
6117    3097282.0
Name: Population, total, dtype: float64
16.33548870618223
8224    20246871.0
Name: Population, total, dtype: float64
16.840142241258203
9498    7641630.0
Name: Population, total, dtype: float64
0.0
10086    45870700.0
Name: Population, total, dtype: float64
0.3096819274460093
6754    3562045.0
Name: Population, total, dtype: float64
11.413924453553173
678    142849449.0
Name: Population, total, dtype: float64
52.1236047053276
5725    5447900.0
Name: Population, total, dtype: float64
5.113115680919249
7489    2070739.0
Name: Population, total, dtype: float64
8.369278615423948
8518    7291436.0
Name: Population, total, dtype: float64
16.864726309658252
1070    2913021.0
Name: Population, total, dtype: float64
69.86030241855998
5431    16321872.0
Name: Population, total, dtype: float64
5.9755921417639
1364    2877311.0
Name: Population, total, dtype: float64
0.6364756288281854
1756    9490583.0
Name: Population, total, dtype: float64
26.687534083286458
6411    364511.0
Name: Population, total, dtype: float64
13.577932995094208
2001    727641.0
Name: Population, total, dtype: float64
14.078868511427697
335    1.230981e+09
Name: Population, total, dtype: float64
0.4585268457268539
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
1.1738412319366778
7195    27023137.0
Name: Population, total, dtype: float64
15.975647287080156
7685    170560182.0
Name: Population, total, dtype: float64
2.4064099843795486
9057    20198353.0
Name: Population, total, dtype: float64
3.268729425412627
5382    7182390.0
Name: Population, total, dtype: float64
6.429126856355789
5137    30762701.0
Name: Population, total, dtype: float64
2.2074001166234107
3667    84107606.0
Name: Population, total, dtype: float64
4.509153661787516
6950    32409639.0
Name: Population, total, dtype: float64
3.1901280844865365
3471    851146.0
Name: Population, total, dtype: float64
13.509016356031637
10527    23606779.0
Name: Population, total, dtype: float64
9.99233051591541
3716    6164626.0
Name: Population, total, dtype: float64
31.69527772850992
139    196796269.0
Name: Population, total, dtype: float64
8.626809971830063
7930    29373646.0
Name: Population, total, dtype: float64
22.179930344641647
2050    9918242.0
Name: Population, total, dtype: float64
25.15593007838869
4647    14630417.0
Name: Population, total, dtype: float64
26.601929742817557
580    117318941.0
Name: Population, total, dtype: float64
14.857874365094277
4892    8194778.0
Name: Population, total, dtype: float64
27.01495120214348
7342    5737723.0
Name: Population, total, dtype: float64
7.163683428250725
5333    2817210.0
Name: Population, total, dtype: float64
12.072612975402015
2883    45918097.0
Name: Population, total, dtype: float64
39.8890395047412
5382    7182390.0
Name: Population, total, dtype: float64
21.729948199353533
5137    30762701.0
Name: Population, total, dtype: float64
36.96916865638983
3667    84107606.0
Name: Population, total, dtype: float64
16.307061257822696
6950    32409639.0
Name: Population, total, dtype: float64
15.998488724081648
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
15.599947960332134
4353    24512104.0
Name: Population, total, dtype: float64
7.10961873654508
5921    2040551.0
Name: Population, total, dtype: float64
9.589581646763305
7097    2173170.0
Name: Population, total, dtype: float64
0.0
3912    1202843.0
Name: Population, total, dtype: float64
3.406524373577412
8959    51584663.0
Name: Population, total, dtype: float64
10.4350062656459
3961    87702670.0
Name: Population, total, dtype: float64
0.8600537160721348
4255    1692149.0
Name: Population, total, dtype: float64
8.453421555618803
6656    1250400.0
Name: Population, total, dtype: float64
12.228890151984048
6999    24221405.0
Name: Population, total, dtype: float64
1.3375365614009889
5970    3948125.0
Name: Population, total, dtype: float64
2.735863580150572
5480    41350152.0
Name: Population, total, dtype: float64
5.143399628573868
2442    502384.0
Name: Population, total, dtype: float64
15.705695328882902
7440    158578261.0
Name: Population, total, dtype: float64
2.0817094881546843
6313    15167095.0
Name: Population, total, dtype: float64
8.343025130544534
6607    3609543.0
Name: Population, total, dtype: float64
0.6043378857581418
1903    9199259.0
Name: Population, total, dtype: float64
0.4081179423126957
2344    15605217.0
Name: Population, total, dtype: float64
0.28661053902666117
3128    20401331.0
Name: Population, total, dtype: float64
5.265152405878447
2540    19970495.0
Name: Population, total, dtype: float64
2.1149784261317435
3030    4386693.0
Name: Population, total, dtype: float64
2.6393131572114137
4206    1640210.0
Name: Population, total, dtype: float64
10.541740211607522
6460    15075085.0
Name: Population, total, dtype: float64
1.3371474066063365
7391    16425578.0
Name: Population, total, dtype: float64
0.2563438189733469
9694    6502952.0
Name: Population, total, dtype: float64
2.154795498044184
8469    12916229.0
Name: Population, total, dtype: float64
0.20307048313749634
2736    11887202.0
Name: Population, total, dtype: float64
0.3472245579750618
8273    10246842.0
Name: Population, total, dtype: float64
0.7039209526457731
2981    64523263.0
Name: Population, total, dtype: float64
0.25742696852493757
2393    8766930.0
Name: Population, total, dtype: float64
0.8113982380153729
9547    46098591.0
Name: Population, total, dtype: float64
1.2850970427535626
6264    21151640.0
Name: Population, total, dtype: float64
1.2885186483201363
10037    33915133.0
Name: Population, total, dtype: float64
3.0749584719245586
8616    6458720.0
Name: Population, total, dtype: float64
2.065555989526319
10576    13850033.0
Name: Population, total, dtype: float64
4.924737181226556
4696    10794170.0
Name: Population, total, dtype: float64
2.313072080710225
8420    174776.0
Name: Population, total, dtype: float64
65.46351242656539
5823    2097555.0
Name: Population, total, dtype: float64
39.82800289044665
6901    619428.0
Name: Population, total, dtype: float64
53.11896183799962
1511    9054332.0
Name: Population, total, dtype: float64
18.11807859922282
2295    7395599.0
Name: Population, total, dtype: float64
40.58585676448967
2099    3722084.0
Name: Population, total, dtype: float64
59.98105582541904
874    72326914.0
Name: Population, total, dtype: float64
26.464571150068707
6117    3097282.0
Name: Population, total, dtype: float64
38.79740793693547
8224    20246871.0
Name: Population, total, dtype: float64
42.956893895493344
9498    7641630.0
Name: Population, total, dtype: float64
32.47458268042644
10086    45870700.0
Name: Population, total, dtype: float64
58.97359137152372
6754    3562045.0
Name: Population, total, dtype: float64
21.61002609994532
678    142849449.0
Name: Population, total, dtype: float64
38.64808675517293
5725    5447900.0
Name: Population, total, dtype: float64
17.902941215220064
7489    2070739.0
Name: Population, total, dtype: float64
77.74990370128818
8518    7291436.0
Name: Population, total, dtype: float64
49.31043712468624
1070    2913021.0
Name: Population, total, dtype: float64
46.83699966802969
5431    16321872.0
Name: Population, total, dtype: float64
39.82418796994811
1364    2877311.0
Name: Population, total, dtype: float64
28.862709689772558
1756    9490583.0
Name: Population, total, dtype: float64
39.67318723478333
6411    364511.0
Name: Population, total, dtype: float64
8.312984869238159
2001    727641.0
Name: Population, total, dtype: float64
6.98339910591339
335    1.230981e+09
Name: Population, total, dtype: float64
2.2302300860623636
1021    28803167.0
Name: Population, total, dtype: float64
13.01170882904915
1658    152149102.0
Name: Population, total, dtype: float64
7.644213062470195
7195    27023137.0
Name: Population, total, dtype: float64
10.353949866736865
7685    170560182.0
Name: Population, total, dtype: float64
4.66474097264742
9057    20198353.0
Name: Population, total, dtype: float64
8.256020619275482
9645    1109591.0
Name: Population, total, dtype: float64
7.477009977519737
4059    859950.0
Name: Population, total, dtype: float64
8.056741889559982
7832    7108239.0
Name: Population, total, dtype: float64
4.421800829592654
188    1.337705e+09
Name: Population, total, dtype: float64
22.88072491195233
9596    67208808.0
Name: Population, total, dtype: float64
25.229263273607742
7979    93726624.0
Name: Population, total, dtype: float64
11.815713226043755
6852    2712650.0
Name: Population, total, dtype: float64
6.668468454369297
2491    14308740.0
Name: Population, total, dtype: float64
13.229164163765267
5774    6246274.0
Name: Population, total, dtype: float64
5.65662441277339
384    242524123.0
Name: Population, total, dtype: float64
14.941678257236434
10380    88472512.0
Name: Population, total, dtype: float64
7.986051066843864
4353    24512104.0
Name: Population, total, dtype: float64
8.158294646710072
5921    2040551.0
Name: Population, total, dtype: float64
7.2243959975537715
7097    2173170.0
Name: Population, total, dtype: float64
12.073874323977666
3912    1202843.0

Name: Population, total, dtype: float64
1.671554627471362
8959    51584663.0
Name: Population, total, dtype: float64
13.376602653554503
3961    87702670.0
Name: Population, total, dtype: float64
6.075369797775538
4255    1692149.0
Name: Population, total, dtype: float64
0.7045487645852825
6656    1250400.0
Name: Population, total, dtype: float64
17.77314109519381
6999    24221405.0
Name: Population, total, dtype: float64
1.334345995897704
5970    3948125.0
Name: Population, total, dtype: float64
4.915160018994564
5480    41350152.0
Name: Population, total, dtype: float64
6.429810864416022
2442    502384.0
Name: Population, total, dtype: float64
9.731216798847047
7440    158578261.0
Name: Population, total, dtype: float64
1.8888104037810567
6313    15167095.0
Name: Population, total, dtype: float64
4.562742237759274
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
6.303307665247074
9645    1109591.0
Name: Population, total, dtype: float64
3.4506776760268782
4059    859950.0
Name: Population, total, dtype: float64
10.466867888833395
7832    7108239.0
Name: Population, total, dtype: float64
0.0
188    1.337705e+09
Name: Population, total, dtype: float64
6.064976178290342
9596    67208808.0
Name: Population, total, dtype: float64
16.491850166941465
7979    93726624.0
Name: Population, total, dtype: float64
4.079366267355776
6852    2712650.0
Name: Population, total, dtype: float64
2.2235399715156796
2491    14308740.0
Name: Population, total, dtype: float64
6.526276993287724
5774    6246274.0
Name: Population, total, dtype: float64
11.971427609338209
384    242524123.0
Name: Population, total, dtype: float64
0.1908660611000089
10380    88472512.0
Name: Population, total, dtype: float64
6.736088634194523
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
12.650275859710893
7930    29373646.0
Name: Population, total, dtype: float64
2.5880772581995726
2050    9918242.0
Name: Population, total, dtype: float64
3.422228379275668
4647    14630417.0
Name: Population, total, dtype: float64
7.564563841092281
580    117318941.0
Name: Population, total, dtype: float64
3.581466243773116
4892    8194778.0
Name: Population, total, dtype: float64
3.3826058285310983
7342    5737723.0
Name: Population, total, dtype: float64
1.2996299255289943
5333    2817210.0
Name: Population, total, dtype: float64
9.450780427865862
2883    45918097.0
Name: Population, total, dtype: float64
21.579106306302013
5823    2097555.0
Name: Population, total, dtype: float64
25.354795049086484
6901    619428.0
Name: Population, total, dtype: float64
31.79081620863012
1511    9054332.0
Name: Population, total, dtype: float64
0.781744149183399
2295    7395599.0
Name: Population, total, dtype: float64
23.09213418524802
2099    3722084.0
Name: Population, total, dtype: float64
54.9677200635853
874    72326914.0
Name: Population, total, dtype: float64
4.761719753377898
6117    3097282.0
Name: Population, total, dtype: float64
45.582092616572304
8224    20246871.0
Name: Population, total, dtype: float64
25.506646254047965
9498    7641630.0
Name: Population, total, dtype: float64
0.5601943889231683
10086    45870700.0
Name: Population, total, dtype: float64
19.759920193881022
6754    3562045.0
Name: Population, total, dtype: float64
8.357061538298753
678    142849449.0
Name: Population, total, dtype: float64
25.433496079879475
5725    5447900.0
Name: Population, total, dtype: float64
1.8425554436422182
7489    2070739.0
Name: Population, total, dtype: float64
61.38991141875533
8518    7291436.0
Name: Population, total, dtype: float64
41.54117937101627
1070    2913021.0
Name: Population, total, dtype: float64
17.489009780456684
5431    16321872.0
Name: Population, total, dtype: float64
7.140376422449888
1364    2877311.0
Name: Population, total, dtype: float64
0.7240214865783519
1756    9490583.0
Name: Population, total, dtype: float64
24.737939711720966
6411    364511.0
Name: Population, total, dtype: float64
0.0
2001    727641.0
Name: Population, total, dtype: float64
8.418146347886099
335    1.230981e+09
Name: Population, total, dtype: float64
0.3033572045706252
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
0.0
7195    27023137.0
Name: Population, total, dtype: float64
7.2024074546853365
7685    170560182.0
Name: Population, total, dtype: float64
0.0
9057    20198353.0
Name: Population, total, dtype: float64
0.9157775518557552
2344    15605217.0
Name: Population, total, dtype: float64
3.968989225468221
3128    20401331.0
Name: Population, total, dtype: float64
1.9208513345134557
2540    19970495.0
Name: Population, total, dtype: float64
18.909578524875315
3030    4386693.0
Name: Population, total, dtype: float64
7.346575171784229
4206    1640210.0
Name: Population, total, dtype: float64
19.522573785054423
6460    15075085.0
Name: Population, total, dtype: float64
0.3721583424997925
7391    16425578.0
Name: Population, total, dtype: float64
0.056802909855569746
9694    6502952.0
Name: Population, total, dtype: float64
7.59073176126149
8469    12916229.0
Name: Population, total, dtype: float64
1.7622035139771597
2736    11887202.0
Name: Population, total, dtype: float64
8.18481388523495
8273    10246842.0
Name: Population, total, dtype: float64
10.52663693947862
2981    64523263.0
Name: Population, total, dtype: float64
1.0162414896311354
2393    8766930.0
Name: Population, total, dtype: float64
8.298913431484221
9547    46098591.0
Name: Population, total, dtype: float64
5.579924976140307
6264    21151640.0
Name: Population, total, dtype: float64
0.8342988832673711
10037    33915133.0
Name: Population, total, dtype: float64
4.3387690285648866
8616    6458720.0
Name: Population, total, dtype: float64
5.488012383964097
10576    13850033.0
Name: Population, total, dtype: float64
3.550776542715218
4696    10794170.0
Name: Population, total, dtype: float64
0.4455777247261044
8420    174776.0
Name: Population, total, dtype: float64
44.85738723787364
5382    7182390.0
Name: Population, total, dtype: float64
0.12206434560703602
5137    30762701.0
Name: Population, total, dtype: float64
0.4592900368424938
3667    84107606.0
Name: Population, total, dtype: float64
0.009362338811758084
6950    32409639.0
Name: Population, total, dtype: float64
0.19961598952752385
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
0.0
9645    1109591.0
Name: Population, total, dtype: float64
29.04328961095743
4059    859950.0
Name: Population, total, dtype: float64
16.89180070330412
7832    7108239.0
Name: Population, total, dtype: float64
94.39810971465647
188    1.337705e+09
Name: Population, total, dtype: float64
42.98083099092106
9596    67208808.0
Name: Population, total, dtype: float64
23.005072403048167
7979    93726624.0
Name: Population, total, dtype: float64
12.486054551279453
6852    2712650.0
Name: Population, total, dtype: float64
12.604976087458903
5823    2097555.0
Name: Population, total, dtype: float64
112.46186063589485
6901    619428.0
Name: Population, total, dtype: float64
96.26952497817635
1511    9054332.0
Name: Population, total, dtype: float64
104.07911250417403
2295    7395599.0
Name: Population, total, dtype: float64
349.5988429426164
2099    3722084.0
Name: Population, total, dtype: float64
169.69609867490593
874    72326914.0
Name: Population, total, dtype: float64
180.7250173607026
6117    3097282.0
Name: Population, total, dtype: float64
60.5217649981398
8224    20246871.0
Name: Population, total, dtype: float64
179.52391281624898
9498    7641630.0
Name: Population, total, dtype: float64
3.8418690229126886
10086    45870700.0
Name: Population, total, dtype: float64
90.08339232263835
6754    3562045.0
Name: Population, total, dtype: float64
17.7271498164434
678    142849449.0
Name: Population, total, dtype: float64
42.03609841061205
5725    5447900.0
Name: Population, total, dtype: float64
9.914028588070284
7489    2070739.0
Name: Population, total, dtype: float64
162.00483294207953
8518    7291436.0
Name: Population, total, dtype: float64
176.56938990874485
1070    2913021.0
Name: Population, total, dtype: float64
74.04182475837781
5431    16321872.0
Name: Population, total, dtype: float64
56.06707796029133
1364    2877311.0
Name: Population, total, dtype: float64
60.318601063158646
1756    9490583.0
Name: Population, total, dtype: float64
69.61530714676356
6411    364511.0
Name: Population, total, dtype: float64
18.93430878299678
2001    727641.0
Name: Population, total, dtype: float64
5.113581164504113
335    1.230981e+09
Name: Population, total, dtype: float64
6.894512877109306
1021    28803167.0
Name: Population, total, dtype: float64
6.849553926484507
1658    152149102.0
Name: Population, total, dtype: float64
10.179104450424571
7195    27023137.0
Name: Population, total, dtype: float64
10.179803951374948
7685    170560182.0
Name: Population, total, dtype: float64
11.355131054829728
9057    20198353.0
Name: Population, total, dtype: float64
11.703005978083102
4353    24512104.0
Name: Population, total, dtype: float64
1.747437402010533
5921    2040551.0
Name: Population, total, dtype: float64
6.986188792502574
7097    2173170.0
Name: Population, total, dtype: float64
3.106213295957968
3912    1202843.0
Name: Population, total, dtype: float64
1.0470336376175313
8959    51584663.0
Name: Population, total, dtype: float64
19.38815100842895
3961    87702670.0
Name: Population, total, dtype: float64
1.9290481229045322
4255    1692149.0
Name: Population, total, dtype: float64
5.863900882974507
6656    1250400.0
Name: Population, total, dtype: float64
66.6764918632051
6999    24221405.0
Name: Population, total, dtype: float64
0.7140365481489053
5970    3948125.0
Name: Population, total, dtype: float64
1.4324682714564838
5480    41350152.0
Name: Population, total, dtype: float64
4.089057935261653
2442    502384.0
Name: Population, total, dtype: float64
9.515248427839461
7440    158578261.0
Name: Population, total, dtype: float64
0.09932475784965687
6313    15167095.0
Name: Population, total, dtype: float64
0.8251757794006259
6607    3609543.0
Name: Population, total, dtype: float64
6.318543058302156
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
5.934792289229035
3128    20401331.0
Name: Population, total, dtype: float64
8.003767880277406
2540    19970495.0
Name: Population, total, dtype: float64
1.9033219742844296
3030    4386693.0
Name: Population, total, dtype: float64
2.4172635866131755
4206    1640210.0
Name: Population, total, dtype: float64
8.287793418521142
6460    15075085.0
Name: Population, total, dtype: float64

6.386333543707496
7391    16425578.0
Name: Population, total, dtype: float64
4.860969430870863
9694    6502952.0
Name: Population, total, dtype: float64
0.8831502393040098
8469    12916229.0
Name: Population, total, dtype: float64
3.2500862038902483
2736    11887202.0
Name: Population, total, dtype: float64
7.593447560297554
8273    10246842.0
Name: Population, total, dtype: float64
1.6089305198546442
2981    64523263.0
Name: Population, total, dtype: float64
1.470908116518917
2393    8766930.0
Name: Population, total, dtype: float64
1.0678019045385245
9547    46098591.0
Name: Population, total, dtype: float64
2.955899605558727
6264    21151640.0
Name: Population, total, dtype: float64
6.546975157368842
10037    33915133.0
Name: Population, total, dtype: float64
1.8005879970284349
8616    6458720.0
Name: Population, total, dtype: float64
21.552236035833253
10576    13850033.0
Name: Population, total, dtype: float64
0.60840545033599
4696    10794170.0
Name: Population, total, dtype: float64
3.1280123331281375
8420    174776.0
Name: Population, total, dtype: float64
0.0
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
28.473821750556716
7930    29373646.0
Name: Population, total, dtype: float64
1.677933035533544
2050    9918242.0
Name: Population, total, dtype: float64
2.804413273181005
4647    14630417.0
Name: Population, total, dtype: float64
5.290244805038716
580    117318941.0
Name: Population, total, dtype: float64
2.6528711264935616
4892    8194778.0
Name: Population, total, dtype: float64
6.938163131194294
7342    5737723.0
Name: Population, total, dtype: float64
2.36714984615101
5333    2817210.0
Name: Population, total, dtype: float64
0.0
2883    45918097.0
Name: Population, total, dtype: float64
6.9987335980846
5382    7182390.0
Name: Population, total, dtype: float64
98.59800847410365
5137    30762701.0
Name: Population, total, dtype: float64
18.311326753668375
3667    84107606.0
Name: Population, total, dtype: float64
31.433527689723416
6950    32409639.0
Name: Population, total, dtype: float64
48.752228001059
3471    851146.0
Name: Population, total, dtype: float64
27.305342586515458
10527    23606779.0
Name: Population, total, dtype: float64
25.22769775880943
2491    14308740.0
Name: Population, total, dtype: float64
12.41101475268537
5774    6246274.0
Name: Population, total, dtype: float64
8.287153513569812
384    242524123.0
Name: Population, total, dtype: float64
55.732228046692256
10380    88472512.0
Name: Population, total, dtype: float64
12.864649056202753
5823    2097555.0
Name: Population, total, dtype: float64
26.61512642442131
6901    619428.0
Name: Population, total, dtype: float64
22.213264922578276
1511    9054332.0
Name: Population, total, dtype: float64
58.44996195505458
2295    7395599.0
Name: Population, total, dtype: float64
15.897395232434926
2099    3722084.0
Name: Population, total, dtype: float64
29.881061070055296
874    72326914.0
Name: Population, total, dtype: float64
17.916802226199827
6117    3097282.0
Name: Population, total, dtype: float64
27.830802022001777
8224    20246871.0
Name: Population, total, dtype: float64
14.73792330745104
9498    7641630.0
Name: Population, total, dtype: float64
16.34789380599177
10086    45870700.0
Name: Population, total, dtype: float64
73.11123188910099
6754    3562045.0
Name: Population, total, dtype: float64
32.163064706051856
678    142849449.0
Name: Population, total, dtype: float64
26.342590317517143
5725    5447900.0
Name: Population, total, dtype: float64
27.068561796788646
7489    2070739.0
Name: Population, total, dtype: float64
113.07267142145623
8518    7291436.0
Name: Population, total, dtype: float64
10.275909041131136
1070    2913021.0
Name: Population, total, dtype: float64
56.891924285854785
5431    16321872.0
Name: Population, total, dtype: float64
52.99096707451271
1364    2877311.0
Name: Population, total, dtype: float64
33.51559086639484
1756    9490583.0
Name: Population, total, dtype: float64
63.96025120380312
6411    364511.0
Name: Population, total, dtype: float64
0.760881925928318
2001    727641.0
Name: Population, total, dtype: float64
34.96390188904108
335    1.230981e+09
Name: Population, total, dtype: float64
4.894121274464838
1021    28803167.0
Name: Population, total, dtype: float64
11.100370191535244
1658    152149102.0
Name: Population, total, dtype: float64
0.007601037777895924
7195    27023137.0
Name: Population, total, dtype: float64
12.154032252441018
7685    170560182.0
Name: Population, total, dtype: float64
1.2336212464967038
9057    20198353.0
Name: Population, total, dtype: float64
2.3950559126814617
3716    6164626.0
Name: Population, total, dtype: float64
2.2409821522060938
139    196796269.0
Name: Population, total, dtype: float64
7.878001632409726
7930    29373646.0
Name: Population, total, dtype: float64
4.5306956627835895
2050    9918242.0
Name: Population, total, dtype: float64
2.9778022314739325
4647    14630417.0
Name: Population, total, dtype: float64
6.074238233208773
580    117318941.0
Name: Population, total, dtype: float64
1.441546836808557
4892    8194778.0
Name: Population, total, dtype: float64
38.147061890328644
7342    5737723.0
Name: Population, total, dtype: float64
7.748806479031596
5333    2817210.0
Name: Population, total, dtype: float64
4.40454719238177
2883    45918097.0
Name: Population, total, dtype: float64
32.86535340375988
5382    7182390.0
Name: Population, total, dtype: float64
7.075613216320608
5137    30762701.0
Name: Population, total, dtype: float64
1.8375074633055337
3667    84107606.0
Name: Population, total, dtype: float64
29.35080127550278
6950    32409639.0
Name: Population, total, dtype: float64
21.51017758983803
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
17.61476779623532
4353    24512104.0
Name: Population, total, dtype: float64
1.5610260708334212
5921    2040551.0
Name: Population, total, dtype: float64
1.3509879841139794
7097    2173170.0
Name: Population, total, dtype: float64
2.9701665306604954
3912    1202843.0
Name: Population, total, dtype: float64
1.5482282828552503
8959    51584663.0
Name: Population, total, dtype: float64
8.389018569714914
3961    87702670.0
Name: Population, total, dtype: float64
8.126421747529095
4255    1692149.0
Name: Population, total, dtype: float64
3.944318500736193
6656    1250400.0
Name: Population, total, dtype: float64
18.582543427737274
6999    24221405.0
Name: Population, total, dtype: float64
0.354899188715895
5970    3948125.0
Name: Population, total, dtype: float64
3.1638144074305186
5480    41350152.0
Name: Population, total, dtype: float64
2.8395306103386693
2442    502384.0
Name: Population, total, dtype: float64
11.527909375829775
7440    158578261.0
Name: Population, total, dtype: float64
0.4871391984457778
6313    15167095.0
Name: Population, total, dtype: float64
1.7289600133171779
6607    3609543.0
Name: Population, total, dtype: float64
4.078825180134428
1903    9199259.0
Name: Population, total, dtype: float64
0.04362819777336699
2344    15605217.0
Name: Population, total, dtype: float64
0.05535687117994085
3128    20401331.0
Name: Population, total, dtype: float64
1.9926296976595466
2540    19970495.0
Name: Population, total, dtype: float64
6.9606666785543565
3030    4386693.0
Name: Population, total, dtype: float64
2.0916687944686294
4206    1640210.0
Name: Population, total, dtype: float64
2.6375176958649025
6460    15075085.0
Name: Population, total, dtype: float64
0.04005878573678122
7391    16425578.0
Name: Population, total, dtype: float64
1.256689520831912
9694    6502952.0
Name: Population, total, dtype: float64
0.4402362617611369
8469    12916229.0
Name: Population, total, dtype: float64
3.2576010013238426
2736    11887202.0
Name: Population, total, dtype: float64
0.5194362377226354
8273    10246842.0
Name: Population, total, dtype: float64
0.2622431201527809
2981    64523263.0
Name: Population, total, dtype: float64
0.22962352327856597
2393    8766930.0
Name: Population, total, dtype: float64
0.46730220144180107
9547    46098591.0
Name: Population, total, dtype: float64
0.42765335764174794
6264    21151640.0
Name: Population, total, dtype: float64
0.9217780409880109
10037    33915133.0
Name: Population, total, dtype: float64
0.7604672209329518
8616    6458720.0
Name: Population, total, dtype: float64
3.968655658545114
10576    13850033.0
Name: Population, total, dtype: float64
2.338407212430203
4696    10794170.0
Name: Population, total, dtype: float64
2.7300851522821374
8420    174776.0
Name: Population, total, dtype: float64
0.0
9645    1109591.0
Name: Population, total, dtype: float64
0.7584325383353578
4059    859950.0
Name: Population, total, dtype: float64
19.921158677048687
7832    7108239.0
Name: Population, total, dtype: float64
5.144749848789294
188    1.337705e+09
Name: Population, total, dtype: float64
2.2118942818010594
9596    67208808.0
Name: Population, total, dtype: float64
0.0
7979    93726624.0
Name: Population, total, dtype: float64
0.6591796384484019
6852    2712650.0
Name: Population, total, dtype: float64
17.90168588014551
2491    14308740.0
Name: Population, total, dtype: float64
2.313436251790234
5774    6246274.0
Name: Population, total, dtype: float64
0.0
384    242524123.0
Name: Population, total, dtype: float64
2.955800033396621
10380    88472512.0
Name: Population, total, dtype: float64
0.0
4353    24512104.0
Name: Population, total, dtype: float64
22.38799032346801
5921    2040551.0
Name: Population, total, dtype: float64
18.66001929713936
7097    2173170.0
Name: Population, total, dtype: float64
6.581392442125833
3912    1202843.0
Name: Population, total, dtype: float64
4.319127443746657
8959    51584663.0
Name: Population, total, dtype: float64
12.659412892544747
3961    87702670.0
Name: Population, total, dtype: float64
17.662891705707175
4255    1692149.0
Name: Population, total, dtype: float64
57.25259384103995
6656    1250400.0
Name: Population, total, dtype: float64
29.77936438168567
6999    24221405.0
Name: Population, total, dtype: float64
6.035191234881182
5970    3948125.0
Name: Population, total, dtype: float64
30.679838616679174
5480    41350152.0
Name: Population, total, dtype: float64
18.162966339858816
2442    502384.0
Name: Population, total, dtype: float64
64.83270828132791
7440    158578261.0
Name: Population, total, dtype: float64
20.013528676060073
6313    15167095.0
Name: Population, total, dtype: float64
13.96761133706433
6607    3609543.0
Name: Population, total, dtype: float64
49.56506443876327
1903    9199259.0
Name: Population, total, dtype: float64
17.60465928478318
2344    15605217.0
Name: Population, total, dtype: float64
10.337659499954643
3128    20401331.0
Name: Population, total, dtype: float64
15.45450975620893
2540    19970495.0
Name: Population, total, dtype: float64
21.368007539552487
3030    4386693.0
Name: Population, total, dtype: float64
40.5640207494361
4206    1640210.0
Name: Population, total, dtype: float64
58.96925141652631
6460    15075085.0
Name: Population, total, dtype: float64
14.100417776488325
7391    16425578.0
Name: Population, total, dtype: float64
12.198175774403134
9694    6502952.0
Name: Population, total, dtype: float64
12.462787220519884
8469    12916229.0
Name: Population, total, dtype: float64
47.894766599911456
2736    11887202.0
Name: Population, total, dtype: float64
47.04975743897589
8273    10246842.0
Name: Population, total, dtype: float64
8.896008964995543
2981    64523263.0
Name: Population, total, dtype: float64
20.953465067913882
2393    8766930.0
Name: Population, total, dtype: float64
7.142727927321341
9547    46098591.0
Name: Population, total, dtype: float64
16.82310870498264
6264    21151640.0
Name: Population, total, dtype: float64
7.476515599983514
10037    33915133.0
Name: Population, total, dtype: float64
8.868706227614501
8616    6458720.0
Name: Population, total, dtype: float64
78.61294082605791
10576    13850033.0
Name: Population, total, dtype: float64
9.66109625878719
4696    10794170.0
Name: Population, total, dtype: float64
49.500474845208636
8420    174776.0
Name: Population, total, dtype: float64
129.15611681369927
5823    2097555.0
Name: Population, total, dtype: float64
28.58042678512037
6901    619428.0
Name: Population, total, dtype: float64
26.34843282101317
1511    9054332.0
Name: Population, total, dtype: float64
28.97775990550973
2295    7395599.0
Name: Population, total, dtype: float64
42.2131808827193
2099    3722084.0
Name: Population, total, dtype: float64
86.95194936209289
874    72326914.0
Name: Population, total, dtype: float64

46.109132390358155
6117    3097282.0
Name: Population, total, dtype: float64
27.13606312187052
8224    20246871.0
Name: Population, total, dtype: float64
45.36648825529663
9498    7641630.0
Name: Population, total, dtype: float64
103.02066870865424
10086    45870700.0
Name: Population, total, dtype: float64
123.38646540082316
6754    3562045.0
Name: Population, total, dtype: float64
36.124327637445475
678    142849449.0
Name: Population, total, dtype: float64
19.147865816708656
5725    5447900.0
Name: Population, total, dtype: float64
19.348113563316346
7489    2070739.0
Name: Population, total, dtype: float64
1.4899140036722052
8518    7291436.0
Name: Population, total, dtype: float64
39.23519387716967
1070    2913021.0
Name: Population, total, dtype: float64
119.30025450801044
5431    16321872.0
Name: Population, total, dtype: float64
73.9969903849173
1364    2877311.0
Name: Population, total, dtype: float64
24.98421469707177
1756    9490583.0
Name: Population, total, dtype: float64
39.614336837900865
6411    364511.0
Name: Population, total, dtype: float64
14.140967044399671
2001    727641.0
Name: Population, total, dtype: float64
39.27010807858629
335    1.230981e+09
Name: Population, total, dtype: float64
23.739746309256518
1021    28803167.0
Name: Population, total, dtype: float64
67.31278484569377
1658    152149102.0
Name: Population, total, dtype: float64
0.19266533539718714
7195    27023137.0
Name: Population, total, dtype: float64
24.747711517507025
7685    170560182.0
Name: Population, total, dtype: float64
54.575834553719744
9057    20198353.0
Name: Population, total, dtype: float64
19.373536700660768
3716    6164626.0
Name: Population, total, dtype: float64
20.984828897821185
139    196796269.0
Name: Population, total, dtype: float64
15.845528092463988
7930    29373646.0
Name: Population, total, dtype: float64
18.61680826026888
2050    9918242.0
Name: Population, total, dtype: float64
36.87127872342966
4647    14630417.0
Name: Population, total, dtype: float64
16.44699985986721
580    117318941.0
Name: Population, total, dtype: float64
9.311454885752584
4892    8194778.0
Name: Population, total, dtype: float64
8.105702366277589
7342    5737723.0
Name: Population, total, dtype: float64
8.617168272252218
5333    2817210.0
Name: Population, total, dtype: float64
22.70228045462068
2883    45918097.0
Name: Population, total, dtype: float64
10.398803487072207
5382    7182390.0
Name: Population, total, dtype: float64
67.42636270390645
5137    30762701.0
Name: Population, total, dtype: float64
16.689469142509775
3667    84107606.0
Name: Population, total, dtype: float64
20.510185557621828
6950    32409639.0
Name: Population, total, dtype: float64
62.28868237502303
3471    851146.0
Name: Population, total, dtype: float64
39.50929515096537
10527    23606779.0
Name: Population, total, dtype: float64
20.18898950156075
9645    1109591.0
Name: Population, total, dtype: float64
26.90856103964648
4059    859950.0
Name: Population, total, dtype: float64
24.356843586684136
7832    7108239.0
Name: Population, total, dtype: float64
31.253927682096965
188    1.337705e+09
Name: Population, total, dtype: float64
26.946827527115293
9596    67208808.0
Name: Population, total, dtype: float64
14.185288957608487
7979    93726624.0
Name: Population, total, dtype: float64
7.010895886044934
6852    2712650.0
Name: Population, total, dtype: float64
17.765054282735953
2491    14308740.0
Name: Population, total, dtype: float64
13.046404095172372
5774    6246274.0
Name: Population, total, dtype: float64
1.5030207288421933
384    242524123.0
Name: Population, total, dtype: float64
17.731745698968965
10380    88472512.0
Name: Population, total, dtype: float64
12.759349247810793
5823    2097555.0
Name: Population, total, dtype: float64
14.77361002184829
6901    619428.0
Name: Population, total, dtype: float64
4.381454064899224
1511    9054332.0
Name: Population, total, dtype: float64
1.1613904929097743
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
4.936722898810304
874    72326914.0
Name: Population, total, dtype: float64
4.621754957246744
6117    3097282.0
Name: Population, total, dtype: float64
14.721771411473805
8224    20246871.0
Name: Population, total, dtype: float64
3.44874421915217
9498    7641630.0
Name: Population, total, dtype: float64
0.0
10086    45870700.0
Name: Population, total, dtype: float64
0.007567559586367652
6754    3562045.0
Name: Population, total, dtype: float64
5.449460663852911
678    142849449.0
Name: Population, total, dtype: float64
39.62751403523155
5725    5447900.0
Name: Population, total, dtype: float64
0.2512391419728917
7489    2070739.0
Name: Population, total, dtype: float64
14.080516349901234
8518    7291436.0
Name: Population, total, dtype: float64
11.895180281660878
1070    2913021.0
Name: Population, total, dtype: float64
0.0
5431    16321872.0
Name: Population, total, dtype: float64
3.471776996834589
1364    2877311.0
Name: Population, total, dtype: float64
1.628250421193428
1756    9490583.0
Name: Population, total, dtype: float64
6.46279003580479
6411    364511.0
Name: Population, total, dtype: float64
9.747006393801966
2001    727641.0
Name: Population, total, dtype: float64
4.423118034804094
335    1.230981e+09
Name: Population, total, dtype: float64
0.03059772586142335
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
0.04286987878299392
7195    27023137.0
Name: Population, total, dtype: float64
2.6549934339519896
7685    170560182.0
Name: Population, total, dtype: float64
3.27272636544608
9057    20198353.0
Name: Population, total, dtype: float64
1.1217483364061136
4353    24512104.0
Name: Population, total, dtype: float64
0.21664474904116182
5921    2040551.0
Name: Population, total, dtype: float64
0.03561268075213672
7097    2173170.0
Name: Population, total, dtype: float64
1.6969558851009527
3912    1202843.0
Name: Population, total, dtype: float64
0.0
8959    51584663.0
Name: Population, total, dtype: float64
1.1056367664939484
3961    87702670.0
Name: Population, total, dtype: float64
0.030339628370751503
4255    1692149.0
Name: Population, total, dtype: float64
0.2476229601764286
6656    1250400.0
Name: Population, total, dtype: float64
2.786808339027173
6999    24221405.0
Name: Population, total, dtype: float64
0.017979528371896283
5970    3948125.0
Name: Population, total, dtype: float64
0.07551877874384838
5480    41350152.0
Name: Population, total, dtype: float64
0.36955728443962194
2442    502384.0
Name: Population, total, dtype: float64
6.070773313969825
7440    158578261.0
Name: Population, total, dtype: float64
0.22433097954548611
6313    15167095.0
Name: Population, total, dtype: float64
0.11640409604315172
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
0.18485815883079848
3128    20401331.0
Name: Population, total, dtype: float64
6.135930524700172
2540    19970495.0
Name: Population, total, dtype: float64
0.33594878561651914
3030    4386693.0
Name: Population, total, dtype: float64
2.5427315276085403
4206    1640210.0
Name: Population, total, dtype: float64
0.40600145149404093
6460    15075085.0
Name: Population, total, dtype: float64
0.02064965913679774
7391    16425578.0
Name: Population, total, dtype: float64
0.06710549437038635
9694    6502952.0
Name: Population, total, dtype: float64
0.12910869958215565
8469    12916229.0
Name: Population, total, dtype: float64
0.11273292621396411
2736    11887202.0
Name: Population, total, dtype: float64
0.0
8273    10246842.0
Name: Population, total, dtype: float64
0.0055989797679323015
2981    64523263.0
Name: Population, total, dtype: float64
0.008373881108529782
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
0.02767871590772378
6264    21151640.0
Name: Population, total, dtype: float64
0.017840723934991448
10037    33915133.0
Name: Population, total, dtype: float64
0.015052112108534058
8616    6458720.0
Name: Population, total, dtype: float64
0.06706629395634102
10576    13850033.0
Name: Population, total, dtype: float64
0.008111800535586421
4696    10794170.0
Name: Population, total, dtype: float64
0.019657949208900745
8420    174776.0
Name: Population, total, dtype: float64
7.979141370771065
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
77.27735400459927
7930    29373646.0
Name: Population, total, dtype: float64
9.488279908460655
2050    9918242.0
Name: Population, total, dtype: float64
2.62955819013773
4647    14630417.0
Name: Population, total, dtype: float64

8.161020605551073
580    117318941.0
Name: Population, total, dtype: float64
3.863854396702487
4892    8194778.0
Name: Population, total, dtype: float64
1.1975354831303315
7342    5737723.0
Name: Population, total, dtype: float64
0.8406045851253112
5333    2817210.0
Name: Population, total, dtype: float64
1.7759348947291411
2883    45918097.0
Name: Population, total, dtype: float64
0.0
5382    7182390.0
Name: Population, total, dtype: float64
0.8663022542015689
5137    30762701.0
Name: Population, total, dtype: float64
1.5166328656977528
3667    84107606.0
Name: Population, total, dtype: float64
1.0135759090314396
6950    32409639.0
Name: Population, total, dtype: float64
0.0
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
0.4420660869883543
9645    1109591.0
Name: Population, total, dtype: float64
0.0
4059    859950.0
Name: Population, total, dtype: float64
0.8654534571260898
7832    7108239.0
Name: Population, total, dtype: float64
0.0
188    1.337705e+09
Name: Population, total, dtype: float64
6.444022829968725
9596    67208808.0
Name: Population, total, dtype: float64
0.061343264659059794
7979    93726624.0
Name: Population, total, dtype: float64
0.00484406298480117
6852    2712650.0
Name: Population, total, dtype: float64
0.478384029792081
2491    14308740.0
Name: Population, total, dtype: float64
0.5264161776205306
5774    6246274.0
Name: Population, total, dtype: float64
0.2952383860788664
384    242524123.0
Name: Population, total, dtype: float64
0.1867221374250025
10380    88472512.0
Name: Population, total, dtype: float64
0.8474244926078971
4353    24512104.0
Name: Population, total, dtype: float64
0.0
5921    2040551.0
Name: Population, total, dtype: float64
0.0
7097    2173170.0
Name: Population, total, dtype: float64
0.0
3912    1202843.0
Name: Population, total, dtype: float64
0.0
8959    51584663.0
Name: Population, total, dtype: float64
0.0
3961    87702670.0
Name: Population, total, dtype: float64
0.0
4255    1692149.0
Name: Population, total, dtype: float64
0.0034007703825829883
6656    1250400.0
Name: Population, total, dtype: float64
0.0
6999    24221405.0
Name: Population, total, dtype: float64
0.0
5970    3948125.0
Name: Population, total, dtype: float64
0.0
5480    41350152.0
Name: Population, total, dtype: float64
0.8843024873090722
2442    502384.0
Name: Population, total, dtype: float64
0.0
7440    158578261.0
Name: Population, total, dtype: float64
0.0
6313    15167095.0
Name: Population, total, dtype: float64
0.0
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
3.9621728612286744
3128    20401331.0
Name: Population, total, dtype: float64
0.0
2540    19970495.0
Name: Population, total, dtype: float64
0.30207498264023963
3030    4386693.0
Name: Population, total, dtype: float64
0.07938505191174844
4206    1640210.0
Name: Population, total, dtype: float64
0.3345370984593141
6460    15075085.0
Name: Population, total, dtype: float64
2.297272883868617
7391    16425578.0
Name: Population, total, dtype: float64
2.9391011293038323e-05
9694    6502952.0
Name: Population, total, dtype: float64
0.691343633539614
8469    12916229.0
Name: Population, total, dtype: float64
0.0
2736    11887202.0
Name: Population, total, dtype: float64
0.0
8273    10246842.0
Name: Population, total, dtype: float64
0.0
2981    64523263.0
Name: Population, total, dtype: float64
0.06682151648065764
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
0.0
6264    21151640.0
Name: Population, total, dtype: float64
0.0
10037    33915133.0
Name: Population, total, dtype: float64
0.0
8616    6458720.0
Name: Population, total, dtype: float64
0.0
10576    13850033.0
Name: Population, total, dtype: float64
0.7446907527041845
4696    10794170.0
Name: Population, total, dtype: float64
2.8395143233587308
8420    174776.0
Name: Population, total, dtype: float64
0.0
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
0.0
7930    29373646.0
Name: Population, total, dtype: float64
0.0
2050    9918242.0
Name: Population, total, dtype: float64
0.0
4647    14630417.0
Name: Population, total, dtype: float64
0.0
580    117318941.0
Name: Population, total, dtype: float64
0.0
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
0.0018994670595912583
5333    2817210.0
Name: Population, total, dtype: float64
0.0
2883    45918097.0
Name: Population, total, dtype: float64
0.0
5382    7182390.0
Name: Population, total, dtype: float64
0.0
9645    1109591.0
Name: Population, total, dtype: float64
0.0
4059    859950.0
Name: Population, total, dtype: float64
0.0
7832    7108239.0
Name: Population, total, dtype: float64
166.84063272871646
188    1.337705e+09
Name: Population, total, dtype: float64
0.0
9596    67208808.0
Name: Population, total, dtype: float64
0.0
7979    93726624.0
Name: Population, total, dtype: float64
0.0
6852    2712650.0
Name: Population, total, dtype: float64
0.0
2491    14308740.0
Name: Population, total, dtype: float64
0.0
5774    6246274.0
Name: Population, total, dtype: float64
0.0
384    242524123.0
Name: Population, total, dtype: float64
0.37101134419895054
10380    88472512.0
Name: Population, total, dtype: float64
0.0
5823    2097555.0
Name: Population, total, dtype: float64
0.0
6901    619428.0
Name: Population, total, dtype: float64
0.0
1511    9054332.0
Name: Population, total, dtype: float64
0.0
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
0.0
874    72326914.0
Name: Population, total, dtype: float64
0.001115880616404238
6117    3097282.0
Name: Population, total, dtype: float64
0.0
8224    20246871.0
Name: Population, total, dtype: float64
0.0
9498    7641630.0
Name: Population, total, dtype: float64
0.0
10086    45870700.0
Name: Population, total, dtype: float64
0.0
6754    3562045.0
Name: Population, total, dtype: float64
0.0
678    142849449.0
Name: Population, total, dtype: float64
0.0
5725    5447900.0
Name: Population, total, dtype: float64
0.0
7489    2070739.0
Name: Population, total, dtype: float64
0.0
8518    7291436.0
Name: Population, total, dtype: float64
0.0
1070    2913021.0
Name: Population, total, dtype: float64
0.0
5431    16321872.0
Name: Population, total, dtype: float64
0.0
1364    2877311.0
Name: Population, total, dtype: float64
0.0
1756    9490583.0
Name: Population, total, dtype: float64
0.0
6411    364511.0
Name: Population, total, dtype: float64
0.0
2001    727641.0
Name: Population, total, dtype: float64
15.26590982007644
335    1.230981e+09
Name: Population, total, dtype: float64
0.0
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
10.456485277710069
7195    27023137.0
Name: Population, total, dtype: float64
0.0
7685    170560182.0
Name: Population, total, dtype: float64
0.0
9057    20198353.0
Name: Population, total, dtype: float64
8.28384925424352
5137    30762701.0
Name: Population, total, dtype: float64
0.0
3667    84107606.0
Name: Population, total, dtype: float64
0.0
6950    32409639.0
Name: Population, total, dtype: float64
1.541541386949676
3471    851146.0
Name: Population, total, dtype: float64
157.0757428920833
10527    23606779.0
Name: Population, total, dtype: float64
165.5168280710172
4353    24512104.0
Name: Population, total, dtype: float64
0.24442380794926472
5921    2040551.0
Name: Population, total, dtype: float64
0.24162378805855814
7097    2173170.0
Name: Population, total, dtype: float64
1.2546497805526369
3912    1202843.0
Name: Population, total, dtype: float64
1.1854060511525748
8959    51584663.0
Name: Population, total, dtype: float64
2.8714997002391547
3961    87702670.0
Name: Population, total, dtype: float64
0.4413133201955665
4255    1692149.0
Name: Population, total, dtype: float64
0.28987624792195354
6656    1250400.0
Name: Population, total, dtype: float64
1.6846059653382803
6999    24221405.0
Name: Population, total, dtype: float64
0.05746977229692856
5970    3948125.0
Name: Population, total, dtype: float64
0.23454763937442846
5480    41350152.0
Name: Population, total, dtype: float64
0.9267964647577586
2442    502384.0
Name: Population, total, dtype: float64
2.5157385122663842
7440    158578261.0
Name: Population, total, dtype: float64
0.06501376813175702
6313    15167095.0
Name: Population, total, dtype: float64
0.7280860298975959
6607    3609543.0
Name: Population, total, dtype: float64
0.16649933793015348
1903    9199259.0

Name: Population, total, dtype: float64
0.04515059214515628
2344    15605217.0
Name: Population, total, dtype: float64
0.03265428374652388
3128    20401331.0
Name: Population, total, dtype: float64
1.4124367696351168
2540    19970495.0
Name: Population, total, dtype: float64
0.14464794120308797
3030    4386693.0
Name: Population, total, dtype: float64
0.1801524704399393
4206    1640210.0
Name: Population, total, dtype: float64
1.0799494144433361
6460    15075085.0
Name: Population, total, dtype: float64
0.05646796622889182
7391    16425578.0
Name: Population, total, dtype: float64
0.0010744714318087457
9694    6502952.0
Name: Population, total, dtype: float64
1.0108982422376331
8469    12916229.0
Name: Population, total, dtype: float64
0.0
2736    11887202.0
Name: Population, total, dtype: float64
0.48544856047609863
8273    10246842.0
Name: Population, total, dtype: float64
0.39137369301515157
2981    64523263.0
Name: Population, total, dtype: float64
0.15308108139270168
2393    8766930.0
Name: Population, total, dtype: float64
0.39431789594501987
9547    46098591.0
Name: Population, total, dtype: float64
0.31491267289414915
6264    21151640.0
Name: Population, total, dtype: float64
0.22273289044562147
10037    33915133.0
Name: Population, total, dtype: float64
0.0
8616    6458720.0
Name: Population, total, dtype: float64
0.7668366509293262
10576    13850033.0
Name: Population, total, dtype: float64
0.5288888575324872
4696    10794170.0
Name: Population, total, dtype: float64
0.849535496743275
8420    174776.0
Name: Population, total, dtype: float64
0.0
5823    2097555.0
Name: Population, total, dtype: float64
20.717563142751793
6901    619428.0
Name: Population, total, dtype: float64
9.54250103080971
1511    9054332.0
Name: Population, total, dtype: float64
0.5721052021365648
2295    7395599.0
Name: Population, total, dtype: float64
24.966940476986508
2099    3722084.0
Name: Population, total, dtype: float64
63.62030723539825
874    72326914.0
Name: Population, total, dtype: float64
9.009892143802507
6117    3097282.0
Name: Population, total, dtype: float64
6.496960508795823
8224    20246871.0
Name: Population, total, dtype: float64
23.24121344086125
9498    7641630.0
Name: Population, total, dtype: float64
7.829297186910562
10086    45870700.0
Name: Population, total, dtype: float64
31.44550262784968
6754    3562045.0
Name: Population, total, dtype: float64
6.2505736220319905
678    142849449.0
Name: Population, total, dtype: float64
16.06624859739371
5725    5447900.0
Name: Population, total, dtype: float64
0.28369882187576656
7489    2070739.0
Name: Population, total, dtype: float64
15.185177053590138
8518    7291436.0
Name: Population, total, dtype: float64
26.49196786882351
1070    2913021.0
Name: Population, total, dtype: float64
17.110269008487613
5431    16321872.0
Name: Population, total, dtype: float64
42.561892181118985
1364    2877311.0
Name: Population, total, dtype: float64
9.304535248466761
1756    9490583.0
Name: Population, total, dtype: float64
11.485555630875043
6411    364511.0
Name: Population, total, dtype: float64
1.2197200723561843
2001    727641.0
Name: Population, total, dtype: float64
0.7492783578318227
335    1.230981e+09
Name: Population, total, dtype: float64
0.14901613273990472
1021    28803167.0
Name: Population, total, dtype: float64
0.6607430576203545
1658    152149102.0
Name: Population, total, dtype: float64
20.671268170215374
7195    27023137.0
Name: Population, total, dtype: float64
0.0
7685    170560182.0
Name: Population, total, dtype: float64
2.28669306200168
9057    20198353.0
Name: Population, total, dtype: float64
0.8052273306984612
9645    1109591.0
Name: Population, total, dtype: float64
0.0
4059    859950.0
Name: Population, total, dtype: float64
1.4337428700429027
7832    7108239.0
Name: Population, total, dtype: float64
0.48739536305141473
188    1.337705e+09
Name: Population, total, dtype: float64
5.875390387435834
9596    67208808.0
Name: Population, total, dtype: float64
5.823181930351926
7979    93726624.0
Name: Population, total, dtype: float64
0.0
6852    2712650.0
Name: Population, total, dtype: float64
4.798886063618169
2491    14308740.0
Name: Population, total, dtype: float64
1.127686148540221
5774    6246274.0
Name: Population, total, dtype: float64
0.8835734239416547
384    242524123.0
Name: Population, total, dtype: float64
0.0
10380    88472512.0
Name: Population, total, dtype: float64
0.0
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
0.0019969977137377615
7930    29373646.0
Name: Population, total, dtype: float64
3.444451178048893
2050    9918242.0
Name: Population, total, dtype: float64
5.265102551711317
4647    14630417.0
Name: Population, total, dtype: float64
3.161897429312661
580    117318941.0
Name: Population, total, dtype: float64
3.402700484705845
4892    8194778.0
Name: Population, total, dtype: float64
0.8506734664382718
7342    5737723.0
Name: Population, total, dtype: float64
0.11490917466682286
5333    2817210.0
Name: Population, total, dtype: float64
3.3689740787923994
2883    45918097.0
Name: Population, total, dtype: float64
0.0
5382    7182390.0
Name: Population, total, dtype: float64
3.281110436666266
5137    30762701.0
Name: Population, total, dtype: float64
5.918954483023615
3667    84107606.0
Name: Population, total, dtype: float64
3.980350439321111
6950    32409639.0
Name: Population, total, dtype: float64
4.574984309845567
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
3.5239089483828048
4353    24512104.0
Name: Population, total, dtype: float64
61.69917225712575
5921    2040551.0
Name: Population, total, dtype: float64
62.788031829944615
7097    2173170.0
Name: Population, total, dtype: float64
66.95252393956349
3912    1202843.0
Name: Population, total, dtype: float64
26.564743366751213
8959    51584663.0
Name: Population, total, dtype: float64
111.42270517922779
3961    87702670.0
Name: Population, total, dtype: float64
56.12025621559745
4255    1692149.0
Name: Population, total, dtype: float64
77.15943994288166
6656    1250400.0
Name: Population, total, dtype: float64
94.42856624186435
6999    24221405.0
Name: Population, total, dtype: float64
26.981405102757552
5970    3948125.0
Name: Population, total, dtype: float64
28.92608381685967
5480    41350152.0
Name: Population, total, dtype: float64
47.934413543658984
2442    502384.0
Name: Population, total, dtype: float64
40.17337868455472
7440    158578261.0
Name: Population, total, dtype: float64
6.9904027899367165
6313    15167095.0
Name: Population, total, dtype: float64
13.407845796868587
6607    3609543.0
Name: Population, total, dtype: float64
74.75538809189034
1903    9199259.0
Name: Population, total, dtype: float64
42.39333419974389
2344    15605217.0
Name: Population, total, dtype: float64
30.686200022877326
3128    20401331.0
Name: Population, total, dtype: float64
54.96697143772374
2540    19970495.0
Name: Population, total, dtype: float64
39.56034545281782
3030    4386693.0
Name: Population, total, dtype: float64
31.566189807818855
4206    1640210.0
Name: Population, total, dtype: float64
66.47744454676968
6460    15075085.0
Name: Population, total, dtype: float64
24.018723395425827
7391    16425578.0
Name: Population, total, dtype: float64
13.415031045733203
9694    6502952.0
Name: Population, total, dtype: float64
13.568212244129231
8469    12916229.0
Name: Population, total, dtype: float64
17.220810938158245
2736    11887202.0
Name: Population, total, dtype: float64
27.20359759407839
8273    10246842.0
Name: Population, total, dtype: float64
27.41505308602633
2981    64523263.0
Name: Population, total, dtype: float64
7.853088191443847
2393    8766930.0
Name: Population, total, dtype: float64
9.995400897923522
9547    46098591.0
Name: Population, total, dtype: float64
19.697556321858578
6264    21151640.0
Name: Population, total, dtype: float64
6.3514698091205695
10037    33915133.0
Name: Population, total, dtype: float64
23.524403702249277
8616    6458720.0
Name: Population, total, dtype: float64
45.48887696150192
10576    13850033.0
Name: Population, total, dtype: float64
12.179371359197608
4696    10794170.0
Name: Population, total, dtype: float64
14.517997581126957
8420    174776.0
Name: Population, total, dtype: float64
118.67000257954463
9645    1109591.0
Name: Population, total, dtype: float64
29.538197698101282
4059    859950.0
Name: Population, total, dtype: float64
51.74078550681219
7832    7108239.0
Name: Population, total, dtype: float64
43.111183755087815
188    1.337705e+09
Name: Population, total, dtype: float64
157.91832923069757
9596    67208808.0
Name: Population, total, dtype: float64
69.53448845727719
7979    93726624.0
Name: Population, total, dtype: float64
21.389892044450782
6852    2712650.0
Name: Population, total, dtype: float64
97.87018154043996
2491    14308740.0
Name: Population, total, dtype: float64
4.9403637790938655
5774    6246274.0
Name: Population, total, dtype: float64
27.37891539679263
384    242524123.0
Name: Population, total, dtype: float64
27.592252130311532
10380    88472512.0
Name: Population, total, dtype: float64
28.562361586775168
5823    2097555.0
Name: Population, total, dtype: float64
194.85394404118196
6901    619428.0

Name: Population, total, dtype: float64
202.31923785777943
1511    9054332.0
Name: Population, total, dtype: float64
148.31492511361955
2295    7395599.0
Name: Population, total, dtype: float64
125.88962546005564
2099    3722084.0
Name: Population, total, dtype: float64
288.75241869948763
874    72326914.0
Name: Population, total, dtype: float64
139.4127287673571
6117    3097282.0
Name: Population, total, dtype: float64
246.82935024924802
8224    20246871.0
Name: Population, total, dtype: float64
116.517639956957
9498    7641630.0
Name: Population, total, dtype: float64
30.959752320860797
10086    45870700.0
Name: Population, total, dtype: float64
173.9763994755857
6754    3562045.0
Name: Population, total, dtype: float64
258.9129580930659
678    142849449.0
Name: Population, total, dtype: float64
453.518837374696
5725    5447900.0
Name: Population, total, dtype: float64
99.30891650975038
7489    2070739.0
Name: Population, total, dtype: float64
249.42378565520374
8518    7291436.0
Name: Population, total, dtype: float64
144.08294700738338
1070    2913021.0
Name: Population, total, dtype: float64
1.259133669018313
5431    16321872.0
Name: Population, total, dtype: float64
138.56730482846132
1364    2877311.0
Name: Population, total, dtype: float64
37.36210117024255
1756    9490583.0
Name: Population, total, dtype: float64
361.98947558402307
6411    364511.0
Name: Population, total, dtype: float64
30.180754956294663
2001    727641.0
Name: Population, total, dtype: float64
84.71333651496361
335    1.230981e+09
Name: Population, total, dtype: float64
40.65008073918485
1021    28803167.0
Name: Population, total, dtype: float64
49.84619803673751
1658    152149102.0
Name: Population, total, dtype: float64
33.33412636011962
7195    27023137.0
Name: Population, total, dtype: float64
30.948962331274206
7685    170560182.0
Name: Population, total, dtype: float64
35.478194701578005
9057    20198353.0
Name: Population, total, dtype: float64
47.702534971582935
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
15.946915279455647
7930    29373646.0
Name: Population, total, dtype: float64
100.22049934977264
2050    9918242.0
Name: Population, total, dtype: float64
74.79887442559989
4647    14630417.0
Name: Population, total, dtype: float64
1.8708200950208465
580    117318941.0
Name: Population, total, dtype: float64
9.847890489760244
4892    8194778.0
Name: Population, total, dtype: float64
18.000575956984722
7342    5737723.0
Name: Population, total, dtype: float64
11.790672640893963
5333    2817210.0
Name: Population, total, dtype: float64
103.74145845343755
2883    45918097.0
Name: Population, total, dtype: float64
16.5308769687955
5382    7182390.0
Name: Population, total, dtype: float64
96.85570110445816
5137    30762701.0
Name: Population, total, dtype: float64
146.75842029810673
3667    84107606.0
Name: Population, total, dtype: float64
53.057999119324954
6950    32409639.0
Name: Population, total, dtype: float64
73.50483023654306
3471    851146.0
Name: Population, total, dtype: float64
36.82296465924214
10527    23606779.0
Name: Population, total, dtype: float64
67.5487535512116
9645    1109591.0
Name: Population, total, dtype: float64
14.497797244545858
4059    859950.0
Name: Population, total, dtype: float64
16.883359702933408
7832    7108239.0
Name: Population, total, dtype: float64
35.39190589473794
188    1.337705e+09
Name: Population, total, dtype: float64
8.762818552458112
9596    67208808.0
Name: Population, total, dtype: float64
23.182855609010854
7979    93726624.0
Name: Population, total, dtype: float64
11.287107816093636
6852    2712650.0
Name: Population, total, dtype: float64
8.75421774773917
2491    14308740.0
Name: Population, total, dtype: float64
9.589636751034881
5774    6246274.0
Name: Population, total, dtype: float64
1.6184453984744052
384    242524123.0
Name: Population, total, dtype: float64
15.274222878294953
10380    88472512.0
Name: Population, total, dtype: float64
4.6071325783410275
3716    6164626.0
Name: Population, total, dtype: float64
19.028260381693986
139    196796269.0
Name: Population, total, dtype: float64
4.073314985629586
7930    29373646.0
Name: Population, total, dtype: float64
29.063148808261513
2050    9918242.0
Name: Population, total, dtype: float64
35.57735951168242
4647    14630417.0
Name: Population, total, dtype: float64
35.69149096107322
580    117318941.0
Name: Population, total, dtype: float64
6.644999128938511
4892    8194778.0
Name: Population, total, dtype: float64
23.504096970363555
7342    5737723.0
Name: Population, total, dtype: float64
11.046155974015017
5333    2817210.0
Name: Population, total, dtype: float64
16.975536546773665
2883    45918097.0
Name: Population, total, dtype: float64
0.0
4353    24512104.0
Name: Population, total, dtype: float64
6.418509052779977
5921    2040551.0
Name: Population, total, dtype: float64
15.389388990616334
7097    2173170.0
Name: Population, total, dtype: float64
13.052877651721545
3912    1202843.0
Name: Population, total, dtype: float64
11.041227171984177
8959    51584663.0
Name: Population, total, dtype: float64
16.65773356226495
3961    87702670.0
Name: Population, total, dtype: float64
7.809407194289694
4255    1692149.0
Name: Population, total, dtype: float64
23.524623077649718
6656    1250400.0
Name: Population, total, dtype: float64
5.275159989198222
6999    24221405.0
Name: Population, total, dtype: float64
5.209210209548077
5970    3948125.0
Name: Population, total, dtype: float64
3.6860967423314976
5480    41350152.0
Name: Population, total, dtype: float64
29.477554637786174
2442    502384.0
Name: Population, total, dtype: float64
17.109301705894755
7440    158578261.0
Name: Population, total, dtype: float64
4.007195289000313
6313    15167095.0
Name: Population, total, dtype: float64
16.65331229659028
6607    3609543.0
Name: Population, total, dtype: float64
74.77922894503936
1903    9199259.0
Name: Population, total, dtype: float64
5.576984785097789
2344    15605217.0
Name: Population, total, dtype: float64
9.090591025058199
3128    20401331.0
Name: Population, total, dtype: float64
6.783708231448757
2540    19970495.0
Name: Population, total, dtype: float64
4.78683002529851
3030    4386693.0
Name: Population, total, dtype: float64
9.722492181828422
4206    1640210.0
Name: Population, total, dtype: float64
10.261198663042245
6460    15075085.0
Name: Population, total, dtype: float64
20.81929829583781
7391    16425578.0
Name: Population, total, dtype: float64
3.995742935179874
9694    6502952.0
Name: Population, total, dtype: float64
4.060502894747139
8469    12916229.0
Name: Population, total, dtype: float64
29.08689916063406
2736    11887202.0
Name: Population, total, dtype: float64
50.864583404335534
8273    10246842.0
Name: Population, total, dtype: float64
7.678149554289211
2981    64523263.0
Name: Population, total, dtype: float64
4.856956975297838
2393    8766930.0
Name: Population, total, dtype: float64
2.4655076403902885
9547    46098591.0
Name: Population, total, dtype: float64
18.629864902515994
6264    21151640.0
Name: Population, total, dtype: float64
5.541780326306453
10037    33915133.0
Name: Population, total, dtype: float64
19.28938430267073
8616    6458720.0
Name: Population, total, dtype: float64
8.585699271328933
10576    13850033.0
Name: Population, total, dtype: float64
9.20340652708558
4696    10794170.0
Name: Population, total, dtype: float64
11.492981801150615
8420    174776.0
Name: Population, total, dtype: float64
44.46186606967469
5823    2097555.0
Name: Population, total, dtype: float64
23.511948081634667
6901    619428.0
Name: Population, total, dtype: float64
17.642865299161357
1511    9054332.0
Name: Population, total, dtype: float64
41.485411083488316
2295    7395599.0
Name: Population, total, dtype: float64
15.804245889004857
2099    3722084.0
Name: Population, total, dtype: float64
50.60804517778883
874    72326914.0
Name: Population, total, dtype: float64
0.0
6117    3097282.0
Name: Population, total, dtype: float64
43.06420999239114
8224    20246871.0
Name: Population, total, dtype: float64
19.094892496528043
9498    7641630.0
Name: Population, total, dtype: float64

45.173073143031765
10086    45870700.0
Name: Population, total, dtype: float64
77.33498164350918
6754    3562045.0
Name: Population, total, dtype: float64
25.239995500849613
678    142849449.0
Name: Population, total, dtype: float64
46.97852762414173
5725    5447900.0
Name: Population, total, dtype: float64
108.94628139234729
7489    2070739.0
Name: Population, total, dtype: float64
46.34438417662472
8518    7291436.0
Name: Population, total, dtype: float64
21.820228225451846
1070    2913021.0
Name: Population, total, dtype: float64
25.263043789421726
5431    16321872.0
Name: Population, total, dtype: float64
76.96438338209872
1364    2877311.0
Name: Population, total, dtype: float64
0.0004921271538646599
1756    9490583.0
Name: Population, total, dtype: float64
59.24351039070714
6411    364511.0
Name: Population, total, dtype: float64
12.170716498193816
2001    727641.0
Name: Population, total, dtype: float64
8.945363389287326
335    1.230981e+09
Name: Population, total, dtype: float64
15.623050817221662
1021    28803167.0
Name: Population, total, dtype: float64
14.831435148658306
1658    152149102.0
Name: Population, total, dtype: float64
5.110213037877804
7195    27023137.0
Name: Population, total, dtype: float64
11.90932593034919
7685    170560182.0
Name: Population, total, dtype: float64
40.222482807743674
9057    20198353.0
Name: Population, total, dtype: float64
27.143367066445176
5382    7182390.0
Name: Population, total, dtype: float64
29.877706042068745
5137    30762701.0
Name: Population, total, dtype: float64
14.609926156339464
3667    84107606.0
Name: Population, total, dtype: float64
14.937433517715196
6950    32409639.0
Name: Population, total, dtype: float64
36.776123773263734
3471    851146.0
Name: Population, total, dtype: float64
49.981508297315685
10527    23606779.0
Name: Population, total, dtype: float64
46.666760360385226
4353    24512104.0
Name: Population, total, dtype: float64
0.10121713158570834
5921    2040551.0
Name: Population, total, dtype: float64
0.012620807579631285
7097    2173170.0
Name: Population, total, dtype: float64
6.449660968605503
3912    1202843.0
Name: Population, total, dtype: float64
1.822631457489097
8959    51584663.0
Name: Population, total, dtype: float64
2.5643641079384243
3961    87702670.0
Name: Population, total, dtype: float64
0.004233917201495899
4255    1692149.0
Name: Population, total, dtype: float64
0.2206678483422802
6656    1250400.0
Name: Population, total, dtype: float64
2.8778966271761592
6999    24221405.0
Name: Population, total, dtype: float64
0.08803895581383765
5970    3948125.0
Name: Population, total, dtype: float64
0.0
5480    41350152.0
Name: Population, total, dtype: float64
0.40255873588256824
2442    502384.0
Name: Population, total, dtype: float64
5.126254744470958
7440    158578261.0
Name: Population, total, dtype: float64
2.507202335353159
6313    15167095.0
Name: Population, total, dtype: float64
0.048859529228753994
6607    3609543.0
Name: Population, total, dtype: float64
1.5004542071344384
1903    9199259.0
Name: Population, total, dtype: float64
0.0
2344    15605217.0
Name: Population, total, dtype: float64
0.04753383544520265
3128    20401331.0
Name: Population, total, dtype: float64
0.3403842180526577
2540    19970495.0
Name: Population, total, dtype: float64
0.07821369246963313
3030    4386693.0
Name: Population, total, dtype: float64
0.2945216424776259
4206    1640210.0
Name: Population, total, dtype: float64
0.0
6460    15075085.0
Name: Population, total, dtype: float64
0.0
7391    16425578.0
Name: Population, total, dtype: float64
0.0
9694    6502952.0
Name: Population, total, dtype: float64
0.27533838186649273
8469    12916229.0
Name: Population, total, dtype: float64
0.0
2736    11887202.0
Name: Population, total, dtype: float64
0.0391723420478254
8273    10246842.0
Name: Population, total, dtype: float64
0.0
2981    64523263.0
Name: Population, total, dtype: float64
0.012375685174640936
2393    8766930.0
Name: Population, total, dtype: float64
0.0
9547    46098591.0
Name: Population, total, dtype: float64
0.018654790566399074
6264    21151640.0
Name: Population, total, dtype: float64
0.00016437272147104207
10037    33915133.0
Name: Population, total, dtype: float64
0.0301042242288606
8616    6458720.0
Name: Population, total, dtype: float64
0.605304276371694
10576    13850033.0
Name: Population, total, dtype: float64
0.02668965242081746
4696    10794170.0
Name: Population, total, dtype: float64
0.005723460118232374
8420    174776.0
Name: Population, total, dtype: float64
0.39329803308560096
5823    2097555.0
Name: Population, total, dtype: float64
43.49165772284042
6901    619428.0
Name: Population, total, dtype: float64
15.05170473991547
1511    9054332.0
Name: Population, total, dtype: float64
0.8124041187449644
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
8.696665142377286
874    72326914.0
Name: Population, total, dtype: float64
11.302661386497
6117    3097282.0
Name: Population, total, dtype: float64
27.701663310178446
8224    20246871.0
Name: Population, total, dtype: float64
11.286950513205
9498    7641630.0
Name: Population, total, dtype: float64
0.0
10086    45870700.0
Name: Population, total, dtype: float64
11.32506134937544
6754    3562045.0
Name: Population, total, dtype: float64
27.034643500257783
678    142849449.0
Name: Population, total, dtype: float64
33.336498507585105
5725    5447900.0
Name: Population, total, dtype: float64
0.7822384580991397
7489    2070739.0
Name: Population, total, dtype: float64
7.09051308533159
8518    7291436.0
Name: Population, total, dtype: float64
38.46603133804396
1070    2913021.0
Name: Population, total, dtype: float64
10.127432400848983
5431    16321872.0
Name: Population, total, dtype: float64
7.783843140932768
1364    2877311.0
Name: Population, total, dtype: float64
1.2462430051385507
1756    9490583.0
Name: Population, total, dtype: float64
9.694185289614358
9645    1109591.0
Name: Population, total, dtype: float64
0.0026223038450768907
4059    859950.0
Name: Population, total, dtype: float64
1.2837902571810804
7832    7108239.0
Name: Population, total, dtype: float64
0.0
188    1.337705e+09
Name: Population, total, dtype: float64
2.3709139805790755
9596    67208808.0
Name: Population, total, dtype: float64
1.371585951821904
7979    93726624.0
Name: Population, total, dtype: float64
0.4468641227025741
6852    2712650.0
Name: Population, total, dtype: float64
0.7566588546094921
2491    14308740.0
Name: Population, total, dtype: float64
0.599025325536539
5774    6246274.0
Name: Population, total, dtype: float64
0.3292151674743723
384    242524123.0
Name: Population, total, dtype: float64
0.0
10380    88472512.0
Name: Population, total, dtype: float64
0.5958021271521072
3716    6164626.0
Name: Population, total, dtype: float64
1.212475757292945
139    196796269.0
Name: Population, total, dtype: float64
13.80138719820664
7930    29373646.0
Name: Population, total, dtype: float64
18.777225679958853
2050    9918242.0
Name: Population, total, dtype: float64
0.0
4647    14630417.0
Name: Population, total, dtype: float64
2.3519978366021674
580    117318941.0
Name: Population, total, dtype: float64
3.0143920864593925
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
1.8184574077228077
5333    2817210.0
Name: Population, total, dtype: float64
5.467311681266503
2883    45918097.0
Name: Population, total, dtype: float64
6.529696611791925
5382    7182390.0
Name: Population, total, dtype: float64
4.226674583444063
5137    30762701.0
Name: Population, total, dtype: float64
1.5916150102250992
3667    84107606.0
Name: Population, total, dtype: float64
1.0130449125620271
6950    32409639.0
Name: Population, total, dtype: float64
5.588327775115349
3471    851146.0
Name: Population, total, dtype: float64
0.0
10527    23606779.0
Name: Population, total, dtype: float64
0.0
6411    364511.0
Name: Population, total, dtype: float64
1.7590798955265405
2001    727641.0
Name: Population, total, dtype: float64
0.0
335    1.230981e+09
Name: Population, total, dtype: float64
0.05122241615961952
1021    28803167.0
Name: Population, total, dtype: float64
0.0
1658    152149102.0
Name: Population, total, dtype: float64
0.06612407936604307
7195    27023137.0
Name: Population, total, dtype: float64
0.6918111280033806
7685    170560182.0
Name: Population, total, dtype: float64
2.2810735350322258
9057    20198353.0
Name: Population, total, dtype: float64
1.1516962841557596
5823    2097555.0
Name: Population, total, dtype: float64
108.70874723942376
6901    619428.0
Name: Population, total, dtype: float64
122.62999269600742
1511    9054332.0
Name: Population, total, dtype: float64
52.702050732186315
2295    7395599.0
Name: Population, total, dtype: float64
210.04172480331707
2099    3722084.0
Name: Population, total, dtype: float64
103.23666412097869
874    72326914.0
Name: Population, total, dtype: float64
135.93787931237233
6117    3097282.0
Name: Population, total, dtype: float64
155.61953118628273
8224    20246871.0
Name: Population, total, dtype: float64
211.63199951570303
9498    7641630.0
Name: Population, total, dtype: float64
20.853615418633115
10086    45870700.0
Name: Population, total, dtype: float64
119.36353277093188
6754    3562045.0
Name: Population, total, dtype: float64
76.63975489635726
678    142849449.0
Name: Population, total, dtype: float64
132.27001397686587
5725    5447900.0
Name: Population, total, dtype: float64
142.7299889789786
7489    2070739.0
Name: Population, total, dtype: float64
218.21707449892253
8518    7291436.0
Name: Population, total, dtype: float64
113.25275355453596
1070    2913021.0
Name: Population, total, dtype: float64
59.84430554906229
5431    16321872.0
Name: Population, total, dtype: float64
94.00430556315015
1364    2877311.0
Name: Population, total, dtype: float64
187.41110961098667
1756    9490583.0
Name: Population, total, dtype: float64
168.24877118100426
6411    364511.0
Name: Population, total, dtype: float64
0.0
2001    727641.0
Name: Population, total, dtype: float64
0.0
335    1.230981e+09
Name: Population, total, dtype: float64
0.9593221795914512
1021    28803167.0
Name: Population, total, dtype: float64
19.04665134434528
1658    152149102.0
Name: Population, total, dtype: float64
1.110689340783976
7195    27023137.0
Name: Population, total, dtype: float64
2.5369715236270807
7685    170560182.0
Name: Population, total, dtype: float64
1.0975780630863363
9057    20198353.0
Name: Population, total, dtype: float64
31.35930664020606
4353    24512104.0
Name: Population, total, dtype: float64
28.46315371442011
5921    2040551.0
Name: Population, total, dtype: float64
14.74711136336237
7097    2173170.0
Name: Population, total, dtype: float64
10.780607587273138
3912    1202843.0
Name: Population, total, dtype: float64
20.198657613753316
8959    51584663.0
Name: Population, total, dtype: float64
46.287342251284656
3961    87702670.0
Name: Population, total, dtype: float64
20.070782862618163
4255    1692149.0
Name: Population, total, dtype: float64
27.939540334541213
6656    1250400.0
Name: Population, total, dtype: float64
51.86165014755526
6999    24221405.0
Name: Population, total, dtype: float64
10.297930087380532
5970    3948125.0
Name: Population, total, dtype: float64
8.035896544367851
5480    41350152.0
Name: Population, total, dtype: float64
12.801920496231997

2442    502384.0
Name: Population, total, dtype: float64
0.0
7440    158578261.0
Name: Population, total, dtype: float64
12.796529144806284
6313    15167095.0
Name: Population, total, dtype: float64
7.460338682466168
6607    3609543.0
Name: Population, total, dtype: float64
0.0
1903    9199259.0
Name: Population, total, dtype: float64
10.715392521527793
2344    15605217.0
Name: Population, total, dtype: float64
3.2020565138179595
3128    20401331.0
Name: Population, total, dtype: float64
13.990916996741234
2540    19970495.0
Name: Population, total, dtype: float64
13.039822997869756
3030    4386693.0
Name: Population, total, dtype: float64
24.143826718416
4206    1640210.0
Name: Population, total, dtype: float64
61.53036799274999
6460    15075085.0
Name: Population, total, dtype: float64
7.631279479452989
7391    16425578.0
Name: Population, total, dtype: float64
2.533665645250023
9694    6502952.0
Name: Population, total, dtype: float64
2.2939851798072253
8469    12916229.0
Name: Population, total, dtype: float64
38.94809547679183
2736    11887202.0
Name: Population, total, dtype: float64
5.6770402249412975
8273    10246842.0
Name: Population, total, dtype: float64
3.5714515586784716
2981    64523263.0
Name: Population, total, dtype: float64
4.344117021102496
2393    8766930.0
Name: Population, total, dtype: float64
2.3452901640856476
9547    46098591.0
Name: Population, total, dtype: float64
2.731328847802019
6264    21151640.0
Name: Population, total, dtype: float64
2.3988722366077027
10037    33915133.0
Name: Population, total, dtype: float64
6.965683966628078
8616    6458720.0
Name: Population, total, dtype: float64
15.836101043400996
10576    13850033.0
Name: Population, total, dtype: float64
13.735998051764875
4696    10794170.0
Name: Population, total, dtype: float64
27.851264392957802
8420    174776.0
Name: Population, total, dtype: float64
260.8976972942526
9645    1109591.0
Name: Population, total, dtype: float64
13.752377603052977
4059    859950.0
Name: Population, total, dtype: float64
22.870029240985964
7832    7108239.0
Name: Population, total, dtype: float64
32.73612486000759
188    1.337705e+09
Name: Population, total, dtype: float64
5.482451377634339
9596    67208808.0
Name: Population, total, dtype: float64
19.02815818625065
7979    93726624.0
Name: Population, total, dtype: float64
16.79082112102234
6852    2712650.0
Name: Population, total, dtype: float64
38.94665563028442
2491    14308740.0
Name: Population, total, dtype: float64
4.096214019446707
5774    6246274.0
Name: Population, total, dtype: float64
1.1324602240921242
384    242524123.0
Name: Population, total, dtype: float64
6.415735619899462
10380    88472512.0
Name: Population, total, dtype: float64
3.0413543943890464
3716    6164626.0
Name: Population, total, dtype: float64
230.84605228239894
139    196796269.0
Name: Population, total, dtype: float64
48.009496630517575
7930    29373646.0
Name: Population, total, dtype: float64
48.6440444846126
2050    9918242.0
Name: Population, total, dtype: float64
88.04210659673798
4647    14630417.0
Name: Population, total, dtype: float64
71.37149442075588
580    117318941.0
Name: Population, total, dtype: float64
19.465461200822443
4892    8194778.0
Name: Population, total, dtype: float64
42.961958287811406
7342    5737723.0
Name: Population, total, dtype: float64
12.260628366073258
5333    2817210.0
Name: Population, total, dtype: float64
33.07212401985621
2883    45918097.0
Name: Population, total, dtype: float64
65.22754828975634
5382    7182390.0
Name: Population, total, dtype: float64
53.09537912414304
5137    30762701.0
Name: Population, total, dtype: float64
8.258212621337174
3667    84107606.0
Name: Population, total, dtype: float64
23.00256469027526
6950    32409639.0
Name: Population, total, dtype: float64
19.582861977492357
3471    851146.0
Name: Population, total, dtype: float64
50.00628383206412
10527    23606779.0
Name: Population, total, dtype: float64
14.533579922468448
4353    24512104.0
Name: Population, total, dtype: float64
12.459712357841472
5921    2040551.0
Name: Population, total, dtype: float64
2.2392628651209834
7097    2173170.0
Name: Population, total, dtype: float64
5.26891777499466
3716    6164626.0
Name: Population, total, dtype: float64
0.0
139    196796269.0
Name: Population, total, dtype: float64
174.909384712355
7930    29373646.0
Name: Population, total, dtype: float64
78.52726571108434
2050    9918242.0
Name: Population, total, dtype: float64
19.14691091130991
4647    14630417.0
Name: Population, total, dtype: float64
101.4591802372652
580    117318941.0
Name: Population, total, dtype: float64
18.610836894333847
4892    8194778.0
Name: Population, total, dtype: float64
0.0
7342    5737723.0
Name: Population, total, dtype: float64
21.678795726944095
5333    2817210.0
Name: Population, total, dtype: float64
50.3908133553212
2883    45918097.0
Name: Population, total, dtype: float64
13.546933448065376
5382    7182390.0
Name: Population, total, dtype: float64
23.035040272180417
5137    30762701.0
Name: Population, total, dtype: float64
20.66114650629633
3667    84107606.0
Name: Population, total, dtype: float64
45.263482819962604
6950    32409639.0
Name: Population, total, dtype: float64
62.0684917234874
3471    851146.0
Name: Population, total, dtype: float64
21.563314400691812
10527    23606779.0
Name: Population, total, dtype: float64
63.164798393371456
9645    1109591.0
Name: Population, total, dtype: float64
0.0
4059    859950.0
Name: Population, total, dtype: float64
19.105771333317705
7832    7108239.0
Name: Population, total, dtype: float64
8.749431835654487
188    1.337705e+09
Name: Population, total, dtype: float64
111.40255503834848
9596    67208808.0
Name: Population, total, dtype: float64
13.625673986232067
7979    93726624.0
Name: Population, total, dtype: float64
9.14371773500287
6852    2712650.0
Name: Population, total, dtype: float64
10.576269074025616
2491    14308740.0
Name: Population, total, dtype: float64
40.97877828113319
5774    6246274.0
Name: Population, total, dtype: float64
10.502362334390305
384    242524123.0
Name: Population, total, dtype: float64
3.7358024200421505
10380    88472512.0
Name: Population, total, dtype: float64
22.01614308907999
3912    1202843.0
Name: Population, total, dtype: float64
4.253374918581238
8959    51584663.0
Name: Population, total, dtype: float64
23.167164341589615
3961    87702670.0
Name: Population, total, dtype: float64
2.2317559167156302
4255    1692149.0
Name: Population, total, dtype: float64
9.312758092498944
6656    1250400.0
Name: Population, total, dtype: float64
25.99065890835979
6999    24221405.0
Name: Population, total, dtype: float64
0.9420654938298846
5970    3948125.0
Name: Population, total, dtype: float64
5.371483896457769
5480    41350152.0
Name: Population, total, dtype: float64
5.436163249958575
2442    502384.0
Name: Population, total, dtype: float64
19.968310916166036
7440    158578261.0
Name: Population, total, dtype: float64
32.59281919816762
6313    15167095.0
Name: Population, total, dtype: float64
0.19679752093024375
6607    3609543.0
Name: Population, total, dtype: float64
32.16033100475167
1903    9199259.0
Name: Population, total, dtype: float64
23.662785435861636
2344    15605217.0
Name: Population, total, dtype: float64
5.014672840124652
3128    20401331.0
Name: Population, total, dtype: float64
34.36143024024275
2540    19970495.0
Name: Population, total, dtype: float64
21.891777321158017
3030    4386693.0
Name: Population, total, dtype: float64
15.609993529136181
4206    1640210.0
Name: Population, total, dtype: float64
33.59927601814427
6460    15075085.0
Name: Population, total, dtype: float64
9.762240554990527
7391    16425578.0
Name: Population, total, dtype: float64
5.390368091750825
9694    6502952.0
Name: Population, total, dtype: float64
18.547861961449996
8469    12916229.0
Name: Population, total, dtype: float64
15.490564036497796
2736    11887202.0
Name: Population, total, dtype: float64
15.164669283867667
8273    10246842.0
Name: Population, total, dtype: float64
1.6385918293351265
2981    64523263.0
Name: Population, total, dtype: float64
2.547649495401697
2393    8766930.0
Name: Population, total, dtype: float64
12.674203993431373
9547    46098591.0
Name: Population, total, dtype: float64
0.6282458767937215
6264    21151640.0
Name: Population, total, dtype: float64
1.6122172555627994
10037    33915133.0
Name: Population, total, dtype: float64
29.941884140610952
8616    6458720.0
Name: Population, total, dtype: float64
79.42767776067835
10576    13850033.0
Name: Population, total, dtype: float64
0.21952621801420574
4696    10794170.0
Name: Population, total, dtype: float64
17.77359715866128
8420    174776.0
Name: Population, total, dtype: float64
92.14028360715623
5823    2097555.0
Name: Population, total, dtype: float64
193.32367170850176
6901    619428.0
Name: Population, total, dtype: float64
88.76248889471316
1511    9054332.0
Name: Population, total, dtype: float64
32.10083160714622
2295    7395599.0
Name: Population, total, dtype: float64
0.0
2099    3722084.0
Name: Population, total, dtype: float64
222.91743170824552
874    72326914.0
Name: Population, total, dtype: float64
25.57298439456798
6117    3097282.0
Name: Population, total, dtype: float64
157.9139555141968
8224    20246871.0
Name: Population, total, dtype: float64
133.21971777150412
9498    7641630.0
Name: Population, total, dtype: float64
52.58987885535506
10086    45870700.0
Name: Population, total, dtype: float64
68.34597236686663
6754    3562045.0
Name: Population, total, dtype: float64
265.1568816286681
678    142849449.0
Name: Population, total, dtype: float64
108.98940021947533
5725    5447900.0
Name: Population, total, dtype: float64
13.279782847561208
7489    2070739.0
Name: Population, total, dtype: float64
126.22591311708067
8518    7291436.0
Name: Population, total, dtype: float64
115.84098796481207
1070    2913021.0
Name: Population, total, dtype: float64
72.50959745459254
5431    16321872.0
Name: Population, total, dtype: float64
44.48273699143743
1364    2877311.0
Name: Population, total, dtype: float64
31.44756663419363
1756    9490583.0
Name: Population, total, dtype: float64
115.7785139962079
6411    364511.0
Name: Population, total, dtype: float64
24.745473126856524
2001    727641.0
Name: Population, total, dtype: float64
2.0900067675886094
335    1.230981e+09
Name: Population, total, dtype: float64
26.225849053299154
1021    28803167.0
Name: Population, total, dtype: float64
47.49611526588572
1658    152149102.0
Name: Population, total, dtype: float64
16.524639645238853
7195    27023137.0
Name: Population, total, dtype: float64
71.46138364890487
7685    170560182.0
Name: Population, total, dtype: float64
7.512500899352603
9057    20198353.0
Name: Population, total, dtype: float64
27.024970964034978

In [11]:
csp[csp["country_code"]=="CHN"]
#csp

,country_code,area,product,value,exchange_rate,consumption_segment,indicator,ppp_conversion_factor,unit,buy
511,CHN,National,Fresh or Chilled Vegetables Other than Potatoes,4.270758e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,75.564515
4690,CHN,National,Fresh Milk,1.313754e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,23.244868
8484,CHN,National,Education,9.240416e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,163.495000
12438,CHN,National,Pork,3.969513e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,70.234447
17402,CHN,National,"Lamb, Mutton and Goat",4.844294e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,8.571236
20630,CHN,National,Paramedical Services,1.339994e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,2.370914
24686,CHN,National,Pasta Products,6.782434e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,12.000476
29399,CHN,National,Water Utility,6.955548e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,12.306775
32876,CHN,National,"Frozen, Preserved or Processed Fruit and Fruit...",8.312906e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,14.708412
37409,CHN,National,"Frozen, Preserved or Processed Vegetables and ...",1.229030e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,21.745802
40867,CHN,National,Cheese,4.300981e+09,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,0.760993
44842,CHN,National,Shoes and Other Footwear,2.485659e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,43.979928
48925,CHN,National,"Fresh, Chilled or Frozen Fish and Seafood",2.166978e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,38.341360
53154,CHN,National,Preserved or Processed Fish and Seafood,1.150463e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,20.355681
57600,CHN,National,Fresh or Chilled Fruit,2.756709e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,48.775746
61404,CHN,National,Insurance,5.102531e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,9.028146
67677,CHN,National,Rice,2.261959e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,40.021895
69505,CHN,National,Fresh or Chilled Potatoes,2.243933e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,3.970295
74092,CHN,National,Other Medical Products,6.906123e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,12.219325
77432,CHN,National,Poultry,1.839428e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,32.545852
81375,CHN,National,Hospital Services,9.379958e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,16.596398
85998,CHN,National,Preserved Milk and Other Milk Products,8.289164e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,14.666405
89524,CHN,National,"Coffee, Tea and Cocoa",7.849823e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,13.889058
93787,CHN,National,Medical Services,1.073713e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,18.997708
97427,CHN,National,Spirits,5.787204e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,10.239570
101762,CHN,National,Wine,1.884551e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,3.334424
105961,CHN,National,Beef and Veal,7.034758e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,12.446925
109580,CHN,National,"Clothing Material, Other Articles of Clothing ...",2.241790e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,3.966504
114451,CHN,National,Eggs and Egg-Based Products,1.293174e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,22.880725
117819,CHN,National,Beer,3.427805e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,6.064976
121793,CHN,National,Tobacco,2.429192e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,42.980831
126725,CHN,National,Butter and Margarine,1.250119e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,2.211894
130355,CHN,National,Other Edible Oil and Fats,1.522982e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,26.946828
134999,CHN,National,Therapeutic Appliances and Equipment,3.642035e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,6.444023
138348,CHN,National,Narcotics,0.000000e+00,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,0.000000
142861,CHN,National,"Jams, Marmalades and Honey",3.320655e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,5.875390
146293,CHN,National,Garments,8.925234e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,157.918329
150076,CHN,National,Sugar,4.952573e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,8.762819
154456,CHN,National,Dental Services,1.339994e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,2.370914
158422,CHN,National,Bread,3.098574e+10,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,5.482451
162524,CHN,National,Pharmaceuticals Products,6.296254e+11,6.77,All,Annual household expenditure by product/service,4.225,Local Currency,111.402555

In [13]:
total = csp.groupby("country_code")["buy"].sum()

In [23]:
total.to_csv("../Data/Consumption/total.csv")

Index(['AFG', 'ALB', 'ARM', 'AZE', 'BDI', 'BEN', 'BFA', 'BGD', 'BGR', 'BIH',
       'BLR', 'BOL', 'BRA', 'BTN', 'CHN', 'CIV', 'CMR', 'COD', 'COG', 'COL',
       'CPV', 'DJI', 'EGY', 'ETH', 'FJI', 'GAB', 'GHA', 'GIN', 'GMB', 'GTM',
       'HND', 'IDN', 'IND', 'IRQ', 'JAM', 'JOR', 'KAZ', 'KEN', 'KGZ', 'KHM',
       'LAO', 'LBR', 'LKA', 'LSO', 'LTU', 'LVA', 'MAR', 'MDA', 'MDG', 'MDV',
       'MEX', 'MKD', 'MLI', 'MNE', 'MNG', 'MOZ', 'MRT', 'MUS', 'MWI', 'NAM',
       'NER', 'NGA', 'NIC', 'NPL', 'PAK', 'PER', 'PHL', 'PNG', 'ROU', 'RUS',
       'RWA', 'SEN', 'SLE', 'SLV', 'SRB', 'STP', 'SWZ', 'TCD', 'TGO', 'THA',
       'TJK', 'TLS', 'TUR', 'TZA', 'UGA', 'UKR', 'VNM', 'YEM', 'ZAF', 'ZMB'],
      dtype='object', name='country_code')

In [14]:
total[total["country_code"]=="USA"]

KeyError: 'country_code'

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data_dir = "../Datasets/consumption.csv"
csp = pd.read_csv(data_dir)#.head(5)
csp = csp[csp["indicator"]=="Share of product/service in total expenditure (%)"]
csp

,country_code,area,product,value,exchange_rate,consumption_segment,indicator,ppp_conversion_factor,unit
0,THA,National,Fresh or Chilled Vegetables Other than Potatoes,0.033900,31.686000,Lowest,Share of product/service in total expenditure (%),18.073000,%
1,PHL,National,Fresh or Chilled Vegetables Other than Potatoes,0.023000,45.109664,Lowest,Share of product/service in total expenditure (%),27.525623,%
2,MNG,National,Fresh or Chilled Vegetables Other than Potatoes,0.015200,1357.064000,Lowest,Share of product/service in total expenditure (%),785.100000,%
3,KHM,National,Fresh or Chilled Vegetables Other than Potatoes,0.046500,4184.917000,Lowest,Share of product/service in total expenditure (%),2134.943000,%
4,LAO,National,Fresh or Chilled Vegetables Other than Potatoes,0.061300,8258.770000,Lowest,Share of product/service in total expenditure (%),4268.571000,%
5,IDN,National,Fresh or Chilled Vegetables Other than Potatoes,0.050700,9090.433000,Lowest,Share of product/service in total expenditure (%),5467.129000,%
6,VNM,National,Fresh or Chilled Vegetables Other than Potatoes,0.024700,18612.917000,Lowest,Share of product/service in total expenditure (%),8847.418000,%
37,LVA,National,Fresh or Chilled Vegetables Other than Potatoes,0.035700,0.530000,Lowest,Share of product/service in total expenditure (%),0.418000,%
38,MNE,National,Fresh or Chilled Vegetables Other than Potatoes,0.072400,0.755000,Lowest,Share of product/service in total expenditure (%),0.484000,%
39,AZE,National,Fresh or Chilled Vegetables Other than Potatoes,0.069700,0.803000,Lowest,Share of product/service in total expenditure (%),0.517000,%
40,BGR,National,Fresh or Chilled Vegetables Other than Potatoes,0.053400,1.477000,Lowest,Share of product/service in total expenditure (%),0.811000,%
41,BIH,National,Fresh or Chilled Vegetables Other than Potatoes,0.018700,1.477000,Lowest,Share of product/service in total expenditure (%),0.901000,%
42,TUR,National,Fresh or Chilled Vegetables Other than Potatoes,0.062700,1.503000,Lowest,Share of product/service in total expenditure (%),1.162000,%
43,LTU,National,Fresh or Chilled Vegetables Other than Potatoes,0.035300,2.606000,Lowest,Share of product/service in total expenditure (%),1.834000,%
44,ROU,National,Fresh or Chilled Vegetables Other than Potatoes,0.067800,3.178000,Lowest,Share of product/service in total expenditure (%),2.021000,%
45,TJK,National,Fresh or Chilled Vegetables Other than Potatoes,0.060800,4.379000,Lowest,Share of product/service in total expenditure (%),1.410000,%
46,UKR,National,Fresh or Chilled Vegetables Other than Potatoes,0.062400,7.936000,Lowest,Share of product/service in total expenditure (%),2.990000,%
47,MDA,National,Fresh or Chilled Vegetables Other than Potatoes,0.034000,12.369000,Lowest,Share of product/service in total expenditure (%),6.632000,%
48,RUS,National,Fresh or Chilled Vegetables Other than Potatoes,0.059200,30.368000,Lowest,Share of product/service in total expenditure (%),17.411000,%
49,KGZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.055300,45.964000,Lowest,Share of product/service in total expenditure (%),19.458000,%
50,MKD,National,Fresh or Chilled Vegetables Other than Potatoes,0.077400,46.485000,Lowest,Share of product/service in total expenditure (%),22.320000,%
51,SRB,National,Fresh or Chilled Vegetables Other than Potatoes,0.069900,77.728933,Lowest,Share of product/service in total expenditure (%),44.773690,%
52,ALB,National,Fresh or Chilled Vegetables Other than Potatoes,0.084300,103.936000,Lowest,Share of product/service in total expenditure (%),57.851000,%
53,KAZ,National,Fresh or Chilled Vegetables Other than Potatoes,0.036200,147.355000,Lowest,Share of product/service in total expenditure (%),94.239000,%
54,ARM,National,Fresh or Chilled Vegetables Other than Potatoes,0.074800,373.660000,Lowest,Share of product/service in total expenditure (%),230.056000,%
55,BLR,National,Fresh or Chilled Vegetables Other than Potatoes,0.008420,2978.510000,Lowest,Share of product/service in total expenditure (%),1103.222000,%
78,LVA,National,Fresh or Chilled Vegetables Other than Potatoes,0.011400,0.530000,Higher,Share of product/service in total expenditure (%),0.418000,%
79,MNE,National,Fresh or Chilled Vegetables Other than Potatoes,0.016200,0.755000,Higher,Share of product/service in total expenditure (%),0.484000,%
80,AZE,National,Fresh or Chilled Vegetables Other than Potatoes,0.019000,0.803000,Higher,Share of product/service in total expenditure (%),0.517000,%
81,BGR,National,Fresh or Chilled Vegetables Other than Potatoes,0.012900,1.477000,Higher,Share of product/service in total expenditure (%),0.811000,%
...,...,...,...,...,...,...,...,...,...
165977,GMB,Urban,Pharmaceuticals Products,0.004790,28.012000,Higher,Share of product/service in total expenditure (%),11.429000,%
165978,MUS,Urban,Pharmaceuticals Products,0.022800,30.784000,Higher,Share of product/service in total expenditure (%),21.785000,%
165979,MOZ,Urban,Pharmaceuticals Products,0.002200,33.960000,Higher,Share of product/service in total expenditure (%),16.373000,%
165980,LBR,Urban,Pharmaceuticals Products,NaN,71.403000,Higher,Share of product/service in total expenditure (%),42.322000,%
165981,KEN,Urban,Pharmaceuticals Products,0.002520,79.233000,Higher,Share of product/service in total expenditure (%),52.716000,%
165982,CPV,Urban,Pharmaceuticals Products,0.006490,83.259000,Higher,Share of product/service in total expenditure (%),84.787000,%
165983,NGA,Urban,Pharmaceuticals Products,0.000000,150.298025,Higher,Share of product/service in total expenditure (%),113.614462,%
165984,MWI,Urban,Pharmaceuticals Products,0.000006,150.487000,Higher,Share of product/service in total expenditure (%),79.412000,%
165985,MRT,Urban,Pharmaceuticals Products,0.006890,275.894000,Higher,Share of product/service in total expenditure (%),149.566000,%
165986,BEN,Urban,Pharmaceuticals Products,NaN,495.277000,Higher,Share of product/service in total expenditure (%),292.319000,%
165987,BFA,Urban,Pharmaceuticals Products,0.007890,495.277000,Higher,Share of product/service in total expenditure (%),249.766000,%
165988,CIV,Urban,Pharmaceuticals Products,0.015600,495.277000,Higher,Share of product/service in total expenditure (%),332.673000,%
165989,CMR,Urban,Pharmaceuticals Products,0.013400,495.277000,Higher,Share of product/service in total expenditure (%),307.585000,%
165990,COG,Urban,Pharmaceuticals Products,0.004270,495.277000,Higher,Share of product/service in total expenditure (%),436.561000,%
165991,GAB,Urban,Pharmaceuticals Products,0.008200,495.277000,Higher,Share of product/service in total expenditure (%),447.817000,%
165992,MLI,Urban,Pharmaceuticals Products,0.016700,495.277000,Higher,Share of product/service in total expenditure (%),301.384000,%
165993,NER,Urban,Pharmaceuticals Products,0.000293,495.277000,Higher,Share of product/service in total expenditure (%),280.465000,%
165994,TGO,Urban,Pharmaceuticals Products,NaN,495.277000,Higher,Share of product/service in total expenditure (%),294.397000,%
165995,SEN,Urban,Pharmaceuticals Products,NaN,495.277022,Higher,Share of product/service in total expenditure (%),305.950234,%
166034,TLS,Urban,Pharmaceuticals Products,0.000000,1.000000,All,Share of product/service in total expenditure (%),0.590000,%
166035,FJI,Urban,Pharmaceuticals Products,0.010100,1.918000,All,Share of product/service in total expenditure (%),1.756000,%
166036,PNG,Urban,Pharmaceuticals Products,0.004480,2.719000,All,Share of product/service in total expenditure (%),1.960000,%
166037,CHN,Urban,Pharmaceuticals Products,0.049500,6.770000,All,Share of product/service in total expenditure (%),4.225000,%
166038,THA,Urban,Pharmaceuticals Products,0.005130,31.686000,All,Share of product/service in total expenditure (%),18.073000,%
166039,PHL,Urban,Pharmaceuticals Products,0.007530,45.109664,All,Share of product/service in total expenditure (%),27.525623,%
166040,MNG,Urban,Pharmaceuticals Products,0.006550,1357.064000,All,Share of product/service in total expenditure (%),785.100000,%
166041,KHM,Urban,Pharmaceuticals Products,0.017200,4184.917000,All,Share of product/service in total expenditure (%),2134.943000,%
166042,LAO,Urban,Pharmaceuticals Products,0.008980,8258.770000,All,Share of product/service in total expenditure (%),4268.571000,%
166043,IDN,Urban,Pharmaceuticals Products,0.003930,9090.433000,All,Share of product/service in total expenditure (%),5467.129000,%
166044,VNM,Urban,Pharmaceuticals Products,0.017100,18612.917000,All,Share of product/service in total expenditure (%),8847.418000,%

In [27]:
len(csp["country_code"].unique())

90